#!/bin/sh
# postrm script for waagent

set -e

if [ "$1" = remove ]; then
    rm -rf /var/lib/waagent
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/walinuxagent" ] ; then
	chmod -x "/etc/init.d/walinuxagent" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d walinuxagent remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'walinuxagent.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
