#!/bin/sh

if [ "$1" = "upgrade" ]; then
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
                deb-systemd-helper purge 'waagent-apt.service' >/dev/null || true
                deb-systemd-helper unmask 'waagent-apt.service' >/dev/null || true
        fi
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/walinuxagent" ] ; then
	chmod +x "/etc/init.d/walinuxagent" >/dev/null || true
fi
# End automatically added section

