#!/bin/sh
set -e
# Automatically added by dh_installinit/13.10.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/avr-evtd" ] ; then
	chmod -x "/etc/init.d/avr-evtd" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d avr-evtd remove >/dev/null
fi
# End automatically added section
