#!/bin/sh
set -e
# Automatically added by dh_installinit/13.10.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/avr-evtd" ] ; then
	chmod +x "/etc/init.d/avr-evtd" >/dev/null || true
fi
# End automatically added section
