#!/bin/sh
set -e
# Automatically added by dh_installinit/13.10.1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/avr-evtd" ] ; then
	invoke-rc.d --skip-systemd-native avr-evtd stop || exit 1
fi
# End automatically added section
