#!/bin/sh
# postrm script for radicale

set -e

NAME=radicale
RUNDIR=/run/$NAME
LOGDIR=/var/log/$NAME
CACHEDIR=/var/cache/$NAME

case "$1" in
  remove)
	rm -rf $RUNDIR
	;;

  purge)
	rm -rf $LOGDIR $CACHEDIR

	# We do NOT remove the system user.
	;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/radicale" ] ; then
	chmod -x "/etc/init.d/radicale" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d radicale remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'radicale.service' >/dev/null || true
	fi
fi
# End automatically added section

