#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/rarpd" ] ; then
	invoke-rc.d rarpd stop || exit 1
fi
# End automatically added section
