#! /bin/sh

set -e

if [ "$1" = "purge" ]; then
  if dpkg-statoverride --list /var/lib/ixfrdist > /dev/null 2>&1
  then
    dpkg-statoverride --remove /var/lib/ixfrdist
  fi
fi

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ixfrdist.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
