#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper mv_conffile /etc/mailfromd/mailfromd.mf /etc/mailfromd/mailfromd.mfl 8.15\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/mailfromd" ] ; then
	chmod +x "/etc/init.d/mailfromd" >/dev/null || true
fi
# End automatically added section
