#!/bin/sh

set -e

case "$1" in
    purge)
        rm -f  /etc/zabbix/zabbix_java_gateway.conf \
               /etc/zabbix/logback-console.xml      \
               /etc/zabbix/logback.xml
        rm -fr /var/log/zabbix-java-gateway
        rm -f  /run/zabbix/zabbix_gateway_java.pid
    ;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/zabbix-java-gateway" ] ; then
	chmod -x "/etc/init.d/zabbix-java-gateway" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d zabbix-java-gateway remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'zabbix-java-gateway.service' >/dev/null || true
	fi
fi
# End automatically added section

