#!/bin/sh
set -e
# Automatically added by dh_runit/2.16.4
# Unlike postrm, I can be sure, that runit-helper is present on
# prerm.
#start: remove after trixie
if  [ ! -e /usr/lib/runit-helper/runit-helper ]; then
    #should not happen
    echo "warning: can't find runit-helper, prerm action skipped!"
    echo "warning: runit-helper: please report this bug"
fi
#end: remove after trixie
if [ -z "${DPKG_ROOT:-}" ]  && [ -x /usr/lib/runit-helper/runit-helper ]; then
    NAME='dnscache' ENABLE='no' ONUPGRADE='restart' /usr/lib/runit-helper/runit-helper prerm "$@"
fi
# End automatically added section
