#!/bin/sh
set -e


case "$1" in
    # only remove in remove/deconfigure so we don't disrupt users' preferences
    remove|deconfigure)
        update-alternatives --remove org.fedoraproject.FirewallD1.policy \
            /usr/share/polkit-1/actions/org.fedoraproject.FirewallD1.server.policy.choice
        update-alternatives --remove org.fedoraproject.FirewallD1.policy \
            /usr/share/polkit-1/actions/org.fedoraproject.FirewallD1.desktop.policy.choice
        ;;

    upgrade|failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'firewalld.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/firewalld" ] ; then
	invoke-rc.d --skip-systemd-native firewalld stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/firewalld/lockdown-whitelist.xml 2.3.0-2\~ -- "$@"
# End automatically added section


exit 0
