#!/bin/sh
set -e
# Automatically added by dh_installinit/13.16
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/clamsmtp" ] ; then
	invoke-rc.d clamsmtp stop || exit 1
fi
# End automatically added section
