#! /bin/sh

set -e

case "$1" in
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    purge)
        getent passwd pglisten >/dev/null && \
        if [ -x /usr/sbin/deluser ]; then
            deluser --quiet --system pglisten
        fi
        rm -rf /var/lib/pglistener
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/pglistener" ] ; then
	chmod -x "/etc/init.d/pglistener" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d pglistener remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'pglistener.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0

