#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    # Configure dnsmasq
    if [ -f /etc/dnsmasq.d-available/incus ] && [ ! -e /etc/dnsmasq.d/incus ]; then
        echo "Setting up incus dnsmasq configuration."
        mkdir -p /etc/dnsmasq.d
        ln -s /etc/dnsmasq.d-available/incus /etc/dnsmasq.d/incus

        # Try to restart a potential system wide dnsmasq
        invoke-rc.d dnsmasq restart 2>/dev/null || true
    fi

    # On initial installation (incus-admin group not yet created), setup idmaps.
    # Ranges follow suggestions from https://linuxcontainers.org/incus/docs/main/installing/
    if ! getent group incus-admin >/dev/null; then
        # Run in a sub-shell to avoid messing with the script arguments.
        (
            if ! grep "root:" /etc/subuid >/dev/null; then
                # UID allocation
                NEXT_UID=999999
                while read line; do
                    OLD_IFS=$IFS
                    IFS=":"
                    set -- $line
                    IFS=$OLD_IFS

                    [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] && continue

                    LAST=$(($2+$3))
                    [ "$LAST" -gt "$NEXT_UID" ] && NEXT_UID=$LAST
                done < /etc/subuid
                usermod --add-subuids $((NEXT_UID+1))-$((NEXT_UID+1000000000)) root
            else
                echo "A subuid range is already defined for the root user; please verify that it has a range of at least 1,000,000,000 uids"
            fi

            if ! grep "root:" /etc/subgid >/dev/null; then
                # GID allocation
                NEXT_GID=999999
                while read line; do
                    OLD_IFS=$IFS
                    IFS=":"
                    set -- $line
                    IFS=$OLD_IFS

                    [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] && continue

                    LAST=$(($2+$3))
                    [ "$LAST" -gt "$NEXT_GID" ] && NEXT_GID=$LAST
                done < /etc/subgid
                usermod --add-subgids $((NEXT_GID+1))-$((NEXT_GID+1000000000)) root
            else
                echo "A subgid range is already defined for the root user; please verify that it has a range of at least 1,000,000,000 gids"
            fi
        )
    fi
fi

# Automatically added by dh_installsysusers/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
   systemd-sysusers ${DPKG_ROOT:+--root="$DPKG_ROOT"} incus.conf
fi
# End automatically added section
# Automatically added by dh_runit/2.16.4
# Unlike postrm, I can be sure, that runit-helper is present on
# postinst.
#start: remove after trixie
if  [ ! -e /usr/lib/runit-helper/runit-helper ]; then
    #should not happen
    echo "warning: can't find runit-helper, postinst action skipped!"
    echo "warning: runit-helper: please report this bug"
fi
#end: remove after trixie
if [ -z "${DPKG_ROOT:-}" ] && [ -x /usr/lib/runit-helper/runit-helper ]; then
    NAME='incus' ENABLE='yes' ONUPGRADE='stop' /usr/lib/runit-helper/runit-helper postinst "$@"
fi
# End automatically added section
# Automatically added by dh_runit/2.16.4
# Unlike postrm, I can be sure, that runit-helper is present on
# postinst.
#start: remove after trixie
if  [ ! -e /usr/lib/runit-helper/runit-helper ]; then
    #should not happen
    echo "warning: can't find runit-helper, postinst action skipped!"
    echo "warning: runit-helper: please report this bug"
fi
#end: remove after trixie
if [ -z "${DPKG_ROOT:-}" ] && [ -x /usr/lib/runit-helper/runit-helper ]; then
    NAME='incus-user' ENABLE='no' ONUPGRADE='stop' /usr/lib/runit-helper/runit-helper postinst "$@"
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/incus" ]; then
		update-rc.d incus defaults >/dev/null
		invoke-rc.d --skip-systemd-native incus start || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/incus-user" ]; then
		update-rc.d incus-user defaults >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/incus-startup" ]; then
		update-rc.d incus-startup defaults >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'incus-startup.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'incus-startup.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'incus-startup.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'incus-startup.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'incus-startup.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'incus-startup.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'incus-startup.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'incus-startup.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'incus.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'incus.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'incus.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'incus.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'incus.socket' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'incus.socket'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'incus.socket' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'incus.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'incus-user.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'incus-user.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'incus-user.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'incus-user.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'incus-user.socket' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'incus-user.socket'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'incus-user.socket' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'incus-user.socket' >/dev/null || true
	fi
fi
# End automatically added section


# Handle services start / restart manually, dh_installsystemd won't allow
# restarting incus.service and incus-user.service on upgrades but not incus-startup.service
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
        if [ -n "$2" ]; then
            _dh_action=restart
        else
            _dh_action=start
        fi
        deb-systemd-invoke $_dh_action 'incus.service' 'incus.socket' 'incus-user.service' 'incus-user.socket' >/dev/null || true

        # Only start 'incus-startup', don't restart it on upgrades
        deb-systemd-invoke start 'incus-startup.service' >/dev/null || true
    fi
fi

# Print the install message
if [ "$1" = "configure" ] && [ -z "$2" ]; then
    echo ""
    echo "Incus has been installed. You must run \`sudo incus admin init\` to"
    echo "perform the initial configuration of Incus."
    echo "Be sure to add user(s) to either the 'incus-admin' group for full"
    echo "administrative access or the 'incus' group for restricted access,"
    echo "then have them logout and back in to properly setup their access."
    echo ""
fi

exit 0
