#!/bin/sh

# Exit immediately if a command produces an error.
set -e

# Source debconf library
. /usr/share/debconf/confmodule

del_override() {
    if dpkg-statoverride --list $1 >/dev/null; then
	dpkg-statoverride --remove $1
    fi
}

if [ "$1" = "purge" ]; then
    # remove cache with authentification info
    rm -rf /var/cache/sqwebmail

    db_get sqwebmail/install-www || [ $? -eq 10 ]
    if [ "$RET" = "symlink" ]; then
	rm -f /var/www/sqwebmail
    elif [ "$RET" = "copy" ]; then
	rm -rf /var/www/sqwebmail
    fi

    # remove calendar mode configuration file
    rm -f /etc/courier/calendarmode

    # remove ispelldict configuration
    rm -f /etc/courier/ispelldict

    del_override /usr/lib/courier/courier/webmail
    del_override /usr/lib/courier/courier/sqwebpasswd
    del_override /var/cache/sqwebmail
    del_override /var/lib/courier/calendar
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/sqwebmail" ] ; then
	chmod -x "/etc/init.d/sqwebmail" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d sqwebmail remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'sqwebmail.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_apache2/UNDECLARED
if [ "$1" = "purge" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in sqwebmail.apache24  ; do
				apache2_invoke disconf $conf  || exit 1
			done
		fi
	fi
fi
# End automatically added section

