#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -n "$EX4DEBUG" ]; then
  echo "now debugging $0 $@"
  set -x
fi

dc_eximconfig_configtype="other"
db_get exim4/dc_eximconfig_configtype || true
if [ "$RET" = "no configuration at this time" ]; then
  dc_eximconfig_configtype="none"
fi
db_stop

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || \
	[ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if ! [ -d /run/systemd/system ] && [ -x /etc/init.d/exim4 ]; then
	# SysV Init
	# || true is needed for succesfull installation with configtype 'none'
		if [ "$dc_eximconfig_configtype" = "none" ]; then
			# we may have broken config here, ignore errors
			invoke-rc.d exim4 start || true
		else
			# we must have working config here, honor errors
			invoke-rc.d exim4 start
		fi
	fi
fi


# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'exim4.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'exim4.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'exim4.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'exim4.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'exim4.service' >/dev/null || true
	fi
fi
# End automatically added section

