#!/bin/sh

set -e

case "$1" in
    remove)
	# Remove stale pid files
	rm -f /var/run/dhcpd.pid /var/run/dhcpd6.pid
	;;

    purge)
	# Remove database
	rm -f /var/lib/dhcp/dhcpd.leases /var/lib/dhcp/dhcpd.leases~

	# Remove database directory
	if [ -d /var/lib/dhcp ]; then
	    rmdir --ignore-fail-on-non-empty /var/lib/dhcp/
	fi

	# Remove init.d configuration file
	rm -f /etc/default/isc-dhcp-server
	;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	# Nothing to do
	;;
esac

init_script_error_handler()
{
	return 0
}

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/isc-dhcp-server" ] ; then
	chmod -x "/etc/init.d/isc-dhcp-server" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d isc-dhcp-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_apparmor/4.1.0-1
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.sbin.dhcpd" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.sbin.dhcpd" || true
    rm -f "/etc/apparmor.d/force-complain/usr.sbin.dhcpd" || true
    rm -f "/etc/apparmor.d/local/usr.sbin.dhcpd" || true
    rm -f /var/cache/apparmor/*/"usr.sbin.dhcpd" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section


exit 0
