#!/bin/sh

set -e

init_script_error_handler()
{
	return 0
}

# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/isc-dhcp-server" ] ; then
	invoke-rc.d --skip-systemd-native isc-dhcp-server stop || true
fi
# End automatically added section


exit 0
