#!/bin/sh
set -e
# Automatically added by dh_apparmor/4.1.0~beta5-6
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.lib.lomiri-download-manager.ldm-extractor" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.lib.lomiri-download-manager.ldm-extractor" || true
    rm -f "/etc/apparmor.d/force-complain/usr.lib.lomiri-download-manager.ldm-extractor" || true
    rm -f "/etc/apparmor.d/local/usr.lib.lomiri-download-manager.ldm-extractor" || true
    rm -f /var/cache/apparmor/*/"usr.lib.lomiri-download-manager.ldm-extractor" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section
