#!/bin/sh
set -e
# Automatically added by dh_installinit/13.12
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/battery-stats" ] ; then
	chmod +x "/etc/init.d/battery-stats" >/dev/null || true
fi
# End automatically added section
