#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/zfs-fuse 0.7.0-13.1 -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/zfs-fuse" ] ; then
	chmod +x "/etc/init.d/zfs-fuse" >/dev/null || true
fi
# End automatically added section
