#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
      invoke-rc.d zfs-fuse stop || exit $?
      rm -f /var/lib/zfs/zpool.cache
      ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'zfs-fuse.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/zfs-fuse 0.7.0-13.1 -- "$@"
# End automatically added section

