#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/iscsiuio" ] ; then
	chmod +x "/etc/init.d/iscsiuio" >/dev/null || true
fi
# End automatically added section
