#!/bin/sh

set -eu

CONFFILE="/etc/valkey/sentinel.conf"

if [ "$1" = "purge" ]
then
	dpkg-statoverride --remove ${CONFFILE} || test $? -eq 2
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/valkey-sentinel" ] ; then
	chmod -x "/etc/init.d/valkey-sentinel" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d valkey-sentinel remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'valkey-sentinel.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
