#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/masakari-host-monitor" ] ; then
	invoke-rc.d masakari-host-monitor stop || true
fi
# End automatically added section
