#!/bin/sh -e
set -e

if [ x"$1" = "xpurge" ]; then
  rm -rf /etc/dqcache /var/lib/dqcache
  deluser --force dqcache || :
fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/dqcache" ] ; then
	chmod -x "/etc/init.d/dqcache" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d dqcache remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'dqcache.service' >/dev/null || true
	fi
fi
# End automatically added section

