#!/bin/sh -e
set -e

# upgrading from version < 20181021-1
# remove user dqcachelog
if [ x"$1" = "xupgrade" ]; then
  if [ x"$2" != "x" ]; then
    if dpkg --compare-versions "$2" lt '20181021-1'; then
      deluser --force dqcachelog || :
    fi
  fi
fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/dqcache" ] ; then
	chmod +x "/etc/init.d/dqcache" >/dev/null || true
fi
# End automatically added section

