#! /bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
		rm -f /var/spool/nullmailer/trigger
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/nullmailer" ] ; then
	invoke-rc.d nullmailer stop || exit 1
fi
# End automatically added section


exit 0
