#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/moosefs-master" ]; then
		update-rc.d moosefs-master defaults >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'moosefs-master.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'moosefs-master.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'moosefs-master.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'moosefs-master.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'moosefs-master.service' >/dev/null || true
fi
# End automatically added section
