#!/bin/sh
set -e
# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/dibbler-server" ] ; then
	chmod -x "/etc/init.d/dibbler-server" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d dibbler-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.20
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
