#!/bin/sh

set -e

case "$1" in
  purge)
    userdel rdnssd >/dev/null 2>&1 || true
    rm -f -- /var/run/rdnssd/resolv.conf 2>/dev/null
    rmdir -- /var/run/rdnssd/ || true
  ;;
esac

# Automatically added by dh_installinit/13.11.9
if [ "$1" = "remove" ] && [ -x "/etc/init.d/rdnssd" ] ; then
	chmod -x "/etc/init.d/rdnssd" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d rdnssd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.9
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.9
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'rdnssd.service' >/dev/null || true
	fi
fi
# End automatically added section


