#!/bin/sh

# Exit immediately if a command produces an error.
set -e

del_override() {
    if dpkg-statoverride --list $1 >/dev/null; then
	dpkg-statoverride --remove $1
    fi
}

if [ "$1" = "purge" ]; then
    rm -f /etc/courier/imapd.pem
    rm -f /etc/courier/imapaccess.dat
    del_override /etc/courier/imapd.cnf
    del_override /etc/courier/imapaccess
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/courier-imap-ssl" ] ; then
	chmod -x "/etc/init.d/courier-imap-ssl" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d courier-imap-ssl remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/courier-imap" ] ; then
	chmod -x "/etc/init.d/courier-imap" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d courier-imap remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'courier-imap-ssl.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'courier-imap.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
