#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/courier-imap" ] ; then
	chmod +x "/etc/init.d/courier-imap" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/courier-imap-ssl" ] ; then
	chmod +x "/etc/init.d/courier-imap-ssl" >/dev/null || true
fi
# End automatically added section
