#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/vitrage-graph" ] ; then
	invoke-rc.d vitrage-graph stop || true
fi
# End automatically added section
