#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/busybox-syslogd" ] ; then
	chmod -x "/etc/init.d/busybox-syslogd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d busybox-syslogd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/busybox-klogd" ] ; then
	chmod -x "/etc/init.d/busybox-klogd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d busybox-klogd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'busybox-klogd.service' 'busybox-syslogd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'busybox-klogd.service' >/dev/null || true
	fi
fi
# End automatically added section
