#!/bin/sh
set -e

# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p vdirsyncer 
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p vdirsyncer  || true
fi

# End automatically added section
# Automatically added by dh_installsystemduser/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ]; then
		if deb-systemd-helper --user debian-installed 'vdirsyncer.timer' ; then
			# The following line should be removed in trixie or trixie+1
			deb-systemd-helper --user unmask 'vdirsyncer.timer' >/dev/null || true

			if deb-systemd-helper --quiet --user was-enabled 'vdirsyncer.timer' ; then
				# Create new symlinks, if any.
				deb-systemd-helper --user enable 'vdirsyncer.timer' >/dev/null || true
			fi
		fi

		# Update the statefile to add new symlinks (if any), which need to be cleaned
		# up on purge. Also remove old symlinks.
		deb-systemd-helper --user update-state 'vdirsyncer.timer' >/dev/null || true
	fi
fi
# End automatically added section
