#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper mv_conffile /etc/init.d/pmacct /etc/init.d/pmacctd 1.5.0-1\~\~ pmacct -- "$@"
dpkg-maintscript-helper mv_conffile /etc/default/pmacct /etc/default/pmacctd 1.5.0-1\~\~ pmacct -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/pmacctd" ]; then
		update-rc.d pmacctd defaults >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/nfacctd" ]; then
		update-rc.d nfacctd defaults >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/sfacctd" ]; then
		update-rc.d sfacctd defaults >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/uacctd" ]; then
		update-rc.d uacctd defaults >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'pmacctd.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'pmacctd.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'pmacctd.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'pmacctd.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'pmacctd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'nfacctd.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'nfacctd.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'nfacctd.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'nfacctd.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'nfacctd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'sfacctd.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'sfacctd.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'sfacctd.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'sfacctd.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'sfacctd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'uacctd.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'uacctd.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'uacctd.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'uacctd.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'uacctd.service' >/dev/null || true
fi
# End automatically added section
