#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper mv_conffile /etc/init.d/pmacct /etc/init.d/pmacctd 1.5.0-1\~\~ pmacct -- "$@"
dpkg-maintscript-helper mv_conffile /etc/default/pmacct /etc/default/pmacctd 1.5.0-1\~\~ pmacct -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/pmacctd" ] ; then
	chmod +x "/etc/init.d/pmacctd" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/nfacctd" ] ; then
	chmod +x "/etc/init.d/nfacctd" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/sfacctd" ] ; then
	chmod +x "/etc/init.d/sfacctd" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/uacctd" ] ; then
	chmod +x "/etc/init.d/uacctd" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'pmacctd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'nfacctd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'sfacctd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'uacctd.service' >/dev/null || true
fi
# End automatically added section
