#!/bin/sh
set -e
# Automatically added by dh_installsystemduser/13.11.8
if [ "$1" = "purge" ]; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'psd-resync.service' 'psd.service' >/dev/null || true
	fi
fi
# End automatically added section
