#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/neutron-l3-agent" ] ; then
	invoke-rc.d neutron-l3-agent stop || true
fi
# End automatically added section
