#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/default/glances 2.11.1-3 glances -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/glances" ] ; then
	chmod +x "/etc/init.d/glances" >/dev/null || true
fi
# End automatically added section
