#!/bin/sh
set -e

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'keyd.service' >/dev/null || true
	fi
fi
# End automatically added section


if [ "$1" = purge ]; then
    # The passwd package is `Priority: required` and is in `Depends`, but the package might be
    # uninstalled before keyd in environments like a piuparts chroot.
    if command -v groupdel >/dev/null; then
        if getent group keyd >/dev/null; then
            groupdel keyd
        elif [ "$?" -ne 2 ]; then
            exit 1
        fi
    fi
fi
