#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/lighttpd/conf-available/10-flv-streaming.conf 1.4.63-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/lighttpd" ] ; then
	chmod +x "/etc/init.d/lighttpd" >/dev/null || true
fi
# End automatically added section
