#!/bin/sh

set -e

if [ "${1}" = "purge" ] ; then
	rm -f /etc/init/neutron-l2gateway-agent.override
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/neutron-l2gateway-agent" ] ; then
	chmod -x "/etc/init.d/neutron-l2gateway-agent" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d neutron-l2gateway-agent remove >/dev/null
fi
# End automatically added section


exit 0
