#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.9
if [ "$1" = "remove" ] && [ -x "/etc/init.d/writeboost" ] ; then
	chmod -x "/etc/init.d/writeboost" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d writeboost remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.9
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'writeboost.service' >/dev/null || true
	fi
fi
# End automatically added section
