#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.9
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/writeboost" ] ; then
	chmod +x "/etc/init.d/writeboost" >/dev/null || true
fi
# End automatically added section
