#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'kylin-process-manager-cleaner.service' 'kylin-process-manager-daemon.service' >/dev/null || true
fi
# End automatically added section
