#!/bin/sh -e

case "$1" in
    configure)
        update-alternatives --install /usr/sbin/policy-rc.d policy-rc.d \
            /usr/bin/policy-rc.d.fai 100
        update-rc.d fai-abort defaults >/dev/null
esac

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'fai.service' 'fai.target' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
