#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/sv/default-syslog/finish 2.1.2-60\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/runit 2.1.2-60\~ -- "$@"
# End automatically added section
# Automatically added by dh_runit/2.16.4
# Unlike postrm, I can be sure, that runit-helper is present on
# prerm.
#start: remove after trixie
if  [ ! -e /usr/lib/runit-helper/runit-helper ]; then
    #should not happen
    echo "warning: can't find runit-helper, prerm action skipped!"
    echo "warning: runit-helper: please report this bug"
fi
#end: remove after trixie
if [ -z "${DPKG_ROOT:-}" ]  && [ -x /usr/lib/runit-helper/runit-helper ]; then
    NAME='default-syslog' ENABLE='yes' ONUPGRADE='nostop' /usr/lib/runit-helper/runit-helper prerm "$@"
fi
# End automatically added section
