#!/bin/sh

set -e

. /usr/share/debconf/confmodule

config="/etc/prometheus-nextcloud-exporter.yml"

update_config () {
    db_get prometheus-nextcloud-exporter/server
    server="$RET"
    db_get prometheus-nextcloud-exporter/username
    username="$RET"
    db_get prometheus-nextcloud-exporter/password
    password="$RET"

    sed -i -e "s|^\(\s*server:\s*\"\)\S\+\(\"\s*\)$|\1$server\2|" \
           -e "s|^\(\s*username:\s*\"\)\S\+\(\"\s*\)$|\1$username\2|" \
           -e "s|^\(\s*password:\s*\"\)\S\+\(\"\s*\)$|\1$password\2|" \
           "$config"
}

case "$1" in
    configure)
        # Add prometheus user
        adduser --quiet --system --home /var/lib/prometheus --no-create-home \
                --group --gecos "Prometheus daemon" prometheus

        [ -f "$config" ] && update_config
        if ! dpkg-statoverride --list /etc/prometheus-nextcloud-exporter.yml \
            >/dev/null
        then
            chown root:prometheus /etc/prometheus-nextcloud-exporter.yml
            chmod 640 /etc/prometheus-nextcloud-exporter.yml
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'prometheus-nextcloud-exporter.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'prometheus-nextcloud-exporter.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'prometheus-nextcloud-exporter.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'prometheus-nextcloud-exporter.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'prometheus-nextcloud-exporter.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
