#!/bin/sh

set -e

# remove temporary sockets
rm -rf /var/shiny-server/sockets

if [ "$1" = "purge" ] ; then
    deluser --remove-all-files --system shiny || true
    delgroup --system shiny || true
fi

# De-register with update-rc.d
update-rc.d shiny-server remove > /dev/null || exit $?

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'shiny-server.service' >/dev/null || true
	fi
fi
# End automatically added section

