#!/bin/sh
set -e

case "$1" in
    configure)
        if [ -z "$2" ]; then
            # Make sure the "docker" system group exists for "docker.socket"
	    # to apply it as the group on "docker.sock"
            if ! getent group docker >/dev/null 2>&1 ; then
                addgroup --system docker
            fi
        fi

        # Ensure config directory permissions
        #  On a fresh install, $2 = '' and dpkg "le-nl" treat that as a
        #  greater version, so the body is not executed.
        if dpkg --compare-versions "$2" le-nl '1.11.2~ds1-1'; then
            if [ "$(stat -c '%a' /etc/docker)" = '700' ]; then
                chmod 0755 /etc/docker
            fi
        fi
        ;;
    abort-*)
        # How'd we get here??
        exit 1
        ;;
    *)
        ;;
esac

# Automatically added by dh_apparmor/4.1.0-1
if [ "$1" = "configure" ]; then
    APP_PROFILE="/etc/apparmor.d/docker.io"
    if [ -f "$APP_PROFILE" ]; then
        # Add the local/ include
        LOCAL_APP_PROFILE="/etc/apparmor.d/local/docker.io"

        test -e "$LOCAL_APP_PROFILE" || {
            mkdir -p `dirname "$LOCAL_APP_PROFILE"`
            install --mode 644 /dev/null "$LOCAL_APP_PROFILE"
        }

        # Reload the profile, including any abstraction updates
        if aa-enabled --quiet 2>/dev/null; then
            apparmor_parser -r -T -W "$APP_PROFILE" || true
        fi
    fi
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper mv_conffile /etc/bash_completion.d/docker.io /etc/bash_completion.d/docker 1.2.0\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/default/docker.io /etc/default/docker 1.2.0\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/init.d/docker.io /etc/init.d/docker 1.2.0\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/init/docker.io.conf /etc/init/docker.conf 1.2.0\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/docker 1.11.2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init/docker.conf 18.06.0\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/docker" ]; then
		update-rc.d docker defaults >/dev/null
		invoke-rc.d --skip-systemd-native docker start || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'docker.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'docker.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'docker.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'docker.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'docker.socket' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'docker.socket'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'docker.socket' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'docker.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		deb-systemd-invoke start 'docker.service' 'docker.socket' >/dev/null || true
	fi
fi
# End automatically added section

