#!/bin/sh
set -e

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/docker" ] ; then
	chmod -x "/etc/init.d/docker" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d docker remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper mv_conffile /etc/bash_completion.d/docker.io /etc/bash_completion.d/docker 1.2.0\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/default/docker.io /etc/default/docker 1.2.0\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/init.d/docker.io /etc/init.d/docker 1.2.0\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/init/docker.io.conf /etc/init/docker.conf 1.2.0\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/docker 1.11.2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init/docker.conf 18.06.0\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'docker.service' 'docker.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/4.1.0-1
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/docker.io" ] ; then
    rm -f "/etc/apparmor.d/disable/docker.io" || true
    rm -f "/etc/apparmor.d/force-complain/docker.io" || true
    rm -f "/etc/apparmor.d/local/docker.io" || true
    rm -f /var/cache/apparmor/*/"docker.io" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section


case "$1" in
	purge)
		# if we have our saved "nuke-graph-directory.sh", let's use it
		# see also docker.io.prerm
		if [ -x /var/lib/docker/nuke-graph-directory.sh ]; then
			/var/lib/docker/nuke-graph-directory.sh /var/lib/docker
		fi
		;;

	*)
		;;
esac
