#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ptunnel-ng" ] ; then
	chmod -x "/etc/init.d/ptunnel-ng" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d ptunnel-ng remove >/dev/null
fi
# End automatically added section
