#!/bin/sh

set -e

case "$1" in
	remove|deconfigure)
		update-alternatives --remove slurmd /usr/sbin/slurmd-wlm
		;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'slurmd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/slurmd" ] ; then
	invoke-rc.d --skip-systemd-native slurmd stop || exit 1
fi
# End automatically added section


exit 0
