#!/bin/sh

set -e

if [ "$1" = purge ]; then
    rm -rf  /var/lib/inetsim /var/log/inetsim
    deluser --system --quiet inetsim || true
    delgroup --only-if-empty --quiet inetsim || true
fi

# Automatically added by dh_installinit/13.3.2
if [ "$1" = "purge" ] ; then
	update-rc.d inetsim remove >/dev/null
fi
# End automatically added section

