#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
	    for i in /etc/boxbackup/bbackupd.conf /etc/boxbackup/bbackupd/notifyadmin; do
		if [ -e $i ]; then
		    rm -f $i
		fi
		if which ucf >/dev/null; then
		    ucf -p $i
		fi
	    done
fi

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/boxbackup-client" ] ; then
	chmod -x "/etc/init.d/boxbackup-client" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d boxbackup-client remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'boxbackup-client.service' 'boxbackup-client.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.15.3
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

