#!/bin/sh

set -e

CONFIG_FILE=/etc/default/pioneers-metaserver

if test "$1" = "purge" ; then
	rm -f "$CONFIG_FILE"
fi

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/pioneers-metaserver" ] ; then
	chmod -x "/etc/init.d/pioneers-metaserver" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d pioneers-metaserver remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.15.3
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
