#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
  for CONFF in /etc/auto.master /etc/auto.net /etc/auto.misc /etc/auto.smb /etc/autofs.conf /etc/default/autofs; do
    rm -f $CONFF $CONFF.ucf-dist $CONFF.ucf-old $CONFF.ucf-new
    if which ucf  >/dev/null; then ucf  --purge $CONFF; fi
    if which ucfr >/dev/null; then ucfr --purge autofs $CONFF; fi
  done
fi

# Automatically added by dh_installinit/13.23
if [ "$1" = "remove" ] && [ -x "/etc/init.d/autofs" ] ; then
	chmod -x "/etc/init.d/autofs" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d autofs remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'autofs.service' >/dev/null || true
	fi
fi
# End automatically added section

