#!/bin/sh

set -e


USERNAME=_mta-sts
VARLIB=/var/lib/mta-sts/

adduser --quiet --system --force-badname --disabled-login \
            --no-create-home --home $VARLIB \
            --shell /usr/sbin/nologin --group "$USERNAME"

mkdir --parents --mode=0755 $VARLIB
chown $USERNAME:$USERNAME $VARLIB



# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p postfix-mta-sts-resolver 
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p postfix-mta-sts-resolver  || true
fi

# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/postfix-mta-sts-resolver" ]; then
		update-rc.d postfix-mta-sts-resolver defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native postfix-mta-sts-resolver $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'postfix-mta-sts-resolver.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'postfix-mta-sts-resolver.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'postfix-mta-sts-resolver.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'postfix-mta-sts-resolver.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'postfix-mta-sts-resolver.service' >/dev/null || true
	fi
fi
# End automatically added section

