#!/bin/sh

set -e

if [ "$1" = remove ] || [ "$1" = deconfigure ]; then
	update-alternatives --remove postfwd /usr/sbin/postfwd1
	update-alternatives --remove postfwd /usr/sbin/postfwd2
fi

# Automatically added by dh_installsystemd/13.16
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'postfwd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.16
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/postfwd" ] ; then
	invoke-rc.d --skip-systemd-native postfwd stop || exit 1
fi
# End automatically added section

