#! /bin/sh
# postrm script for gross

set -e

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/gross" ] ; then
	chmod -x "/etc/init.d/gross" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d gross remove >/dev/null
fi
# End automatically added section


[ -e /usr/share/debconf/confmodule ]  && . /usr/share/debconf/confmodule

case "$1" in
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    purge)
        if [ -d /var/lib/gross ]; then
            rm -rf /var/lib/gross || true
        fi

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

exit 0
