#!/bin/sh
set -e
# Automatically added by dh_installinit/13.16
if [ "$1" = "remove" ] && [ -x "/etc/init.d/netplug" ] ; then
	chmod -x "/etc/init.d/netplug" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d netplug remove >/dev/null
fi
# End automatically added section
