#!/bin/sh

set -e

case "$1" in
    purge)
        rm -fr  \
            /etc/tarantool \
            /var/log/tarantool \
            /var/run/tarantool \
            /var/lib/tarantool
    ;;
esac

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/tarantool" ] ; then
	chmod -x "/etc/init.d/tarantool" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d tarantool remove >/dev/null
fi
# End automatically added section


