#!/bin/sh

set -e

SYSUSER=tarantool

case "$1" in
    configure)
        if ! getent passwd $SYSUSER > /dev/null; then
            adduser \
                --system \
                --group \
                --quiet \
                --home \
                /var/spool/$SYSUSER \
                --no-create-home \
                --disabled-login \
                    tarantool
        fi

        # Use setgid to allow `adm` members to read logs
        install -d -o$SYSUSER -gadm -m2750 /var/log/tarantool
        install -d -o$SYSUSER -g$SYSUSER -m750 /var/run/tarantool
        install -d -o$SYSUSER -g$SYSUSER -m750 /var/lib/tarantool
    ;;
esac

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/tarantool" ]; then
		update-rc.d tarantool defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d tarantool $_dh_action || exit 1
	fi
fi
# End automatically added section

