#!/bin/sh

set -e

if [ "${1}" = "purge" ] ; then
	[ -d /etc/heat ] && rmdir --ignore-fail-on-non-empty /etc/heat
	rm -rf /var/log/heat/heat-engine.*
	[ -d /var/log/heat ] && rmdir --ignore-fail-on-non-empty /var/log/heat
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/heat-engine" ] ; then
	chmod -x "/etc/init.d/heat-engine" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d heat-engine remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'heat-engine.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
