#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/heat-engine" ] ; then
	invoke-rc.d heat-engine stop || true
fi
# End automatically added section
