#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/npd6" ] ; then
	chmod -x "/etc/init.d/npd6" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d npd6 remove >/dev/null
fi
# End automatically added section
