#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.3
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/npd6" ] ; then
	chmod +x "/etc/init.d/npd6" >/dev/null || true
fi
# End automatically added section
