#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/npd6" ] ; then
	invoke-rc.d --skip-systemd-native npd6 stop || exit 1
fi
# End automatically added section
