#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    if [ -d /var/tmp/vi.recover ]; then
      rm -rf /var/tmp/vi.recover
    fi
fi

# Automatically added by dh_installinit/13.16
if [ "$1" = "remove" ] && [ -x "/etc/init.d/nvi" ] ; then
	chmod -x "/etc/init.d/nvi" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d nvi remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nvi.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
