#!/bin/sh

set -e

GROUP="memcache"
USER="memcache"
DATADIR="/nonexistent"

# shamelessly copied from debian gearman-job-server package...

case "$1" in
configure)
    # creating memcache group if it isn't already there
    if ! getent group $GROUP >/dev/null ; then
            # Adding system group
            addgroup --system $GROUP >/dev/null
    fi

    # creating memcache user if it isn't already there
    if ! getent passwd $USER >/dev/null ; then
            # Adding system user
            adduser \
              --system \
              --disabled-login \
              --ingroup $GROUP \
              --home $DATADIR \
              --no-create-home \
              --gecos "Memcached" \
              --shell /bin/false \
              $USER  >/dev/null
    fi
    if [ ! -e /etc/memcached.conf ]
        then
            mkdir -p /etc
            cp /usr/share/memcached/memcached.conf.default /etc/memcached.conf
    fi
    ;;
esac

# Automatically added by dh_installtmpfiles/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "$(command -v systemd-tmpfiles)" ]; then
		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create memcached.conf || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/memcached" ]; then
		update-rc.d memcached defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native memcached $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'memcached.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'memcached.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'memcached.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'memcached.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'memcached.service' >/dev/null || true
	fi
fi
# End automatically added section

