#!/bin/sh

set -e

if [ "$1" = purge ]; then
    rm -f /etc/tinc/nets.boot
fi

# Automatically added by dh_installinit/13.16
if [ "$1" = "remove" ] && [ -x "/etc/init.d/tinc" ] ; then
	chmod -x "/etc/init.d/tinc" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d tinc remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'tinc.service' >/dev/null || true
	fi
fi
# End automatically added section

