#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/modules-load.d/feedbackd.conf 0.2.0 -- "$@"
# End automatically added section
# Automatically added by dh_installsystemduser/13.24.2
if [ "$1" = "purge" ]; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'fbd-alert-slider.service' >/dev/null || true
	fi
fi
# End automatically added section
