#!/bin/sh

set -e

if [ "${1}" = "purge" ] ; then
	if [ -f /usr/share/debconf/confmodule ] && [ -f /usr/share/dbconfig-common/dpkg/postrm ] ; then
		. /usr/share/debconf/confmodule

		db_get keystone/configure_db
		if [ "$RET" = "true" ] ; then
			. /usr/share/dbconfig-common/dpkg/postrm
			dbc_go keystone $@
		fi
	fi
	rm -rf /var/log/keystone /var/lib/keystone /etc/keystone
	if [ -x `which a2dissite`"" ] ; then
		a2dissite wsgi-keystone.conf || true
	fi
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/keystone" ] ; then
	chmod -x "/etc/init.d/keystone" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d keystone remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'keystone.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_apparmor/4.1.0-1
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.bin.keystone-all" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.bin.keystone-all" || true
    rm -f "/etc/apparmor.d/force-complain/usr.bin.keystone-all" || true
    rm -f "/etc/apparmor.d/local/usr.bin.keystone-all" || true
    rm -f /var/cache/apparmor/*/"usr.bin.keystone-all" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section

