#!/bin/sh
set -e

# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p python3-pyro5 
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p python3-pyro5  || true
fi

# End automatically added section
# Automatically added by dh_installinit/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/pyro5-ns" ]; then
		update-rc.d pyro5-ns defaults-disabled >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native pyro5-ns $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'pyro5-ns.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'pyro5-ns.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'pyro5-ns.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'pyro5-ns.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'pyro5-ns.service' >/dev/null || true
fi
# End automatically added section
