#!/bin/sh
set -e
# Automatically added by dh_installinit/13.16
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/pyro5-ns" ] ; then
	chmod +x "/etc/init.d/pyro5-ns" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'pyro5-ns.service' >/dev/null || true
fi
# End automatically added section
