#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.Flatpak.SystemHelper.conf 1.1.1-1\~ flatpak -- "$@"
# End automatically added section
