#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.8
if [ "$1" = "remove" ] && [ -x "/etc/init.d/aumix" ] ; then
	chmod -x "/etc/init.d/aumix" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d aumix remove >/dev/null
fi
# End automatically added section
