#!/bin/sh

set -e

case "$1" in
    configure)
        if ! id -u dkimpy-milter >/dev/null 2>&1; then
            adduser --quiet --system --group --no-create-home --home /nonexistent dkimpy-milter
        elif [ -n "$2" ]; then
            addgroup --quiet --system dkimpy-milter
            usermod -g dkimpy-milter dkimpy-milter
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p dkimpy-milter 
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p dkimpy-milter  || true
fi

# End automatically added section
# Automatically added by dh_installdeb/13.23
dpkg-maintscript-helper mv_conffile /etc/dkimpy-milter.conf /etc/dkimpy-milter/dkimpy-milter.conf 1.1.4-1 -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.23
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/dkimpy-milter" ]; then
		update-rc.d dkimpy-milter defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native dkimpy-milter $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'dkimpy-milter.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'dkimpy-milter.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'dkimpy-milter.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'dkimpy-milter.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'dkimpy-milter.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0

