#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'dkimpy-milter.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/dkimpy-milter" ] ; then
	invoke-rc.d --skip-systemd-native dkimpy-milter stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.23
dpkg-maintscript-helper mv_conffile /etc/dkimpy-milter.conf /etc/dkimpy-milter/dkimpy-milter.conf 1.1.4-1 -- "$@"
# End automatically added section

# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1; then
	py3clean -p dkimpy-milter 
else
	dpkg -L dkimpy-milter | sed -En -e '/^(.*)\/(.+)\.py$/s,,rm "\1/__pycache__/\2".*,e'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section
