#!/bin/sh
set -e
# Automatically added by dh_installinit/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/ekeyd-egd-linux" ] ; then
	invoke-rc.d --skip-systemd-native ekeyd-egd-linux stop || exit 1
fi
# End automatically added section
