#!/bin/sh
set -e
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/das-watchdog" ] ; then
	chmod -x "/etc/init.d/das-watchdog" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d das-watchdog remove >/dev/null
fi
# End automatically added section
