#!/bin/sh
set -e
# Automatically added by dh_systemd_start/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'oci-first-boot.service' 'oci-report-status.service' >/dev/null || true
fi
# End automatically added section
