#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/default/ipmidetectd 1.6.4-4\~ freeipmi-ipmidetect -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/ipmidetectd 1.6.4-3.1\~ -- "$@"
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/freeipmi-ipmidetect /usr/share/doc/freeipmi-common 1.6.6-4\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ipmidetectd.service' >/dev/null || true
	fi
fi
# End automatically added section
