#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/init.d/hitch 1.8.0-1\~ hitch -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'hitch.service' >/dev/null || true
	fi
fi
# End automatically added section
