#!/bin/sh

set -e

if [ "$1" = "remove" ]; then
	rm -f /etc/graphite/*.pyc
	rm -f /var/lib/graphite/search_index
	rm -rf /var/lib/graphite/.fontconfig
fi

# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'graphite_build_search_index.service' 'graphite_build_search_index.timer' >/dev/null || true
fi
# End automatically added section

# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1; then
	py3clean -p graphite-web 
else
	dpkg -L graphite-web | sed -En -e '/^(.*)\/(.+)\.py$/s,,rm "\1/__pycache__/\2".*,e'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section


exit 0

