#!/bin/sh

set -e

. /usr/share/debconf/confmodule
db_version 2.0

case "$1" in
	configure)
		db_get "apcupsd/warning" || true
		[ "$RET" = "false" ] && exit 0
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

db_stop

# Automatically added by dh_installinit/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/apcupsd" ]; then
		update-rc.d apcupsd defaults >/dev/null
		invoke-rc.d apcupsd start || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'apcupsd.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'apcupsd.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'apcupsd.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'apcupsd.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
