#!/bin/sh

set -e

case "$1" in
	remove|upgrade|deconfigure)
		[ -x /etc/init.d/apcupsd ] && ( /etc/init.d/apcupsd stop || killall apcupsd || echo "" >> /dev/null )

		if [ -f /etc/cron.daily/apcupsd ]
		then
			rm -f /etc/cron.daily/apcupsd
		fi
		;;

	failed-upgrade)

		;;

	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installinit/13.16
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/apcupsd" ] ; then
	invoke-rc.d apcupsd stop || exit 1
fi
# End automatically added section


exit 0
