#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'zfs-import-cache.service' 'zfs-import-scan.service' 'zfs-import.target' 'zfs-load-module.service' 'zfs-mount.service' 'zfs-share.service' 'zfs-volume-wait.service' 'zfs-volumes.target' 'zfs.target' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/zfs-share" ] ; then
	invoke-rc.d --skip-systemd-native zfs-share stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/zfs-load-key" ] ; then
	invoke-rc.d --skip-systemd-native zfs-load-key stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/zfs-mount" ] ; then
	invoke-rc.d --skip-systemd-native zfs-mount stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/zfs-import" ] ; then
	invoke-rc.d --skip-systemd-native zfs-import stop || exit 1
fi
# End automatically added section
