#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/unbound/unbound.conf.d/qname-minimisation.conf 1.9.6-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/unbound" ] ; then
	chmod +x "/etc/init.d/unbound" >/dev/null || true
fi
# End automatically added section
