#!/bin/sh

set -e

BIPUSER=bip
BIPGROUP=bip

if [ "$1" = "purge" ] ; then
	deluser --quiet --system "$BIPUSER" > /dev/null || true
	delgroup --quiet --system "$BIPGROUP" > /dev/null || true
	rm -rf /var/log/bip /var/lib/bip /run/bip
fi

# Automatically added by dh_installinit/13.16
if [ "$1" = "remove" ] && [ -x "/etc/init.d/bip" ] ; then
	chmod -x "/etc/init.d/bip" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d bip remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'bip.service' >/dev/null || true
	fi
fi
# End automatically added section

