#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.15.3
dpkg-maintscript-helper rm_conffile /etc/dnsmasq.d/dbab.adblock.conf 1.5.7-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dnsmasq.d/dbab.trashsites.conf 1.5.7-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dbab/dbab.proxy 1.5.7-2\~ -- "$@"
# End automatically added section
