#!/bin/sh
# postinst script for minidlna

set -e

USER=minidlna
HOME_DIR=/var/lib/minidlna
CACHE_DIR=/var/cache/minidlna

setup_user() {

	if ! getent passwd "${USER}" >/dev/null; then
		adduser --quiet\
			--system \
			--group \
			--gecos "MiniDLNA server" \
			--home "${HOME_DIR}" \
			--no-create-home \
			${USER}
	fi
}

setup_cache() {
	if [ ! -d "${CACHE_DIR}" ];then
		mkdir -p "${CACHE_DIR}"
		chown ${USER}:${USER} "${CACHE_DIR}"
		chmod 750 "${CACHE_DIR}"
	fi
}

fix_statoverride() {
	# Previous versions create some dumb overrides and do not clean them on
	# removal, so we should remove them here.
        for file in /var/lib/minidlna /var/cache/minidlna /etc/minidlna.conf;do
		if dpkg-statoverride --list "${file}" >/dev/null; then
			dpkg-statoverride --remove "${file}"
		fi
	done
}

fix_permissions() {
	# Previous versions use some strange and even not secure permissions,
	# so we should fix them here.
	chown root:root /etc/minidlna.conf
	if [ -d "${CACHE_DIR}" ];then
		chown ${USER}:${USER} "${CACHE_DIR}"
		chmod 750 "${CACHE_DIR}"
	fi
}

ACTION="$1"
OLD_VERSION="$2"

if [ "$ACTION" = configure ];then
	setup_user

	if dpkg --compare-versions "$OLD_VERSION" lt-nl 1.1.5; then
		fix_statoverride
		fix_permissions
	fi

	setup_cache
fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/minidlna" ]; then
		update-rc.d minidlna defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native minidlna $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'minidlna.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'minidlna.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'minidlna.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'minidlna.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'minidlna.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
