#!/bin/sh
set -e
# Automatically added by dh_installinit/13.22
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/bcron-update" ] ; then
	chmod +x "/etc/init.d/bcron-update" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.22
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/bcron-sched" ] ; then
	chmod +x "/etc/init.d/bcron-sched" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.22
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/bcron-spool" ] ; then
	chmod +x "/etc/init.d/bcron-spool" >/dev/null || true
fi
# End automatically added section
