#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/gnocchi-api" ] ; then
	chmod -x "/etc/init.d/gnocchi-api" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d gnocchi-api remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'gnocchi-api.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
