#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/gnocchi-api" ] ; then
	invoke-rc.d gnocchi-api stop || true
fi
# End automatically added section
