#!/bin/sh
# post removal script for the Debian GNU/Linux oidentd package

set -e

if which update-inetd > /dev/null; then
	if which identd > /dev/null; then
		update-inetd --add "ident		stream	tcp	nowait	nobody	/usr/sbin/identd identd -i"
	fi
fi

if [ "$1" = purge ]; then
	if which deluser > /dev/null; then
		deluser --system --quiet oident
	fi
fi

# Automatically added by dh_installinit/13.16
if [ "$1" = "remove" ] && [ -x "/etc/init.d/oidentd" ] ; then
	chmod -x "/etc/init.d/oidentd" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d oidentd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'oidentd.service' 'oidentd.socket' >/dev/null || true
	fi
fi
# End automatically added section

