#!/bin/sh

set -e

if [ "$BANDWIDTHD_PACKAGE_DEBUG" != "" ]; then
	echo "bandwidthd-pgsql.prerm: $*"
fi

# Hook up the dbconfig-common library.
. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/prerm
dbc_go bandwidthd-pgsql $@


# From http://wiki.debian.org/Apache/PackagingFor24 :
# "Likewise, in postrm do upon purge and simple removals"
if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
	. /usr/share/apache2/apache2-maintscript-helper
	apache2_invoke disconf bandwidthd.conf
fi

# reload apache2 config for uninstalled /bandwidthd alias.
if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
	. /usr/share/apache2/apache2-maintscript-helper
	apache2_reload
fi

# Automatically added by dh_installsystemd/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'bandwidthd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/bandwidthd" ] ; then
	invoke-rc.d --skip-systemd-native bandwidthd stop || exit 1
fi
# End automatically added section


