#!/bin/sh

set -e

case "$1" in
	purge)
		rm -f /etc/v2ray/config.json
		if test ! -e /etc/v2ray ; then
			# If the config directory does not exist, do nothing
			:
		else
			if test -d /etc/v2ray ; then
				# If it is an empty directory, remove it
				rmdir /etc/v2ray || true
			fi
		fi
		;;
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		exit 0
		;;
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 0
		;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/v2ray" ] ; then
	chmod -x "/etc/init.d/v2ray" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d v2ray remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'v2ray.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
