#!/bin/sh

set -e

dpkg-maintscript-helper mv_conffile \
	/etc/apache2/conf.d/bandwidthd /etc/apache2/conf-available/bandwidthd.conf 2.0.1+cvs20090917-6~ bandwidthd -- "$@"

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/bandwidthd" ] ; then
	chmod +x "/etc/init.d/bandwidthd" >/dev/null || true
fi
# End automatically added section

