#!/bin/sh

set -e

if [ "$1" = purge ]; then
	deluser --quiet --system rtpengine > /dev/null || true
	delgroup --quiet --system rtpengine > /dev/null || true

	if [ -f /etc/modprobe.d/rtpengine.conf ] && grep -q DPKG-GENERATED /etc/modprobe.d/rtpengine.conf; then
		rm -f /etc/modprobe.d/rtpengine.conf
	fi
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/rtpengine-daemon" ] ; then
	chmod -x "/etc/init.d/rtpengine-daemon" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d rtpengine-daemon remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'rtpengine-daemon.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0

