#!/bin/sh
set -e
# Automatically added by dh_installinit/13.7.1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/squidtaild" ] ; then
	invoke-rc.d squidtaild stop || exit 1
fi
# End automatically added section
