#!/bin/sh -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper mv_conffile /var/lib/pcp/config/pmcd/pmcd.conf /etc/pcp/pmcd/pmcd.conf 3.7.0\~ pcp -- "$@"
dpkg-maintscript-helper mv_conffile /etc/pmcd/pmcd.conf /etc/pcp/pmcd/pmcd.conf 3.6.1\~ pcp -- "$@"
dpkg-maintscript-helper mv_conffile /var/lib/pcp/config/pmcd/pmcd.options /etc/pcp/pmcd/pmcd.options 3.7.0\~ pcp -- "$@"
dpkg-maintscript-helper mv_conffile /etc/pmcd/pmcd.options /etc/pcp/pmcd/pmcd.options 3.6.1\~ pcp -- "$@"
dpkg-maintscript-helper mv_conffile /var/lib/pcp/config/pmcd/rc.local /etc/pcp/pmcd/rc.local 3.7.0\~ pcp -- "$@"
dpkg-maintscript-helper mv_conffile /etc/pmcd/rc.local /etc/pcp/pmcd/FILE 3.6.1\~ pcp -- "$@"
dpkg-maintscript-helper mv_conffile /var/lib/pcp/config/pmie/control /etc/pcp/pmie/control 3.7.0\~ pcp -- "$@"
dpkg-maintscript-helper mv_conffile /etc/pmie/control /etc/pcp/pmie/control 3.6.1\~ pcp -- "$@"
dpkg-maintscript-helper mv_conffile /var/lib/pcp/config/pmproxy/pmproxy.options /etc/pcp/pmproxy/pmproxy.options 3.7.0\~ pcp -- "$@"
dpkg-maintscript-helper mv_conffile /etc/pmproxy/pmproxy.options /etc/pcp/pmproxy/pmproxy.options 3.6.1\~ pcp -- "$@"
dpkg-maintscript-helper mv_conffile /var/lib/pcp/config/pmlogger/control /etc/pcp/pmlogger/control 3.7.0\~ pcp -- "$@"
dpkg-maintscript-helper mv_conffile /etc/pmlogger/control /etc/pcp/pmlogger/control 3.6.1\~ pcp -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/pcp -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.d/pcp-pmie -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.d/pcp-pmlogger -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.d/pcp-pmlogger-daily-report -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp.sh -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/columns/container -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/columns/delayacct -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/columns/fdcount -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/columns/guest -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/columns/memory -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/columns/sched -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/columns/swap -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/columns/tcp -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/columns/udp -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/columns/wchan -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/meters/entropy -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/meters/freespace -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/meters/ipc -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/meters/locks -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/meters/memcache -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/meters/mysql -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/meters/postfix -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/meters/redis -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/htop/meters/tcp -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/openmetrics/config.d/collectd.url -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/openmetrics/config.d/etcd.url -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/openmetrics/config.d/grafana.url -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/kernel/interrupts-irix -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/kernel/memory-irix -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/kernel/queues-irix -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/kernel/syscalls-irix -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/kernel/syscalls-percpu-irix -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/memory/tlb-irix -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/networking/socket-irix -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/networking/tcp-activity-irix -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/networking/udp-packets-irix -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/sgi/cpu-evctr -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/sgi/craylink -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/sgi/efs -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/sgi/hub -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/sgi/kaio -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/sgi/node-memory -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/sgi/numa -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/sgi/numa-summary -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/sgi/xbow -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/sgi/xlv-activity -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/sgi/xlv-stripe-io -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/sgi/xvm-all -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/sgi/xvm-ops -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/sgi/xvm-stats -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/v1.0/C2 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/v1.0/C3 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/v1.0/D3 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/v1.0/K0 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/v1.0/S0 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmlogconf/v1.0/S1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmproxy/pmproxy.defaults -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmrep/iostat_v12_3.conf -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmrep/pmrep.conf -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pcp/pmrep/sar-old-kernel.conf -- "$@"
# End automatically added section

#
# The goal here is to live-migrate PCP temporary files from places
# they may have been stashed away in previous versions.  This is
# important as they may be in-use by instrumented applications and
# we want to avoid loss of service as a result of the switch.
#

# The new place ... this should match the setting in /etc/pcp.conf
# _after_ the installation
#
PCP_TMP_DIR=/var/lib/pcp/tmp


getent group pcp >/dev/null || groupadd -r pcp
getent passwd pcp >/dev/null || \
useradd -c "Performance Co-Pilot" -g pcp -d /var/lib/pcp -M -r -s /usr/sbin/nologin pcp

# must match pmns/GNUmakefile, owned by root:root so $PCP_SYSCONF_DIR/pmcd/rc
# can remove it once PMNS rebuild is done on first pmcd startup
#
touch /var/lib/pcp/pmns/.NeedRebuild
chmod 644 /var/lib/pcp/pmns/.NeedRebuild

# owned by pcp:pcp so pmlogger_daily can remove it once rewriting
# is done
#
touch /var/log/pcp/pmlogger/.NeedRewrite
chown pcp:pcp /var/log/pcp/pmlogger/.NeedRewrite
chmod 644 /var/log/pcp/pmlogger/.NeedRewrite

# must match GNUmakefile
#
chown pcp:pcp /var/lib/pcp/config/pmda
chmod 775 /var/lib/pcp/config/pmda
chown pcp:pcp /var/lib/pcp/tmp
chmod 775 /var/lib/pcp/tmp
chown pcp:pcp /var/log/pcp
chmod 775 /var/log/pcp
# we used to dink with /var/run/pcp here, but that is done more
# safely in pcp-reboot-init now

# must match src/pmdas/{json,bash,mmv}/GNUmakefile
#
for PMDA in bash json mmv; do
    # directory may be in optionally build component, so test first
    #
    if [ -d /var/lib/pcp/tmp/$PMDA ]
    then
	chown pcp:pcp /var/lib/pcp/tmp/$PMDA
	chmod 775 /var/lib/pcp/tmp/$PMDA
    fi
done

# must match src/pmdas/mmv/src/GNUmakefile
# (strange but true, the "pmproxy" pmda is built in the mmv dir)
#
chown pcp:pcp /var/lib/pcp/tmp/pmproxy
chmod 775 /var/lib/pcp/tmp/pmproxy

# must match src/pmie/GNUmakefile
#
chown pcp:pcp /var/lib/pcp/config/pmie
chmod 775 /var/lib/pcp/config/pmie
chown pcp:pcp /var/lib/pcp/tmp/pmie
chmod 775 /var/lib/pcp/tmp/pmie
chown pcp:pcp /var/log/pcp/pmie
chmod 775 /var/log/pcp/pmie

# must match src/pmlogger/GNUmakefile
#
chown pcp:pcp /var/lib/pcp/config/pmlogger
chmod 775 /var/lib/pcp/config/pmlogger
chown pcp:pcp /var/lib/pcp/tmp/pmlogger
chmod 775 /var/lib/pcp/tmp/pmlogger
chown pcp:pcp /var/log/pcp/pmlogger
chmod 775 /var/log/pcp/pmlogger
chown pcp:pcp /var/log/pcp/sa
chmod 775 /var/log/pcp/sa

# must match src/pmproxy/GNUmakefile
#
chown pcp:pcp /var/log/pcp/pmproxy
chmod 775 /var/log/pcp/pmproxy

# must match src/pmfind/GNUmakefile
#
chown pcp:pcp /var/log/pcp/pmfind
chmod 775 /var/log/pcp/pmfind

# and fixup the change in deployment plan for these ones in the case
# of an upgrade, rather than an install ... they used to be pcp:pcp
chown root:root /etc/pcp/pmie
chmod 755 /etc/pcp/pmie
chown root:root /etc/pcp/pmie/control
chmod 644 /etc/pcp/pmie/control
chown root:root /etc/pcp/pmlogger
chmod 755 /etc/pcp/pmlogger
chown root:root /etc/pcp/pmlogger/control
chmod 644 /etc/pcp/pmlogger/control

# figure out what sort if init|systemctl|... we're using to
# launch daemons and services
do_systemctl=false
do_systemd_helper=false
do_update_rc=false
do_invoke_rc=false
if which systemctl >/dev/null 2>&1
then
    # we have a systemctl executable, but it might be disabled,
    # e.g. on MX Linux
    systemctl -q is-active local-fs.target >/dev/null 2>&1 && do_systemctl=true
fi
if $do_systemctl
then
    which deb-systemd-helper >/dev/null 2>&1 && do_systemd_helper=true
else
    # not using systemctl(1), maybe need to install System-V style
    # init script links with update-rc.d(1) and start/stop with
    # invoke-rc.d(1)
    which update-rc.d >/dev/null 2>&1 && do_update_rc=true
    which invoke-rc.d >/dev/null 2>&1 && do_invoke_rc=true
fi
# only need to check pmcd.service, if it is here they will all
# be here
if [ -f /lib/systemd/system/pmcd.service ]
then
    :
else
    do_systemd_helper=false
    do_systemctl=false
fi
# ditto for the System-V variant for pmlogger
if [ -f /etc/init.d/pmlogger ]
then
    :
else
    do_update_rc=false
    do_invoke_rc=false
fi

if $do_systemd_helper
then
    deb-systemd-helper enable pcp-reboot-init.service >/dev/null
    deb-systemd-helper enable pmcd.service >/dev/null
    deb-systemd-helper enable pmlogger.service >/dev/null
    deb-systemd-helper enable pmie.service >/dev/null
    deb-systemd-helper enable pmproxy.service >/dev/null
elif $do_update_rc
then
    update-rc.d -f pmcd remove >/dev/null
    update-rc.d pmcd defaults >/dev/null
    update-rc.d -f pmlogger remove >/dev/null
    update-rc.d pmlogger defaults >/dev/null
    update-rc.d -f pmie remove >/dev/null
    update-rc.d pmie defaults >/dev/null
    update-rc.d -f pmproxy remove >/dev/null
    update-rc.d pmproxy defaults >/dev/null
fi

if $do_systemctl
then
    systemctl daemon-reload >/dev/null
    systemctl start pcp-reboot-init.service >/dev/null
    systemctl start pmcd.service >/dev/null
    systemctl start pmlogger.service >/dev/null
elif $do_invoke_rc
then
    invoke-rc.d pmcd start
    invoke-rc.d pmlogger start
else
    /etc/init.d/pmcd start
    /etc/init.d/pmlogger start
fi

exit 0
