#!/bin/sh

set -e

if [ "${1}" = "purge" ] ; then
	rm -f /etc/neutron/plugins/ml2/ironic_neutron_agent.ini
fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ironic-neutron-agent" ] ; then
	chmod -x "/etc/init.d/ironic-neutron-agent" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d ironic-neutron-agent remove >/dev/null
fi
# End automatically added section


exit 0
