#!/bin/sh

set -e

if [ "$1" = upgrade ] && dpkg --compare-versions "$2" lt "1.8.0~"; then
    update-alternatives --remove klog /usr/bin/klog.afs
fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/openafs-client" ] ; then
	chmod +x "/etc/init.d/openafs-client" >/dev/null || true
fi
# End automatically added section


exit 0
