#!/bin/sh

set -e

if [ "$1" = remove ] || [ "$1" = deconfigure ] ; then
    update-alternatives --remove pagsh /usr/bin/pagsh.openafs
fi

# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'openafs-client.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/openafs-client" ] ; then
	invoke-rc.d --skip-systemd-native openafs-client stop || exit 1
fi
# End automatically added section


exit 0
