#!/bin/sh

set -e

case "$1" in
    configure)
	chown irc:adm /var/log/hopm
	chgrp irc /etc/hopm/hopm.conf
	chmod g+r,o-rwx /etc/hopm/hopm.conf
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
	echo "ERROR: Postinst called with unknown argument!"
	exit 0
    ;;
esac

# Automatically added by dh_installinit/13.14.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/hopm" ]; then
		update-rc.d hopm defaults-disabled >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native hopm $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0
