#!/bin/sh

set -e

case "$1" in
    purge)
	rm -rf /var/log/hopm
    ;;

esac

# Automatically added by dh_installinit/13.14.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/hopm" ] ; then
	chmod -x "/etc/init.d/hopm" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d hopm remove >/dev/null
fi
# End automatically added section


exit 0
