#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
    # Lock account on purge
    if [ -f /etc/shadow ]; then
        usermod -L -e 1 Debian-quake3
    else
        usermod -L Debian-quake3
    fi
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/quake3-server" ] ; then
	chmod -x "/etc/init.d/quake3-server" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d quake3-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_cruft/0.9.68
if [ "$1" = "purge" ]
then
    # we need to glob, so no quotes
    rm -rf /var/games/quake3-server/
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'quake3-server.service' >/dev/null || true
	fi
fi
# End automatically added section


if [ "$1" = "purge" ] ; then
    rmdir --ignore-fail-on-non-empty /var/games
fi
