#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.14.1
dpkg-maintscript-helper rm_conffile /etc/init.d/partimaged 0.6.9-10\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/partimaged 0.6.9-10\~ -- "$@"
# End automatically added section
