#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.14.1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'partimaged.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.14.1
dpkg-maintscript-helper rm_conffile /etc/init.d/partimaged 0.6.9-10\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/partimaged 0.6.9-10\~ -- "$@"
# End automatically added section
