#!/bin/sh -e

if [ "$1" = "purge" ] ; then
    rm -rf /var/run/torrus /var/log/torrus /var/lib/torrus /var/cache/torrus
fi

dpkg-maintscript-helper rm_conffile /etc/logrotate.d/torrus-common 2.01-3 -- "$@"

# Automatically added by dh_installinit/13.11.4
if [ "$1" = "remove" ] && [ -x "/etc/init.d/torrus-common" ] ; then
	chmod -x "/etc/init.d/torrus-common" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d torrus-common remove >/dev/null
fi
# End automatically added section


exit 0
