#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/torrus-common" ] ; then
	invoke-rc.d torrus-common stop || exit 1
fi
# End automatically added section
