#!/bin/sh

# Nethack post-remove script for Debian
#
# Ben Gertzfield (che@debian.org) 29 July 1997
# Copyright 1997 Ben Gertzfield. This script is released under the
# GNU General Public License, version 2 or later.

# Updated 13 October 2003 to move the debhelper above the save-files
# purge (seems to be reading from stdin, seeing the "Purging" echo
# as a command)

# Updated 18 August 1998 to rm -rf the score/save directory on a purge,
# added debhelper comments

set -e

# Automatically added by dh_installinit/13.14.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/nethack-common" ] ; then
	chmod -x "/etc/init.d/nethack-common" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d nethack-common remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nethack-common.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.14.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


if [ "$1" = "purge" ]; then
    echo -n "Purging high-scores and save-files for Nethack... "
    rm -rf /var/games/nethack/
    echo "done."
fi

