#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/octavia-agent" ] ; then
	chmod +x "/etc/init.d/octavia-agent" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/octavia-agent-certs-ramfs" ] ; then
	chmod +x "/etc/init.d/octavia-agent-certs-ramfs" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/octavia-agent-netns" ] ; then
	chmod +x "/etc/init.d/octavia-agent-netns" >/dev/null || true
fi
# End automatically added section
