#!/bin/sh

set -e

if [ "$1" = "configure" ] && \
  dpkg --compare-versions "$2" ge "0.13.0-6~" && \
  dpkg --compare-versions "$2" lt "0.72.0-2~"
then
  echo "Forcibly resetting runlevels for wtmpdb-update-boot on this upgrade"
  update-rc.d -f wtmpdb-update-boot remove || true
fi

old_log="${DPKG_ROOT:-}/var/log/wtmp"
new_log="${DPKG_ROOT:-}/var/log/wtmp.db"
tmp_log="$new_log.import-tmp"

# If wtmp logs are present on first installation, import them.
if [ "$1" = "configure" ] && [ -z "$2" ] && \
  [ -s "$old_log" ] && [ ! -s "$new_log" ]
then
  # Convert all entries or none.
  printf "Converting wtmp login records into wtmpdb database ... "
  if wtmpdb import -f "$tmp_log" "$old_log"
  then
    [ ! -s "$tmp_log" ] || mv -f "$tmp_log" "$new_log"
    echo "done"
  else
    [ ! -s "$tmp_log" ] || rm -f "$tmp_log"
    echo "failed"
  fi
fi

# Automatically added by dh_installtmpfiles/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "$(command -v systemd-tmpfiles)" ]; then
		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create wtmpdb.conf || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/wtmpdb-update-boot" ]; then
		update-rc.d wtmpdb-update-boot defaults >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'wtmpdb-update-boot.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'wtmpdb-update-boot.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'wtmpdb-update-boot.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'wtmpdb-update-boot.service' >/dev/null || true
	fi
fi
# End automatically added section

