#!/bin/sh
#$Id: prerm,v 1.4 2003/09/08 18:09:03 agx Exp $

set -e

# rm symbolic link to /usr/doc/portsentry when package gets removed or
# upgraded
# keep this for one stable release to get rid of the symlink
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/portsentry ]; then
	rm -f /usr/doc/portsentry
fi

# to avoid long downtimes upon mass upgrades do not stop the daemon.
# Unfortunately maintainer scripts prior to 1.0-1.2 don't know anything
# about this. So we have to stop the daemon on downgrades.
if [ "$1" != "upgrade" ]; then
    if command -v invoke-rc.d > /dev/null; then
    	invoke-rc.d portsentry stop
    else
        /etc/init.d/portsentry stop
    fi
    deb-systemd-invoke stop "portsentry@*.service"
fi

# Automatically added by dh_installinit/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/portsentry" ] ; then
	invoke-rc.d --skip-systemd-native portsentry stop || exit 1
fi
# End automatically added section

