#!/bin/sh

set -e

case "$1" in
    purge)
        rm -f /etc/zabbix/zabbix_web_service.conf
        rm -f /var/log/zabbix/zabbix_web_service.log*
    ;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/zabbix-web-service" ] ; then
	chmod -x "/etc/init.d/zabbix-web-service" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d zabbix-web-service remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'zabbix-web-service.service' >/dev/null || true
	fi
fi
# End automatically added section

