#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'nagios-nrpe-server.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/nagios-nrpe-server" ] ; then
	invoke-rc.d --skip-systemd-native nagios-nrpe-server stop || exit 1
fi
# End automatically added section
