#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/prosody/certs/localhost.crt 0.11.3-1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/prosody/certs/localhost.key 0.11.3-1 -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/prosody" ] ; then
	chmod +x "/etc/init.d/prosody" >/dev/null || true
fi
# End automatically added section
