#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'prosody.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/prosody" ] ; then
	invoke-rc.d --skip-systemd-native prosody stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/prosody/certs/localhost.crt 0.11.3-1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/prosody/certs/localhost.key 0.11.3-1 -- "$@"
# End automatically added section
