#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/ganeti" ] ; then
	invoke-rc.d --skip-systemd-native ganeti stop || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/ganeti 2.16.0\~rc2-6\~ -- "$@"
# End automatically added section
