#!/bin/sh
set -e

if test "$1" = "purge"; then

    # Check if there is no collision of ownership of /etc/bird/bird.conf
    if ! command -v ucf ucfr >/dev/null || ucfr bird3 /etc/bird/bird.conf 2>/dev/null; then
	dpkg-statoverride --remove /etc/bird >/dev/null 2>/dev/null || true
	dpkg-statoverride --remove /etc/bird/bird.conf >/dev/null 2>/dev/null || true

	for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist;  do
	    rm -f /etc/bird/bird.conf$ext
	done
	rm -f /etc/bird/bird.conf
	if command -v ucf ucfr >/dev/null; then
	    ucf --purge /etc/bird/bird.conf
	    ucfr --purge bird3 /etc/bird/bird.conf
	fi

	deluser --quiet bird > /dev/null || true
    fi
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/bird" ] ; then
	chmod -x "/etc/init.d/bird" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d bird remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'bird.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
