#!/bin/sh
set -e
# Automatically added by dh_installinit/13.16
if [ "$1" = "remove" ] && [ -x "/etc/init.d/thinkfan" ] ; then
	chmod -x "/etc/init.d/thinkfan" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d thinkfan remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.16
dpkg-maintscript-helper rm_conffile /etc/thinkfan.conf 1.2.1-1\~ thinkfan -- "$@"
dpkg-maintscript-helper rm_conffile /etc/systemd/system/thinkfan.service.d/override.conf 1.2.1-2\~ thinkfan -- "$@"
dpkg-maintscript-helper rm_conffile /etc/thinkfan.yaml 1.2.1-3.1\~ thinkfan -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'thinkfan-sleep.service' 'thinkfan-wakeup.service' 'thinkfan.service' >/dev/null || true
	fi
fi
# End automatically added section
