#!/bin/sh

set -e

umask 0022
ACTION="$1"
VERSION="$2"

if [ "$ACTION" = "configure" ]; then
    # add the mpd user
    if ! getent passwd mpd >/dev/null; then
        adduser --quiet --ingroup audio --system --no-create-home \
            --home /var/lib/mpd mpd
    fi

    # set ownership and permissions on directories
    for i in /var/log/mpd /var/lib/mpd /var/lib/mpd/playlists; do
        if ! dpkg-statoverride --list --quiet "$i" >/dev/null; then
            dpkg-statoverride --force-all --quiet --update \
                --add mpd audio 0755 "$i"
        fi
    done

    # set ownership and permissions on mpd.conf
    if ! dpkg-statoverride --list --quiet /etc/mpd.conf >/dev/null; then
        dpkg-statoverride --force-all --quiet --update \
            --add mpd audio 0640 /etc/mpd.conf
    fi
fi

# Automatically added by dh_installtmpfiles/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "$(command -v systemd-tmpfiles)" ]; then
		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create mpd.conf || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemduser/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ]; then
		if deb-systemd-helper --user debian-installed 'mpd.service' ; then
			# The following line should be removed in trixie or trixie+1
			deb-systemd-helper --user unmask 'mpd.service' >/dev/null || true

			if deb-systemd-helper --quiet --user was-enabled 'mpd.service' ; then
				# Create new symlinks, if any.
				deb-systemd-helper --user enable 'mpd.service' >/dev/null || true
			fi
		fi

		# Update the statefile to add new symlinks (if any), which need to be cleaned
		# up on purge. Also remove old symlinks.
		deb-systemd-helper --user update-state 'mpd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemduser/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ]; then
		if deb-systemd-helper --user debian-installed 'mpd.socket' ; then
			# The following line should be removed in trixie or trixie+1
			deb-systemd-helper --user unmask 'mpd.socket' >/dev/null || true

			if deb-systemd-helper --quiet --user was-enabled 'mpd.socket' ; then
				# Create new symlinks, if any.
				deb-systemd-helper --user enable 'mpd.socket' >/dev/null || true
			fi
		fi

		# Update the statefile to add new symlinks (if any), which need to be cleaned
		# up on purge. Also remove old symlinks.
		deb-systemd-helper --user update-state 'mpd.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/mpd" ]; then
		update-rc.d mpd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native mpd $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'mpd.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'mpd.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'mpd.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'mpd.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'mpd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'mpd.socket'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'mpd.socket' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'mpd.socket'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'mpd.socket' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'mpd.socket' >/dev/null || true
fi
# End automatically added section

