#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
	# clean up all statoverrides that belonged to mpd, so the
	# mpd system user can be removed cleanly
	for i in $(dpkg-statoverride --list | awk '/^mpd / {print $4}'); do
		if dpkg-statoverride --list --quiet "$i" >/dev/null; then
			dpkg-statoverride --force-all --quiet --remove "$i"
		fi
	done

        deluser --quiet --system mpd > /dev/null || true

	rm -rf /var/log/mpd /run/mpd /var/lib/mpd/state \
            /var/lib/mpd/.config \
            /var/lib/mpd/sticker.sql /var/lib/mpd/tag_cache > /dev/null 2>&1
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/mpd" ] ; then
	chmod -x "/etc/init.d/mpd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d mpd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemduser/13.24.2
if [ "$1" = "purge" ]; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'mpd.service' 'mpd.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'mpd.service' 'mpd.socket' >/dev/null || true
	fi
fi
# End automatically added section

