#!/bin/sh
set -eu

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/rspamd" ] ; then
	chmod -x "/etc/init.d/rspamd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d rspamd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/rspamd/logging.conf 0.6.11\~ rspamd -- "$@"
dpkg-maintscript-helper rm_conffile /etc/rspamd/options.conf 0.6.11\~ rspamd -- "$@"
dpkg-maintscript-helper rm_conffile /etc/rspamd/workers.conf 0.6.11\~ rspamd -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'rspamd.service' >/dev/null || true
	fi
fi
# End automatically added section


case "$1" in
    purge)
      rm -rf /var/lib/rspamd
      rm -rf /var/log/rspamd
      rm -rf /run/rspamd
    ;;

    remove|upgrade|disappear|failed-upgrade|abort-*)
    ;;

    *)
      echo "postrm called with unknown argument \`$1'" >&2
      exit 1
    ;;
esac
