#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
    rm -f /var/log/nova/nova-compute.log*
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/nova-compute" ] ; then
	chmod -x "/etc/init.d/nova-compute" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d nova-compute remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nova-compute.service' >/dev/null || true
	fi
fi
# End automatically added section

