#!/bin/sh
set -e
# Automatically added by dh_installinit/13.20
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/tntnet" ] ; then
	chmod +x "/etc/init.d/tntnet" >/dev/null || true
fi
# End automatically added section
