#! /bin/sh
set -e

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'phosh.service' >/dev/null || true
	fi
fi
# End automatically added section


case "$1" in
    (remove|purge)
        if [ -d /usr/lib/x86_64-linux-gnu/phosh/plugins ]; then
            rm -f /usr/lib/x86_64-linux-gnu/phosh/plugins/giomodule.cache
            rm -f /usr/lib/x86_64-linux-gnu/phosh/plugins/prefs/giomodule.cache
        fi
        ;;
esac
