#! /bin/sh

set -e

case "${1:-}" in
  configure|reconfigure)

    if [ ! -e /etc/brlapi.key ]; then
        mcookie >/etc/brlapi.key
        chmod 0640 /etc/brlapi.key
    fi

    [ -r /etc/default/brltty ] && . /etc/default/brltty

    ! [ "$START_IN_INITRAMFS" = "true" -o "$START_IN_INITRAMFS" = "yes" ] || \
	! command -v update-initramfs >/dev/null 2>&1 || update-initramfs -u

    #update-rc.d brltty start 10 23 . > /dev/null

    ;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/brltty" ]; then
		update-rc.d brltty start 25 S . >/dev/null
		invoke-rc.d --skip-systemd-native brltty start || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'brltty.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'brltty.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'brltty.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'brltty.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'brltty.service' >/dev/null || true
	fi
fi
# End automatically added section


