#!/bin/sh

set -e

if test "$1" = "purge"
then
	rm -f /etc/brlapi.key
fi

#update-rc.d brltty remove > /dev/null

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/brltty" ] ; then
	chmod -x "/etc/init.d/brltty" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d brltty remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'brltty.service' >/dev/null || true
	fi
fi
# End automatically added section

