#!/bin/sh

set -e

case "$1" in
    purge)
        rm -fr /var/log/zabbix-proxy
        rm -fr /run/zabbix
    ;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/zabbix-proxy" ] ; then
	chmod -x "/etc/init.d/zabbix-proxy" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d zabbix-proxy remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/default/zabbix-proxy 1:2.2.7\+dfsg-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_ucf/13.24.2
if [ "$1" = "purge" ]; then
	for ext in .ucf-new .ucf-old .ucf-dist ""; do
		rm -f "/etc/zabbix/zabbix_proxy.conf$ext"
	done
	
	if [ -x "`command -v ucf`" ]; then
		ucf --purge "/etc/zabbix/zabbix_proxy.conf"
	fi
	if [ -x "`command -v ucfr`" ]; then
		ucfr --purge zabbix-proxy-pgsql "/etc/zabbix/zabbix_proxy.conf"
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'zabbix-proxy.service' >/dev/null || true
	fi
fi
# End automatically added section

