#!/bin/sh

set -e

dpkg-maintscript-helper mv_conffile /etc/init.d/dnssec-trigger /etc/init.d/dnssec-triggerd 0.12-1~ dnssec-trigger -- "$@"
dpkg-maintscript-helper mv_conffile /etc/dnssec.conf /etc/dnssec-trigger/dnssec.conf 0.12-3~ dnssec-trigger -- "$@"

# Automatically added by dh_installinit/13.16
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/dnssec-triggerd" ] ; then
	chmod +x "/etc/init.d/dnssec-triggerd" >/dev/null || true
fi
# End automatically added section


exit 0
