#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'vdr.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/vdr" ] ; then
	invoke-rc.d --skip-systemd-native vdr stop || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/vdr/plugins/order.conf 2.2.0-1 -- "$@"
# End automatically added section
