#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/jupyterhub/config/jupyterhub_config.d/50-use-configurable-http-proxy.py 5.2.1\+ds1-4\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/jupyterhub/config/jupyterhub_config.d/config.yaml 5.2.1\+ds1-4\~ -- "$@"
# End automatically added section
# Automatically added by dh_ucf/13.24.2
if [ "$1" = "purge" ]; then
	for ext in .ucf-new .ucf-old .ucf-dist ""; do
		rm -f "/etc/jupyterhub/jupyterhub_config.py$ext"
	done
	
	if [ -x "`command -v ucf`" ]; then
		ucf --purge "/etc/jupyterhub/jupyterhub_config.py"
	fi
	if [ -x "`command -v ucfr`" ]; then
		ucfr --purge jupyterhub "/etc/jupyterhub/jupyterhub_config.py"
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'jupyterhub.service' >/dev/null || true
	fi
fi
# End automatically added section
