#!/bin/sh
set -e


# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p jupyterhub 
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p jupyterhub  || true
fi

if command -v py3compile >/dev/null 2>&1; then
	py3compile -p jupyterhub /usr/share/jupyterhub
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p jupyterhub /usr/share/jupyterhub || true
fi

# End automatically added section
# Automatically added by dh_ucf/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	ucf "/usr/share/jupyterhub/jupyterhub_config.py" "/etc/jupyterhub/jupyterhub_config.py"
	ucfr jupyterhub "/etc/jupyterhub/jupyterhub_config.py"
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/jupyterhub/config/jupyterhub_config.d/50-use-configurable-http-proxy.py 5.2.1\+ds1-4\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/jupyterhub/config/jupyterhub_config.d/config.yaml 5.2.1\+ds1-4\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'jupyterhub.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'jupyterhub.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'jupyterhub.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'jupyterhub.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'jupyterhub.service' >/dev/null || true
	fi
fi
# End automatically added section


if [ "${1}" = "configure" ] && [ ! -z "${2}" ]; then
    if dpkg --compare-versions ${2} le "5.2.1+ds1-4~"; then
        if [ -d /etc/jupyterhub/config/jupyterhub_config.d ]; then
	    rmdir --ignore-fail-on-non-empty -p /etc/jupyterhub/config/jupyterhub_config.d
        fi

        if [ -d /etc/jupyterhub/config ]; then
	    rmdir --ignore-fail-on-non-empty -p /etc/jupyterhub/config
        fi
    fi
fi
