#!/bin/bash

set -e

. /usr/share/debconf/confmodule

if [ "$1" == "configure" ]
then
	db_purge
fi

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'liblemonldap-ng-portal-perl.service' 'liblemonldap-ng-portal-perl.timer' >/dev/null || true
	fi
fi
# End automatically added section

exit 0
