#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/heimdal-kcm" ] ; then
	chmod -x "/etc/init.d/heimdal-kcm" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d heimdal-kcm remove >/dev/null
fi
# End automatically added section
