#!/bin/sh
set -e
# Automatically added by dh_installinit/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/dibbler-relay" ] ; then
	invoke-rc.d dibbler-relay stop || exit 1
fi
# End automatically added section
