#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.23
dpkg-maintscript-helper rm_conffile /etc/sysconfig/monitorix 3.13.1-1\~ monitorix -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.23
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/monitorix" ] ; then
	chmod +x "/etc/init.d/monitorix" >/dev/null || true
fi
# End automatically added section
