#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/nova-api" ] ; then
	chmod +x "/etc/init.d/nova-api" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/nova-api-metadata" ] ; then
	chmod +x "/etc/init.d/nova-api-metadata" >/dev/null || true
fi
# End automatically added section
