#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/default/zabbix-server 1:2.2.7\+dfsg-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/zabbix-server" ] ; then
	chmod +x "/etc/init.d/zabbix-server" >/dev/null || true
fi
# End automatically added section
