#!/bin/sh

set -e

dpkg-maintscript-helper dir_to_symlink /usr/share/olad/www/new/libs/jquery/js /usr/share/javascript/jquery 0.10.9.nojsmin-1 ola -- "$@"
dpkg-maintscript-helper dir_to_symlink /usr/share/olad/www/new/libs/angular/js /usr/share/javascript/angular.js 0.10.9.nojsmin-1 ola -- "$@"
dpkg-maintscript-helper dir_to_symlink /usr/share/olad/www/new/libs/bootstrap /usr/share/javascript/bootstrap 0.10.9.nojsmin-1 ola -- "$@"

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/olad" ] ; then
	chmod +x "/etc/init.d/olad" >/dev/null || true
fi
# End automatically added section

