#!/bin/sh

set -e

# source debconf library
. /usr/share/debconf/confmodule

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	# only remove aptly-api user and its homedir on purge
	if [ "${1}" = "purge" ] ; then
	    userdel -r aptly-api
	fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper mv_conffile /etc/aptly-api.conf /etc/aptly.conf 1.6\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'aptly-api.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
