#!/bin/sh

set -e

# source debconf library
. /usr/share/debconf/confmodule

case "$1" in
    configure|reconfigure)
        # create an aptly-api group and user
        if ! getent passwd aptly-api > /dev/null; then
	    useradd --system --user-group --create-home --home-dir /var/lib/aptly-api aptly-api
        fi

        # set config file permissions not world readable as it may contain secrets
        chown root:aptly-api /etc/aptly.conf
        chmod 640 /etc/aptly.conf
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper mv_conffile /etc/aptly-api.conf /etc/aptly.conf 1.6\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'aptly-api.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'aptly-api.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'aptly-api.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'aptly-api.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'aptly-api.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
