#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/cloudkitty-processor" ] ; then
	invoke-rc.d cloudkitty-processor stop || true
fi
# End automatically added section
