#!/bin/sh
set -e
# Automatically added by dh_installinit/13.16
if [ "$1" = "remove" ] && [ -x "/etc/init.d/fetch-crl-cron" ] ; then
	chmod -x "/etc/init.d/fetch-crl-cron" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d fetch-crl-cron remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.16
if [ "$1" = "remove" ] && [ -x "/etc/init.d/fetch-crl-boot" ] ; then
	chmod -x "/etc/init.d/fetch-crl-boot" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d fetch-crl-boot remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'fetch-crl.timer' >/dev/null || true
	fi
fi
# End automatically added section
