#!/bin/sh
set -e
# Automatically added by dh_installinit/13.16
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/fetch-crl-boot" ] ; then
	chmod +x "/etc/init.d/fetch-crl-boot" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.16
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/fetch-crl-cron" ] ; then
	chmod +x "/etc/init.d/fetch-crl-cron" >/dev/null || true
fi
# End automatically added section
