#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.16
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'fetch-crl.service' 'fetch-crl.timer' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.16
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/fetch-crl-cron" ] ; then
	invoke-rc.d --skip-systemd-native fetch-crl-cron stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/13.16
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/fetch-crl-boot" ] ; then
	invoke-rc.d --skip-systemd-native fetch-crl-boot stop || exit 1
fi
# End automatically added section
