#!/bin/sh

set -e

if [ "$1" = "purge" ] && [ -d /etc/proxy-suite ]; then
  rmdir --ignore-fail-on-non-empty /etc/proxy-suite
fi

# Automatically added by dh_installinit/13.23
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ftp-proxy" ] ; then
	chmod -x "/etc/init.d/ftp-proxy" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d ftp-proxy remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ftp-proxy.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
