#!/bin/sh

set -e

movecfgfile () {
  if [ -e "/etc/$1" ] ; then
    echo -n "Moving $1"
    mv "/etc/$1" "/etc/proxy-suite/"
    echo
  fi
}

# If we are upgrading we might need to move configfiles
if [ "$1" = "upgrade" ] ;  then
  if [ ! -d /etc/proxy-suite ] ; then
    echo "Moving configuration files to /etc/proxy-suite."
    mkdir /etc/proxy-suite
    chmod 755 /etc/proxy-suite
    movecfgfile ftp-proxy.conf
  fi
fi

# Automatically added by dh_installinit/13.23
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/ftp-proxy" ] ; then
	chmod +x "/etc/init.d/ftp-proxy" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'ftp-proxy.service' >/dev/null || true
fi
# End automatically added section


exit 0
