#!/bin/sh

set -e

case "$1" in
  purge)
    rm -rf /var/lib/victoria-metrics \
           /var/log/victoria-metrics \
           /run/victoria-metrics
    # We do NOT remove the system user.
    ;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/victoria-metrics" ] ; then
	chmod -x "/etc/init.d/victoria-metrics" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d victoria-metrics remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'victoria-metrics.service' >/dev/null || true
	fi
fi
# End automatically added section

