#!/bin/sh

set -e

for FILE in /etc/issue.linuxlogo /etc/issue.linuxlogo.ascii
do
	if [ ! -L "${FILE}" ]
	then
		if [ -e "${FILE}" ]
		then
			mv -f "${FILE}" /var/run/linuxlogo/"$(basename ${FILE})"
		fi

		ln -sf /var/run/linuxlogo/"$(basename ${FILE})" "${FILE}"
	fi
done


case "${1}" in
	configure)
		rm -f /usr/bin/linux_logo_wait

		if [ -x "$(which invoke-rc.d)" ]
		then
			invoke-rc.d linuxlogo restart || exit ${?}
		else
			/etc/init.d/linuxlogo restart || exit ${?}
		fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installmenu/13.23
if [ "$1" = "configure" ] && [ -x "`command -v update-menus`" ] && [ -x "$DPKG_ROOT`command -v update-menus`" ]; then
	update-menus
fi
# End automatically added section
# Automatically added by dh_installinit/13.23
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/linuxlogo" ]; then
		update-rc.d linuxlogo defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native linuxlogo $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0
