#!/bin/sh

set -e

case "${1}" in
	purge|remove)
		rm -f /etc/issue.linuxlogo /etc/issue.linuxlogo.ascii
		rm -rf /var/run/linuxlogo/
		;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installinit/13.23
if [ "$1" = "remove" ] && [ -x "/etc/init.d/linuxlogo" ] ; then
	chmod -x "/etc/init.d/linuxlogo" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d linuxlogo remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installmenu/13.23
if [ -x "`command -v update-menus`" ] && [ -x "$DPKG_ROOT`command -v update-menus`" ]; then update-menus ; fi
# End automatically added section


exit 0
