#! /bin/sh

set -e

case "$1" in
    configure)

	# Cleanup old mediawiki.ini
	# This is intentionally PHP5 only, it was never installed
	# for PHP7.
	if [ -e "/usr/share/php5/php5-maintscript-helper" ]; then
		. /usr/share/php5/php5-maintscript-helper
		php5_invoke dismod ALL mediawiki
	fi

        chown -R www-data:www-data /var/lib/mediawiki/cache /var/lib/mediawiki/images
        chmod 700 /var/lib/mediawiki/cache /var/lib/mediawiki/images
        chown -R www-data:www-data /var/log/mediawiki
        chown -R www-data:www-data /var/cache/mediawiki

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_apache2/UNDECLARED
if true; then
	if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
		. /usr/share/apache2/apache2-maintscript-helper
		for conf in mediawiki  ; do
			apache2_invoke enconf $conf  || exit 1
		done
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/mediawiki/mediawiki.conf 1:1.35.0\~rc.1-1 -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'mediawiki-jobrunner.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'mediawiki-jobrunner.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'mediawiki-jobrunner.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'mediawiki-jobrunner.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'mediawiki-jobrunner.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'mediawiki-jobrunner.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
