#!/bin/sh

set -e

if [ "$1" = "configure" ] && [ "$2" ] && dpkg --compare-versions "$2" lt "1.08-1"; then
    if [ -e /etc/rc2.d/S40ps-watcher ] && \
       [ -e /etc/rc3.d/S40ps-watcher ] && \
       [ -e /etc/rc4.d/S40ps-watcher ] && \
       [ -e /etc/rc5.d/S40ps-watcher ] && \
       [ -e /etc/rc0.d/K40ps-watcher ] && \
       [ -e /etc/rc1.d/K40ps-watcher ] && \
       [ -e /etc/rc6.d/K40ps-watcher ]; then
        update-rc.d -f ps-watcher remove >/dev/null
    fi
fi

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/ps-watcher" ]; then
		update-rc.d ps-watcher defaults 99 01 >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native ps-watcher $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'ps-watcher.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'ps-watcher.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'ps-watcher.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'ps-watcher.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'ps-watcher.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'ps-watcher.service' >/dev/null || true
	fi
fi
# End automatically added section

