#!/bin/sh
set -e

# generate correct pid file, for versions where was non or incorrect
if [ "$1" = "upgrade" ] && [ "$2" ] && dpkg --compare-versions "$2" le "1.06-6"; then
	pidof ps-watcher > /var/run/ps-watcher.pid
fi
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/ps-watcher" ] ; then
	chmod +x "/etc/init.d/ps-watcher" >/dev/null || true
fi
# End automatically added section

