#!/bin/sh

set -e

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/openmohaa-server" ] ; then
	chmod -x "/etc/init.d/openmohaa-server" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d openmohaa-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'openmohaa-server.service' >/dev/null || true
	fi
fi
# End automatically added section


if [ "$1" = "purge" ] ; then
    # Lock account on purge
    if [ -f /etc/shadow ]; then
        usermod -L -e 1 _openmohaa-server
    else
        usermod -L _openmohaa-server
    fi
    rm -r /var/games/openmohaa-server
    rmdir --ignore-fail-on-non-empty /var/games
fi
