#!/bin/sh
# postrm script for mtail
# Script executed after the package is removed.

set -e

case "$1" in
  purge)
        rm -rf /var/log/mtail/ /var/run/mtail/
	# We do NOT remove the system user.
	;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/mtail" ] ; then
	chmod -x "/etc/init.d/mtail" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d mtail remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'mtail.service' >/dev/null || true
	fi
fi
# End automatically added section

