#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/o2cb" ] ; then
	chmod +x "/etc/init.d/o2cb" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/ocfs2" ] ; then
	chmod +x "/etc/init.d/ocfs2" >/dev/null || true
fi
# End automatically added section
