#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/ocfs2" ] ; then
	invoke-rc.d --skip-systemd-native ocfs2 stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/o2cb" ] ; then
	invoke-rc.d --skip-systemd-native o2cb stop || exit 1
fi
# End automatically added section
