#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/masakari-introspective-instance-monitor" ] ; then
	chmod -x "/etc/init.d/masakari-introspective-instance-monitor" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d masakari-introspective-instance-monitor remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'masakari-introspective-instance-monitor.service' >/dev/null || true
	fi
fi
# End automatically added section
