#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
  if [ -d "/etc/ircd" ]; then
    rm -rf /etc/ircd/*
    rmdir --ignore-fail-on-non-empty /etc/ircd
  fi
fi

if [ "$1" = "purge" ]; then
  if [ -d "/var/log/ircd" ]; then
    rm -rf /var/log/ircd/*
    rmdir --ignore-fail-on-non-empty /var/log/ircd
  fi
fi

if [ "$1" = "purge" ]; then
  if [ -d "/var/run/ircd" ]; then
    rm -rf /var/run/ircd/*
    rmdir --ignore-fail-on-non-empty /var/run/ircd
  fi
fi

# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ircd-ircu" ] ; then
	chmod -x "/etc/init.d/ircd-ircu" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d ircd-ircu remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ircd-ircu.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
