#!/bin/sh

set -e

if [ "${1}" = "configure" ] || [ "${1}" = "reconfigure" ] ; then
	A2EN=$(which a2ensite)
	if [ -x "${A2EN}" ] ; then
		${A2EN} tempest-ci.conf
	fi
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/openstack-tempest-ci-live-booter" ]; then
		update-rc.d openstack-tempest-ci-live-booter defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d openstack-tempest-ci-live-booter $_dh_action || exit 1
	fi
fi
# End automatically added section

