#!/bin/sh
set -e
# Automatically added by dh_apparmor/4.1.0-1
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.lib.mediascanner-2.0.mediascanner-extractor" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.lib.mediascanner-2.0.mediascanner-extractor" || true
    rm -f "/etc/apparmor.d/force-complain/usr.lib.mediascanner-2.0.mediascanner-extractor" || true
    rm -f "/etc/apparmor.d/local/usr.lib.mediascanner-2.0.mediascanner-extractor" || true
    rm -f /var/cache/apparmor/*/"usr.lib.mediascanner-2.0.mediascanner-extractor" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section
# Automatically added by dh_apparmor/4.1.0-1
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.bin.mediascanner-service-2.0" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.bin.mediascanner-service-2.0" || true
    rm -f "/etc/apparmor.d/force-complain/usr.bin.mediascanner-service-2.0" || true
    rm -f "/etc/apparmor.d/local/usr.bin.mediascanner-service-2.0" || true
    rm -f /var/cache/apparmor/*/"usr.bin.mediascanner-service-2.0" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemduser/13.24.2
if [ "$1" = "purge" ]; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'mediascanner-2.0.service' >/dev/null || true
	fi
fi
# End automatically added section
