#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/munin" ] ; then
	invoke-rc.d --skip-systemd-native munin stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/init/munin.conf 2.0.49-2\~ -- "$@"
# End automatically added section
