#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.15.2
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'rbldnsd.service' 'rbldnsd.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.15.2
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/rbldnsd" ] ; then
	invoke-rc.d --skip-systemd-native rbldnsd stop || exit 1
fi
# End automatically added section
