#!/bin/sh

set -e

case $1 in
    purge)
        if getent passwd msmtp >/dev/null; then
            if command -v deluser >/dev/null; then
                deluser --quiet msmtp >/dev/null
            fi
        fi
        ;;
    *)
        ;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/msmtpd" ] ; then
	chmod -x "/etc/init.d/msmtpd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d msmtpd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'msmtpd.service' >/dev/null || true
	fi
fi
# End automatically added section

