#!/bin/sh
set -e
# Automatically added by dh_installsysusers/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
   systemd-sysusers ${DPKG_ROOT:+--root="$DPKG_ROOT"} tinydns.conf
fi
# End automatically added section
# Automatically added by dh_runit/2.16.4
# Unlike postrm, I can be sure, that runit-helper is present on
# postinst.
#start: remove after trixie
if  [ ! -e /usr/lib/runit-helper/runit-helper ]; then
    #should not happen
    echo "warning: can't find runit-helper, postinst action skipped!"
    echo "warning: runit-helper: please report this bug"
fi
#end: remove after trixie
if [ -z "${DPKG_ROOT:-}" ] && [ -x /usr/lib/runit-helper/runit-helper ]; then
    NAME='tinydns' ENABLE='no' ONUPGRADE='restart' /usr/lib/runit-helper/runit-helper postinst "$@"
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/tinydns" ]; then
		update-rc.d tinydns defaults-disabled >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'tinydns.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'tinydns.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'tinydns.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'tinydns.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'tinydns.service' >/dev/null || true
fi
# End automatically added section
