#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.14.1
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/ddccontrol.DDCControl.conf 1.0.0-3\~ ddccontrol -- "$@"
# End automatically added section
# Automatically added by dh_installmenu/13.14.1
if [ -x "`command -v update-menus`" ] && [ -x "$DPKG_ROOT`command -v update-menus`" ]; then update-menus ; fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
