#!/bin/sh
set -e
# Automatically added by dh_installinit/13.23
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/rng-tools-debian" ] ; then
	chmod +x "/etc/init.d/rng-tools-debian" >/dev/null || true
fi
# End automatically added section
