#!/bin/sh

set -e


if [ "$1" = "purge" ] ; then
    rm -r /var/games/ufoai-server
    rmdir --ignore-fail-on-non-empty /var/games
fi

# Automatically added by dh_installsystemd/13.20
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ufoai-server.service' >/dev/null || true
	fi
fi
# End automatically added section

