#!/bin/sh
set -e
# Automatically added by dh_systemd_enable/13.20
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'gcpegg.service' >/dev/null || true
	fi
fi
# End automatically added section
