#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.23
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/pure-ftpd-postgresql pure-ftpd-common 1.0.49-4.1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.23
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/pure-ftpd-postgresql" ] ; then
	chmod +x "/etc/init.d/pure-ftpd-postgresql" >/dev/null || true
fi
# End automatically added section
