#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          batmand
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: start Better Approach To Mobile Ad-hoc Networking daemon
# Description:       This daemon configures routes between B.A.T.M.A.N. L3
#                    multi-hop ad-hoc mesh network nodes.
### END INIT INFO

# Author: Sven Eckelmann <sven@narfation.org>

DESC="Better Approach To Mobile Ad-hoc Networking daemon"
NAME=batmand
DAEMON=/usr/sbin/batmand
PIDFILE=/var/run/$NAME.pid
START_ARGS="--background --make-pidfile"

DAEMON_OPTS=""

# Read override variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

DAEMON_ARGS="--no-detach $DAEMON_OPTS"
