#!/bin/sh
set -e

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/nsd" ] ; then
	chmod -x "/etc/init.d/nsd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d nsd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nsd.service' >/dev/null || true
	fi
fi
# End automatically added section


if test "$1" = "purge"; then
    spool=/var/lib/nsd
    rm -f $spool/nsd.db $spool/ixfr.db $spool/xfrd.state
    rmdir $spool 2>/dev/null || true

    dpkg-statoverride --remove $spool >/dev/null 2>/dev/null || true

    # remove server/control keys on purge
    for f in nsd_control.key nsd_control.pem nsd_server.key nsd_server.pem; do
        rm -f "/etc/nsd/$f"
    done

    # delete nsd daemon user, if it exists
    if getent passwd nsd > /dev/null ; then
        deluser  --quiet nsd > /dev/null || true
    fi
fi

exit 0
