#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/sudo-ldap" ] ; then
	invoke-rc.d --skip-systemd-native sudo-ldap stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/init.d/sudo 1.8.21p2-2\~ -- "$@"
# End automatically added section
