#!/bin/sh -e

if test "$1" = purge; then
	rm -f /etc/zephyr/server.list
fi

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/zephyrd" ] ; then
	chmod -x "/etc/init.d/zephyrd" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d zephyrd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.15.3
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
