#!/bin/sh -e

invoke-rc.d --quiet udev reload || true

# Those using dependency based boot sequencing with sysv-rc and installing
# ekeyd-egd-linux before and including version 1.0.4-1 would have wrong
# runlevel symlinks.  Recover from this.
if [ "$1" = "configure" ] && \
   dpkg --compare-versions "$2" le "1.0.4-1" && \
   [ -f /etc/rcS.d/S[0-9][0-9]ekeyd ] ; then
   update-rc.d -f ekeyd remove
fi

# Automatically added by dh_installinit/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/ekeyd" ]; then
		update-rc.d ekeyd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native ekeyd $_dh_action || exit 1
	fi
fi
# End automatically added section


chmod 0600 /etc/entropykey/keyring || true

