#!/bin/sh -e

invoke-rc.d --quiet udev reload || true

# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ekeyd" ] ; then
	chmod -x "/etc/init.d/ekeyd" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d ekeyd remove >/dev/null
fi
# End automatically added section

