#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/anope" ] ; then
	chmod -x "/etc/init.d/anope" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d anope remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/anope/default 2.0.7-1\~ anope -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'anope.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/4.1.0~beta5-5
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.sbin.anope" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.sbin.anope" || true
    rm -f "/etc/apparmor.d/force-complain/usr.sbin.anope" || true
    rm -f "/etc/apparmor.d/local/usr.sbin.anope" || true
    rm -f /var/cache/apparmor/*/"usr.sbin.anope" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section
