#!/bin/sh
# vim: ts=4:et:sts=4
# $Id: beanstalkd.postrm 89 2009-01-03 16:34:01Z robert $

set -e

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/beanstalkd" ] ; then
	chmod -x "/etc/init.d/beanstalkd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d beanstalkd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'beanstalkd.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'beanstalkd.service' >/dev/null || true
	fi
fi
# End automatically added section


PACKAGE=beanstalkd
DEFAULTSFILE=/etc/default/$PACKAGE


case "$1" in
   failed-install|abort-install|abort-upgrade|failed-upgrade)
        exit 0
    ;;

    remove)
        if [ -d /var/lib/beanstalkd ]; then
            if [ $(find /var/lib/beanstalkd | wc -l) -eq 1 ]; then
                rmdir /var/lib/beanstalkd
            fi
        fi
        exit 0
    ;;
    purge)
        echo "purge requested, thus removing /var/lib/beanstalkd"
        rm -rf /var/lib/beanstalkd/

        # remove user, group and home directory beanstalkd
        deluser --remove-home beanstalkd >/dev/null 2>&1 || true

        exit 0
    ;;
    upgrade|disappear)
        exit 0
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
