#!/bin/sh
set -e

case ${1} in
	purge)
		rm -f /etc/schroot/mini-buildd/fstab
		# On purge, force-remove user mini-buildd along with all files.
		# Be sure to give the user a warning, though, as he might
		# lose valuable data like repositories
		. /usr/share/debconf/confmodule
		db_input critical mini-buildd/purge_warning || true
		db_go || true
		userdel --force --remove mini-buildd || true
		;;
esac

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/mini-buildd" ] ; then
	chmod -x "/etc/init.d/mini-buildd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d mini-buildd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/mini-buildd.bash-completion -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.weekly/mini-buildd -- "$@"
dpkg-maintscript-helper rm_conffile /etc/schroot/setup.d/15mini-buildd-workarounds -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'mini-buildd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
