#!/bin/sh
set -e

if [ "${1}" = "remove" ]; then
	# Prepared Chroot models may have made extra changes to the
	# system. We need to properly run 'unprepare' to all of them
	# to not leave artefacts (i.e., /etc/schroot/chroot.d/*.conf
	# plus backend-related cruft like LVM setups).
	# (We cannot do it in postrm/purge as we need mini-buildd still installed for that.)
	su mini-buildd -c "/usr/sbin/mini-buildd --remove-system-artifacts" || true
fi

# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'mini-buildd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/mini-buildd" ] ; then
	invoke-rc.d --skip-systemd-native mini-buildd stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/mini-buildd.bash-completion -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.weekly/mini-buildd -- "$@"
dpkg-maintscript-helper rm_conffile /etc/schroot/setup.d/15mini-buildd-workarounds -- "$@"
# End automatically added section


exit 0
