#!/bin/sh

set -e

case $1 in
    purge)
	rm -rf /etc/tmate-ssh-server/keys
    ;;
esac

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/tmate-ssh-server" ] ; then
	chmod -x "/etc/init.d/tmate-ssh-server" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d tmate-ssh-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'tmate-ssh-server.service' >/dev/null || true
	fi
fi
# End automatically added section

