#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.13
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'smokeping.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.13
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/smokeping" ] ; then
	invoke-rc.d --skip-systemd-native smokeping stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.13
dpkg-maintscript-helper mv_conffile /etc/smokeping/apache2.conf /etc/apache2/conf-available/smokeping.conf -- "$@"
# End automatically added section
# Automatically added by dh_apache2/UNDECLARED
if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in smokeping  ; do
				apache2_invoke disconf $conf  || exit 1
			done
		fi
	fi
fi
# End automatically added section
