#!/bin/sh

set -e

case "$1" in
  purge)
	if [ -e /var/spool/news ]; then
		# we need the debconf library
		. /usr/share/debconf/confmodule

		# Prompt here rather than in configure since there may
		# be a considerable gap between configuration and
		# removal.
		db_input high leafnode/purge || true
		db_go

		db_get leafnode/purge || true
		answer=$RET

		if [ "$answer" = "true" ]; then
			rm -rf /var/spool/news
			echo ""
		fi
	fi
	rm -rf /var/lib/leafnode
	rm -rf /etc/news/leafnode
  ;;
  remove)
  ;;

  upgrade|deconfigure)
  ;;
         
  failed-upgrade)
  ;;

  abort-upgrade)
  ;;
                
  *)
	echo "unknown argument --> $1" >&2
	exit 0
  ;;
esac

# Automatically added by dh_installsystemd/13.23
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'leafnode-fetchnews.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'leafnode.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'leafnode.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.23
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

