#!/bin/sh

set -e

. /usr/share/debconf/confmodule

add_group_if_missing() {
    if ! getent group direwolf >/dev/null; then
        addgroup --system --force-badname direwolf || true
    fi
}

add_user_if_missing() {
    if ! id -u direwolf > /dev/null 2>&1; then
        mkdir -m 02750 -p /var/lib/direwolf
        adduser --system --home /var/lib/direwolf \
          --disabled-password \
          --force-badname direwolf \
          --ingroup direwolf
        adduser direwolf dialout
        chown direwolf:direwolf /var/lib/direwolf
    fi
}

add_group_if_missing
add_user_if_missing

db_stop

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'direwolf.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'direwolf.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'direwolf.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'direwolf.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'direwolf.service' >/dev/null || true
fi
# End automatically added section


exit 0

