#!/bin/sh
# postinst script for wesnoth-1.18-server
# Copyright 2024 by P. J. McDermott
# Licensed under Expat

set -e

add_user()
{
	adduser --quiet --system --group --disabled-password \
		--home /run/wesnothd \
		--gecos 'Wesnoth Multiplayer Server Daemon' \
		_wesnoth
	mkdir /run/wesnothd/1.18
}

case "$1" in
	configure)
		add_user
	;;
esac

# Automatically added by dh_installtmpfiles/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "$(command -v systemd-tmpfiles)" ]; then
		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create wesnoth-1.18-server.conf || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/wesnoth-1.18-server" ]; then
		update-rc.d wesnoth-1.18-server defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native wesnoth-1.18-server $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'wesnoth-1.18-server.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'wesnoth-1.18-server.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'wesnoth-1.18-server.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'wesnoth-1.18-server.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'wesnoth-1.18-server.service' >/dev/null || true
fi
# End automatically added section


exit 0
