#!/bin/sh
# postrm script for wesnoth-1.18-server
# Copyright 2024 by P. J. McDermott
# Licensed under Expat

set -e

del_user()
{
	rmdir /run/wesnothd/1.18 || true
	deluser --quiet --remove-home _wesnoth || \
		deluser --quiet _wesnoth || true
}

case "$1" in
	remove)
		del_user
	;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/wesnoth-1.18-server" ] ; then
	chmod -x "/etc/init.d/wesnoth-1.18-server" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d wesnoth-1.18-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'wesnoth-1.18-server.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
