#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/init.d/dnsdist.conf-dist 1.8.2-3\~ dnsdist -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/dnsdist" ] ; then
	chmod +x "/etc/init.d/dnsdist" >/dev/null || true
fi
# End automatically added section
