#!/bin/sh
set -e

# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p pagure-milters /usr/share/pagure-milters
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p pagure-milters /usr/share/pagure-milters || true
fi

# End automatically added section
# Automatically added by dh_installtmpfiles/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "$(command -v systemd-tmpfiles)" ]; then
		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create pagure-milters.conf || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'pagure-milters.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'pagure-milters.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'pagure-milters.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'pagure-milters.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'pagure-milters.service' >/dev/null || true
fi
# End automatically added section
