#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.14.1
dpkg-maintscript-helper rm_conffile /etc/icecast2/web/status2.xsl 2.4.0-1\~ icecast2 -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.14.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/icecast2" ] ; then
	chmod +x "/etc/init.d/icecast2" >/dev/null || true
fi
# End automatically added section
