#!/bin/sh
set -e
# Automatically added by dh_installinit/13.14.1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/icecast2" ] ; then
	invoke-rc.d --skip-systemd-native icecast2 stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.14.1
dpkg-maintscript-helper rm_conffile /etc/icecast2/web/status2.xsl 2.4.0-1\~ icecast2 -- "$@"
# End automatically added section
