#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
        if getent passwd gnome-initial-setup >/dev/null; then
                if which deluser >/dev/null 2>&1; then
                        deluser --system gnome-initial-setup || echo "Could not remove gnome-initial-setup user."
                fi
        fi
fi
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/gnome-welcome-tour.desktop 40.1-2\~ -- "$@"
# End automatically added section

exit 0
