#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
  systemd-sysusers
fi

# Automatically added by dh_installsysusers/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
   systemd-sysusers ${DPKG_ROOT:+--root="$DPKG_ROOT"} mimic.conf
fi
# End automatically added section


exit 0
