#!/bin/sh

set -e

LOGDIR=/var/log/solarpowerlog

if [ "$1" = "purge" ]
then
    rm -rf $LOGDIR || true
fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/solarpowerlog" ] ; then
	chmod -x "/etc/init.d/solarpowerlog" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d solarpowerlog remove >/dev/null
fi
# End automatically added section


exit 0
