#!/bin/sh
### BEGIN INIT INFO
# Provides:          octavia-agent-netns
# Required-Start:    $remote_fs $syslog $network cloud-config
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Creates an encrypted ramfs for Octavia certs
# Description:       Creates an encrypted ramfs for Octavia TLS
#                    certificates and key storage.
### END INIT INFO

# Using the lsb functions to perform the operations.
. /lib/lsb/init-functions
# Process name ( For display )
NAME=octavia-agent-certs-netns

PATH=/sbin:/usr/sbin:/bin:/usr/bin

case $1 in
start)
	log_daemon_msg "Starting Octavia Agent netns (octavia-agent-netns-start)" "$NAME"
	octavia-agent-netns-start
	log_end_msg $?
;;
stop)
	log_daemon_msg "Stopping Octavia Agent netns (octavia-agent-netns-stop)" "$NAME"
	octavia-agent-netns-stop
	log_end_msg $?
;;
restart|force-reload)
	# Restart the daemon.
	$0 stop && sleep 2 && $0 start
;;
*)
	# For invalid arguments, print the usage message.
	echo "Usage: $0 {start|stop|restart|reload|status}"
	exit 2
;;
esac
