#!/bin/sh 

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
#

[ -f /etc/logrotate.d/proftpd-basic ] && \
	mv -f /etc/logrotate.d/proftpd-basic /etc/logrotate.d/proftpd-core

if [ "$1" = "upgrade" ]; then
     invoke-rc.d --skip-systemd-native proftpd stop >/dev/null 2>&1 || true 
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/proftpd" ] ; then
	chmod +x "/etc/init.d/proftpd" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'proftpd.socket' >/dev/null || true
fi
# End automatically added section

