#!/bin/sh

set -e

if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ;
then
    deb-systemd-invoke stop 'proftpd.service' 'proftpd.socket' >/dev/null || true
fi

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'proftpd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/proftpd" ] ; then
	invoke-rc.d --skip-systemd-native proftpd stop || exit 1
fi
# End automatically added section

