#!/bin/sh

set -e

if [ "$1" = configure ]; then
  update-alternatives --install /usr/bin/x-session-manager \
    x-session-manager /usr/libexec/gnome-flashback-metacity 40 \
    --slave /usr/share/man/man1/x-session-manager.1.gz \
    x-session-manager.1.gz /usr/share/man/man1/gnome-session.1.gz
fi

# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/gnome-flashback-screensaver.desktop 3.36.0-3\~ gnome-session-flashback -- "$@"
# End automatically added section

