#!/bin/sh

set -e

if [ "$1" = upgrade ]; then
  update-alternatives --remove \
    x-session-manager /usr/lib/gnome-panel/gnome-session-flashback
  update-alternatives --remove \
    x-session-manager /usr/lib/gnome-flashback/gnome-flashback-metacity
fi

# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/gnome-flashback-screensaver.desktop 3.36.0-3\~ gnome-session-flashback -- "$@"
# End automatically added section

