#!/bin/sh
set -e

if [ "$1" = configure ]; then
	. /etc/ikiwiki-hosting/ikiwiki-hosting.conf || true
	if [ -n "$gitdaemondir" ] && [ -n "$gitdaemonuser" ]; then
		adduser --quiet --system --group --no-create-home --home "$gitdaemondir" "$gitdaemonuser"
	fi
fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/ikiwiki-hosting-web" ]; then
		update-rc.d ikiwiki-hosting-web defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native ikiwiki-hosting-web $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'ikiwiki-hosting-web.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'ikiwiki-hosting-web.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'ikiwiki-hosting-web.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'ikiwiki-hosting-web.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'ikiwiki-hosting-web.service' >/dev/null || true
	fi
fi
# End automatically added section


a2enmod suexec
a2enmod ssl
if which invoke-rc.d >/dev/null 2>&1; then
	invoke-rc.d apache2 restart
else
	service apache2 restart
fi
