#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
	(
		cd /etc/sitesummary
		rm -f config.d/00debconf
		rm -f hostclass site sitecontact sitegroup
		rmdir config.d 2>/dev/null || true
	)
fi

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/sitesummary-client" ] ; then
	chmod -x "/etc/init.d/sitesummary-client" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d sitesummary-client remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'sitesummary-client.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.15.3
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

