#!/bin/sh
set -e
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/sitesummary-client" ] ; then
	chmod +x "/etc/init.d/sitesummary-client" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'sitesummary-client.service' 'sitesummary-client.timer' >/dev/null || true
fi
# End automatically added section
