#!/bin/sh
set -e
# Automatically added by dh_installinit/13.10
if [ "$1" = "remove" ] && [ -x "/etc/init.d/httpry" ] ; then
	chmod -x "/etc/init.d/httpry" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d httpry remove >/dev/null
fi
# End automatically added section
