#!/bin/sh
set -e
# Automatically added by dh_installinit/13.10
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/httpry" ] ; then
	invoke-rc.d httpry stop || exit 1
fi
# End automatically added section
