#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/corosync-signals.conf 3.1.8-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/corosync-notifyd" ] ; then
	chmod +x "/etc/init.d/corosync-notifyd" >/dev/null || true
fi
# End automatically added section
