#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.15.3
dpkg-maintscript-helper rm_conffile /etc/kernel/postinst.d/zzz-chkboot 1.3-4\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/kernel/postrm.d/zzz-chkboot 1.3-4\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/chkboot" ] ; then
	chmod +x "/etc/init.d/chkboot" >/dev/null || true
fi
# End automatically added section
