#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'chkboot.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/chkboot" ] ; then
	invoke-rc.d --skip-systemd-native chkboot stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.15.3
dpkg-maintscript-helper rm_conffile /etc/kernel/postinst.d/zzz-chkboot 1.3-4\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/kernel/postrm.d/zzz-chkboot 1.3-4\~ -- "$@"
# End automatically added section
