#!/bin/sh
set -e

# automatically remove cached tiles
if [ -d /var/cache/renderd/tiles ]
then
    rm -rf /var/cache/renderd/tiles
fi

# automatically remove munin plugins
if [ -d /etc/munin/plugins ]
then
    rm -f /etc/munin/plugins/renderd_*
fi

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'renderd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/renderd" ] ; then
	invoke-rc.d --skip-systemd-native renderd stop || exit 1
fi
# End automatically added section

