#!/bin/sh
set -e
# Automatically added by dh_installinit/13.16
if [ "$1" = "remove" ] && [ -x "/etc/init.d/nsca-ng-server" ] ; then
	chmod -x "/etc/init.d/nsca-ng-server" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d nsca-ng-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.16
dpkg-maintscript-helper rm_conffile /etc/default/nsca-ng-server -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nsca-ng-server.service' 'nsca-ng-server.socket' >/dev/null || true
	fi
fi
# End automatically added section
