#!/bin/bash

set -e

setperm() {
    local user="$1"
        local group="$2"
        local mode="$3"
        local file="$4"
        shift 4
# only do something when no setting exists
        if ! dpkg-statoverride --list "$file" >/dev/null 2>&1; then
            chown "$user":"$group" "$file"
                chmod "$mode" "$file"
                fi
}

case "$1" in
    configure)
        if ! getent passwd nagios > /dev/null ; then
            echo 'Adding system-user for nagios' 1>&2
            adduser --system --group --home /var/lib/nagios \
                --disabled-login --force-badname nagios > /dev/null
        fi

        # explicitly set some permissions
        setperm root root 0600 /etc/nsca-ng/nsca-ng.cfg

        test -d /var/run/nsca-ng || mkdir -p /var/run/nsca-ng
        setperm nagios nagios 0700 /var/run/nsca-ng

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
    echo "postinst called with unknown argument \$1'" >&2
    exit 1
    ;;
esac

# Automatically added by dh_installdeb/13.16
dpkg-maintscript-helper rm_conffile /etc/default/nsca-ng-server -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/nsca-ng-server" ]; then
		update-rc.d nsca-ng-server defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native nsca-ng-server $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'nsca-ng-server.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'nsca-ng-server.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'nsca-ng-server.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'nsca-ng-server.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'nsca-ng-server.socket' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'nsca-ng-server.socket'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'nsca-ng-server.socket' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'nsca-ng-server.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'nsca-ng-server.service' 'nsca-ng-server.socket' >/dev/null || true
	fi
fi
# End automatically added section

