#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.16
dpkg-maintscript-helper rm_conffile /etc/default/nsca-ng-server -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.16
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/nsca-ng-server" ] ; then
	chmod +x "/etc/init.d/nsca-ng-server" >/dev/null || true
fi
# End automatically added section
