#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.16
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'nsca-ng-server.service' 'nsca-ng-server.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.16
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/nsca-ng-server" ] ; then
	invoke-rc.d --skip-systemd-native nsca-ng-server stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.16
dpkg-maintscript-helper rm_conffile /etc/default/nsca-ng-server -- "$@"
# End automatically added section
