#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Code copied from dh_systemd_enable ----------------------
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask glewlwyd.service >/dev/null || true

if deb-systemd-helper --quiet was-enabled glewlwyd.service; then
  # Enables the unit on first installation, creates new
  # symlinks on upgrades if the unit file has changed.
  deb-systemd-helper enable glewlwyd.service >/dev/null || true
else
  # Update the statefile to add new symlinks (if any), which need to be
  # cleaned up on purge. Also remove old symlinks.
  deb-systemd-helper update-state glewlwyd.service >/dev/null || true
fi

# Create the glewlwyd user in glewlwyd, so that Dbus doesn't complain.

# create a user to run as (code stolen from dnsmasq)
if [ "$1" = "configure" ]; then
  CONFIG_DIR="/etc/glewlwyd"
  CONFIG="$CONFIG_DIR/glewlwyd.conf"
  CONFIG_DB="$CONFIG_DIR/glewlwyd-db.conf"

  db_get glewlwyd/config_type || true

  if [ "$RET" = "Personalized" ]; then
    mkdir -p $CONFIG_DIR || true
    cp /usr/share/glewlwyd/templates/glewlwyd-debian.conf.properties $CONFIG

    if [ -z "`id -u glewlwyd 2> /dev/null`" ]; then
      echo "Add user glewlwyd"
      adduser --system  --home /etc/glewlwyd --gecos "glewlwyd" \
              --no-create-home --disabled-password \
              --quiet glewlwyd || true
    fi

    if [ ! -f /var/log/glewlwyd.log ]; then
      touch /var/log/glewlwyd.log
      chown glewlwyd /var/log/glewlwyd.log
    fi

    dbc_generate_include="template:$CONFIG_DB"
    dbc_generate_include_perms="660"
    dbc_generate_include_owner="glewlwyd:root"
    dbc_generate_include_args="-o template_infile=/usr/share/glewlwyd/templates/glewlwyd-db.conf.properties"
    dbc_mysql_createdb_encoding="UTF8"
    dbc_pgsql_createdb_encoding="UTF8"
    dbc_basepath="/var/cache/glewlwyd"
    dbc_dbfile_owner="glewlwyd:root"
    dbc_dbfile_perms="0660"

    . /usr/share/dbconfig-common/dpkg/postinst
    dbc_go glewlwyd "$@" || true

    db_get glewlwyd/config_external_url || true
    sed -i -e "s,_G_EXTRNAL_URL_,$RET,g" $CONFIG

    if [ "$dbc_dbtype" = "mysql" ]; then
      sed -i -e "s,_G_DB_TYPE_,mariadb," $CONFIG_DB
    elif [ "$dbc_dbtype" = "sqlite3" ]; then
      sed -i -e "s,_G_DB_TYPE_,sqlite3," $CONFIG_DB
    else
      db_get glewlwyd/need_pgcrypto
      echo "Initializing PostgreSQL database"
      sed -i -e "s,_G_DB_TYPE_,postgre," $CONFIG_DB
      su - postgres -c "psql -h$dbc_dbserver $dbc_dbname -c 'create extension if not exists pgcrypto;'" || true
      su - postgres -c "psql -h$dbc_dbserver $dbc_dbname < /usr/share/dbconfig-common/data/glewlwyd/install/postgre.default.sql"
    fi

  else
    if [ ! -f $CONFIG ]; then
      gunzip --stdout /usr/share/doc/glewlwyd/glewlwyd.conf.sample.gz > $CONFIG
    fi
  fi

  echo "Start Glewlwyd service"
  invoke-rc.d glewlwyd start || true
fi
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/glewlwyd" ]; then
		update-rc.d glewlwyd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native glewlwyd $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'glewlwyd.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'glewlwyd.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'glewlwyd.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'glewlwyd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'glewlwyd.service' >/dev/null || true
	fi
fi
# End automatically added section

