#!/bin/sh
set -e

. /usr/share/debconf/confmodule

if [ "$1" = "remove" ]; then
	if which invoke-rc.d >/dev/null 2>&1 ; then
			invoke-rc.d glewlwyd stop || true
	else
			/etc/init.d/glewlwyd stop || true
	fi
fi

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'glewlwyd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/glewlwyd" ] ; then
	invoke-rc.d --skip-systemd-native glewlwyd stop || exit 1
fi
# End automatically added section

