#!/bin/sh

# Remove /etc/printcap file on purge ONLY if it has not changed.
if [ "x$1" = "xpurge" ] ; then
	cmp -s /etc/printcap /usr/share/doc/lpr/examples/printcap
	if [ $? -eq 0 ] ; then
		rm -f /etc/printcap
	fi
fi

# Automatically added by dh_installinit/13.23
if [ "$1" = "remove" ] && [ -x "/etc/init.d/lpd" ] ; then
	chmod -x "/etc/init.d/lpd" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d lpd remove >/dev/null
fi
# End automatically added section

