#!/bin/sh

set -e

if [ -x /usr/sbin/lpd ]; then
	start-stop-daemon --stop --quiet --oknodo --name lpd --exec /usr/sbin/lpd
fi

# Automatically added by dh_installinit/13.23
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/lpd" ] ; then
	chmod +x "/etc/init.d/lpd" >/dev/null || true
fi
# End automatically added section

