#!/bin/sh
set -e
# Automatically added by dh_installinit/13.15.2
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/ypxfrd" ] ; then
	invoke-rc.d --skip-systemd-native ypxfrd stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/13.15.2
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/yppasswdd" ] ; then
	invoke-rc.d --skip-systemd-native yppasswdd stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/13.15.2
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/ypserv" ] ; then
	invoke-rc.d --skip-systemd-native ypserv stop || exit 1
fi
# End automatically added section
