#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/neutron-api" ] ; then
	invoke-rc.d neutron-api stop || true
fi
# End automatically added section
