#!/bin/sh -e

if [ "$1" = "purge" ]; then
	rm -f /etc/iftab
fi

# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ifrename" ] ; then
	chmod -x "/etc/init.d/ifrename" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d ifrename remove >/dev/null
fi
# End automatically added section

