#!/bin/sh
#
# Postinst script for fetchmail
# $Id: fetchmail.postinst 469 2008-05-18 12:47:05Z nion $
#

set -e

# Create fetchmail user and its homedir if we may need it
if ! getent passwd fetchmail >/dev/null; then
	adduser --system --ingroup nogroup --home /var/lib/fetchmail \
	--shell /bin/false --disabled-password fetchmail
fi

# if the login shell is not /bin/false, change this, see #481727
LOGINSH=$(getent passwd fetchmail | cut -d ':' -f 7)
if [ "x$LOGINSH" != "x/bin/false" ]; then
	chsh -s /bin/false fetchmail
fi

if ! [ -d /var/lib/fetchmail ]; then
    mkdir -p /var/lib/fetchmail
fi
chmod 700 /var/lib/fetchmail
chown -h -R fetchmail:nogroup /var/lib/fetchmail

# Automatically added by dh_installsystemduser/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ]; then
		if deb-systemd-helper --user debian-installed 'fetchmail.service' ; then
			# The following line should be removed in trixie or trixie+1
			deb-systemd-helper --user unmask 'fetchmail.service' >/dev/null || true

			if deb-systemd-helper --quiet --user was-enabled 'fetchmail.service' ; then
				# Create new symlinks, if any.
				deb-systemd-helper --user enable 'fetchmail.service' >/dev/null || true
			fi
		fi

		# Update the statefile to add new symlinks (if any), which need to be cleaned
		# up on purge. Also remove old symlinks.
		deb-systemd-helper --user update-state 'fetchmail.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/fetchmail" ]; then
		update-rc.d fetchmail defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native fetchmail $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0

# vim:ts=4:sw=4:
