#!/bin/sh

set -e
# Stops daemon if it is running under our control
if [ -x /etc/init.d/fetchmail ]; then
    invoke-rc.d --quiet fetchmail stop
fi

# Automatically added by dh_installinit/13.16
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/fetchmail" ] ; then
	invoke-rc.d --skip-systemd-native fetchmail stop || exit 1
fi
# End automatically added section


exit 0
