#!/bin/sh
set -e

# generate correct pid file, for versions where was non or incorrect
if [ "$1" = "upgrade" ] && [ "$2" ] && dpkg --compare-versions "$2" <= "1.12-1"; then
	pidof dns-flood-detector > /var/run/dns-flood-detector.pid
fi
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/dns-flood-detector" ] ; then
	chmod +x "/etc/init.d/dns-flood-detector" >/dev/null || true
fi
# End automatically added section

