#! /bin/sh
# postrm script for oar-server
#
# see: dh_installdeb(1)

set -e
#set -x 

case "$1" in
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	  true
        ;;
	purge)
            # Remove the possible conffiles 
            for conffile in /etc/oar/job_resource_manager.pl \
                            /etc/oar/job_resource_manager_cgroups.pl \
                            /etc/oar/oarmonitor_sensor.pl \
                            /etc/oar/scheduler_quotas.conf \
                            /etc/oar/server_epilogue \
                            /etc/oar/server_prologue \
                            /etc/oar/shut_down_nodes.sh \
                            /etc/oar/suspend_resume_manager.pl \
                            /etc/oar/wake_up_nodes.sh ; do
                # we mimic dpkg as closely as possible, so we remove configuration
                # files with dpkg backup extensions too:
                ### Some of the following is from Tore Anderson:
                for ext in '~' '%' .bak .dpkg-tmp .dpkg-new .dpkg-old .dpkg-dist .ucf-old .ucf-new .ucf-dist;  do
                    rm -f $conffile$ext
                done
                # remove the configuration file itself
                rm -f $conffile
                # and finally clear it out from the ucf database
                if which ucf >/dev/null; then
                        ucf --purge $conffile
                fi
                if which ucfr >/dev/null; then
                    ucfr --purge oar-server $conffile
                fi
            done
            # Remove directories in var
            rm -rf /var/lib/oar/phoenix
        ;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
esac

# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/init.d/oar-server 2.5.10\~g5k10-2 oar-server -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/oar-server 2.5.10\~g5k10-2 oar-server -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'oar-accounting.timer' 'oar-server.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'oar-accounting.timer' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
