#!/bin/sh

set -e

case "$1" in
    configure)
        # Create a tinyproxy system group
        if ! getent group tinyproxy > /dev/null; then
            addgroup --quiet --system tinyproxy
        fi

        # Create a tinyproxy system user
        if ! getent passwd tinyproxy > /dev/null; then
            adduser --quiet --system \
                --ingroup tinyproxy \
                --home /run/tinyproxy \
                --disabled-password --shell /bin/false \
                tinyproxy
            usermod -c "Tinyproxy daemon" tinyproxy
        fi

        chmod 750 /var/log/tinyproxy
        chmod 640 /var/log/tinyproxy/* 2>/dev/null || true
        chown tinyproxy:adm /var/log/tinyproxy
        chown tinyproxy:adm /var/log/tinyproxy/* 2>/dev/null || true
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "ERROR: Postinst called with unknown argument!"
        exit 0
    ;;
esac

# Automatically added by dh_installtmpfiles/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "$(command -v systemd-tmpfiles)" ]; then
		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create tinyproxy.conf || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/tinyproxy" ]; then
		update-rc.d tinyproxy defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native tinyproxy $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'tinyproxy.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'tinyproxy.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'tinyproxy.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'tinyproxy.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'tinyproxy.service' >/dev/null || true
	fi
fi
# End automatically added section

