#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
    if getent passwd tinyproxy >/dev/null; then
        if which deluser >/dev/null 2>&1; then
            deluser --quiet --system tinyproxy || echo "Could not remove tinyproxy user."
        fi
    fi
    # Get rid of leftover logs
    rm -rf /var/log/tinyproxy
fi

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/tinyproxy" ] ; then
	chmod -x "/etc/init.d/tinyproxy" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d tinyproxy remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'tinyproxy.service' >/dev/null || true
	fi
fi
# End automatically added section

