#!/bin/sh

set -e

case "${1}" in
    configure)
        if ! getent passwd _gfarmfs > /dev/null 2>&1; then
            adduser --quiet --system --force-badname --group --disabled-login --no-create-home --home /var/lib/gfarmfs _gfarmfs
        fi
        chown _gfarmfs:_gfarmfs /var/lib/gfarmfs
    ;;
esac

# Automatically added by dh_installinit/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/gfmd" ]; then
		update-rc.d gfmd defaults >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'gfmd.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'gfmd.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'gfmd.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'gfmd.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'gfmd.service' >/dev/null || true
fi
# End automatically added section

