#!/bin/sh

# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/gfmd" ] ; then
	chmod -x "/etc/init.d/gfmd" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d gfmd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'gfmd.service' >/dev/null || true
	fi
fi
# End automatically added section


case "${1}" in
    purge)
        rm -f /etc/systemd/system/gfmd.service \
              /etc/systemd/system/gfarm-pgsql.service
    ;;
esac
