#! /bin/sh

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

set -e

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/kdump-tools" ] ; then
	chmod -x "/etc/init.d/kdump-tools" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d kdump-tools remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper mv_conffile /etc/default/grub.d/kdump-tools.default /etc/default/grub.d/kdump-tools.cfg 1:1.6.1-2\~ kdump-tools -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/grub.d/kdump-tools..ppc64el 1:1.6.1-2\~ kdump-tools -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'kdump-tools.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


case "$1" in
       remove)
	       if test -e /etc/zipl.conf;then
	             sed -i "s/ crashkernel=.*M//" /etc/zipl.conf
		     zipl
	       fi
	       if command -v update-grub > /dev/null && [ -e /boot/grub/grub.cfg ]; then
		       update-grub
	       fi
	       ;;
       purge)
		rm -rf /var/lib/kdump
		if command -v ucf > /dev/null 2>&1; then
			ucf --purge /etc/default/kdump-tools
			ucfr -p kdump-tools /etc/default/kdump-tools
		fi
		rm -f /etc/default/kdump-tools
		for i in new old dist; do
			rm -f /etc/default/kdump-tools.ucf-$i
		done
	       ;;
esac

