#!/bin/sh

# atheme
# Version:	atheme-2.2.0  06/08/07
# Author:	Bradley Smith <brad@brad-smith.co.uk>

set -e

case "$1" in
    purge)
	rm -rf /etc/atheme
        rm -rf /var/run/atheme
        rm -rf /var/lib/atheme
        rm -rf /var/log/atheme
    ;;

esac

# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/atheme-services" ] ; then
	chmod -x "/etc/init.d/atheme-services" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d atheme-services remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.20
dpkg-maintscript-helper rm_conffile /etc/default/atheme-services 7.2.9-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'atheme-services.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
