#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.20
dpkg-maintscript-helper rm_conffile /etc/default/atheme-services 7.2.9-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.20
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/atheme-services" ] ; then
	chmod +x "/etc/init.d/atheme-services" >/dev/null || true
fi
# End automatically added section
