#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/news/motd.news 2.5.3-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/news/radius.conf 2.6.1-3\~ -- "$@"
# End automatically added section
