#!/bin/sh -e

kill_innd() {
    if [ -x /etc/init.d/inn2 ]; then
	invoke-rc.d inn2 stop
    fi
}

case "$1" in
    remove|deconfigure|failed-upgrade)
	kill_innd
    ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'inn2.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/news/motd.news 2.5.3-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/news/radius.conf 2.6.1-3\~ -- "$@"
# End automatically added section


exit 0
