#!/bin/sh

set -e

if test "$1" = "configure" -o "$1" = "reconfigure" ; then

    test -r /etc/default/myproxy-server && . /etc/default/myproxy-server

    if test -z "$MYPROXY_USER" -o "$MYPROXY_USER" = "myproxy" ; then

	getent group myproxy > /dev/null || \
	    addgroup --quiet --system myproxy

	getent passwd myproxy > /dev/null || \
	    adduser --quiet --system --home /var/lib/myproxy \
	    --shell /bin/false --ingroup myproxy --disabled-password \
	    --disabled-login --gecos "User to run the MyProxy service" myproxy

	chown myproxy:myproxy /var/lib/myproxy

    fi

fi

# Automatically added by dh_installtmpfiles/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "$(command -v systemd-tmpfiles)" ]; then
		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create myproxy-server.conf || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/myproxy-server" ]; then
		update-rc.d myproxy-server defaults-disabled >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native myproxy-server $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'myproxy-server.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'myproxy-server.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'myproxy-server.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'myproxy-server.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'myproxy-server.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'myproxy-server.service' >/dev/null || true
	fi
fi
# End automatically added section

