#!/bin/sh
# pre-removal script for popa3d

set -e

# Automatically added by dh_installinit/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/popa3d" ] ; then
	invoke-rc.d popa3d stop || exit 1
fi
# End automatically added section


update-inetd --disable pop3
