#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.11.8
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'proxsmtp.target' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.8
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/proxsmtp" ] ; then
	invoke-rc.d --skip-systemd-native proxsmtp stop || exit 1
fi
# End automatically added section
