#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.23
dpkg-maintscript-helper rm_conffile /etc/network/if-up.d/avahi-daemon 0.8-4\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/resolvconf/update-libc.d/avahi-daemon 0.8-4\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/avahi-dbus.conf 0.8-9\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/avahi-daemon 0.8-11\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.23
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/avahi-daemon" ] ; then
	chmod +x "/etc/init.d/avahi-daemon" >/dev/null || true
fi
# End automatically added section
