#!/bin/sh

set -e

# avoid cancelling of "stop" via socket or D-Bus activation
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
    systemctl mask --runtime avahi-daemon.service
fi

# Automatically added by dh_installsystemd/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'avahi-daemon.service' 'avahi-daemon.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/avahi-daemon" ] ; then
	invoke-rc.d --skip-systemd-native avahi-daemon stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.23
dpkg-maintscript-helper rm_conffile /etc/network/if-up.d/avahi-daemon 0.8-4\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/resolvconf/update-libc.d/avahi-daemon 0.8-4\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/avahi-dbus.conf 0.8-9\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/avahi-daemon 0.8-11\~ -- "$@"
# End automatically added section

