#!/bin/sh
set -e

# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/udev/rules.d/70-persistent-ipoib.rules 43.0 rdma-core -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/iwpmd" ]; then
		update-rc.d iwpmd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native iwpmd $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'iwpmd.service' 'rdma-hw.target' 'rdma-ndd.service' >/dev/null || true
	fi
fi
# End automatically added section


if [ "$1" = "configure" ]; then
    # we ship udev rules, so trigger an update. This has to be done after
    # DEBHELPER restarts systemd to get our new service files loaded.
    udevadm trigger --subsystem-match=infiniband --action=change || true
    udevadm trigger --subsystem-match=net --action=change || true
    udevadm trigger --subsystem-match=infiniband_mad --action=change || true
fi
