#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/udev/rules.d/70-persistent-ipoib.rules 43.0 rdma-core -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/iwpmd" ] ; then
	chmod +x "/etc/init.d/iwpmd" >/dev/null || true
fi
# End automatically added section
