#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'iwpmd.service' 'rdma-hw.target' 'rdma-ndd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/iwpmd" ] ; then
	invoke-rc.d --skip-systemd-native iwpmd stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/udev/rules.d/70-persistent-ipoib.rules 43.0 rdma-core -- "$@"
# End automatically added section
