#!/bin/sh
set -e

if dpkg-maintscript-helper supports mv_conffile 2>/dev/null; then
    dpkg-maintscript-helper mv_conffile /etc/carbon/carbon-c-relay.conf /etc/carbon-c-relay.conf 0.40~ -- "$@"
fi

# Automatically added by dh_installinit/13.14.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/carbon-c-relay" ] ; then
	chmod +x "/etc/init.d/carbon-c-relay" >/dev/null || true
fi
# End automatically added section

