#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/jool_siit" ] ; then
	chmod +x "/etc/init.d/jool_siit" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/jool" ] ; then
	chmod +x "/etc/init.d/jool" >/dev/null || true
fi
# End automatically added section
