#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'prometheus-node-exporter-smartmon.timer' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'prometheus-node-exporter-nvme.timer' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'prometheus-node-exporter-mellanox-hca-temp.timer' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'prometheus-node-exporter-ipmitool-sensor.timer' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'prometheus-node-exporter-apt.timer' >/dev/null || true
fi
# End automatically added section
