#! /bin/sh

set -e

case "$1" in
    purge)
		rm -rf /var/cache/apt-cacher /var/log/apt-cacher
	;;
	
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/apt-cacher" ] ; then
	chmod -x "/etc/init.d/apt-cacher" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d apt-cacher remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0


