#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.16
dpkg-maintscript-helper rm_conffile /etc/default/corosync-qdevice 3.0.0-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/corosync-qdevice" ]; then
		update-rc.d corosync-qdevice defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native corosync-qdevice $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'corosync-qdevice.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'corosync-qdevice.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'corosync-qdevice.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'corosync-qdevice.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'corosync-qdevice.service' >/dev/null || true
fi
# End automatically added section
