#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/cloud-init-main" ] ; then
	chmod +x "/etc/init.d/cloud-init-main" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/cloud-init-local" ] ; then
	chmod +x "/etc/init.d/cloud-init-local" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/cloud-config" ] ; then
	chmod +x "/etc/init.d/cloud-config" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/cloud-final" ] ; then
	chmod +x "/etc/init.d/cloud-final" >/dev/null || true
fi
# End automatically added section
