#!/bin/sh
set -e
# Automatically added by dh_icons/13.24.2
if command -v update-icon-caches >/dev/null; then
	update-icon-caches /usr/share/icons/ContrastHigh
fi
# End automatically added section
# Automatically added by dh_installsystemduser/13.24.2
if [ "$1" = "purge" ]; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'ayatana-indicator-keyboard.service' >/dev/null || true
	fi
fi
# End automatically added section
