#!/bin/sh
# postrm script for dhcp-probe
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

PACKAGE="dhcp-probe"
CONFDEST="/etc/$PACKAGE"
UPSTRCONF="/etc/dhcp_probe.cf"

case "$1" in
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
		purge)
			rm -rf "$CONFDEST" "$UPSTRCONF"
			grep /etc/dhcp-probe /var/lib/ucf/hashfile | while IFS=/ read -r _ f; do
				ucf --purge "/$f" || :
			done
			ucf --purge "$UPSTRCONF" || :
		;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit/13.23
if [ "$1" = "remove" ] && [ -x "/etc/init.d/dhcp-probe" ] ; then
	chmod -x "/etc/init.d/dhcp-probe" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d dhcp-probe remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'dhcp-probe.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
