#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/prometheus-node-exporter" ] ; then
	chmod +x "/etc/init.d/prometheus-node-exporter" >/dev/null || true
fi
# End automatically added section
