#!/bin/sh
set -e

# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'msktutil-auto-update.timer' >/dev/null || true
	fi
fi
# End automatically added section


CONFFILE=/etc/default/msktutil

case "$1" in
    remove)
        # Nothing to do here
    ;;

    purge)
        # ignore errors during purge
        set +e
        if [ -x "/usr/bin/ucf" ]; then
            ucf --purge $CONFFILE
        fi
        rm -rf $CONFFILE

        set -e
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
