#!/bin/sh

set -e

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/arc-infosys-ldap" ] ; then
	chmod -x "/etc/init.d/arc-infosys-ldap" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d arc-infosys-ldap remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'arc-infosys-ldap.service' >/dev/null || true
	fi
fi
# End automatically added section


if [ "$1" = "purge" ] ; then
    APP_PROFILE=/etc/apparmor.d/usr.sbin.slapd
    LOCAL_APP_PROFILE=/etc/apparmor.d/local/usr.sbin.slapd

    if [ -r "$LOCAL_APP_PROFILE" ] ; then
	sed '/# AppArmor profile for NorduGrid ARC ARIS START/,/# AppArmor profile for NorduGrid ARC ARIS END/d' -i "$LOCAL_APP_PROFILE"
    fi

    if [ ! -r "$APP_PROFILE" ] ; then
	if [ -r "$LOCAL_APP_PROFILE" ] ; then
	    if [ -z "`sed '/^#/d' $LOCAL_APP_PROFILE`" ] ; then
		rm -f "$LOCAL_APP_PROFILE" || true
	    fi
	fi
	rmdir /etc/apparmor.d/local 2>/dev/null || true
	rmdir /etc/apparmor.d 2>/dev/null || true
    fi

    if [ -r "$APP_PROFILE" ] ; then
	# Reload the profile
	if aa-status --enabled 2>/dev/null ; then
            apparmor_parser -r -T -W "$APP_PROFILE" || true
	fi
    fi
fi
