#!/bin/sh
set -e

# begin-remove-after: released:trixie
# protective diversion of files moved from / to /usr, to avoid file loss.
# Only for upgrades.
if [ "$1" = "upgrade" ] || [ "$1" = "install" ]; then
	dpkg-divert --package samba-ad-dc --no-rename \
		--divert /lib/systemd/system/samba-ad-dc.service.usr-is-merged \
		--add /lib/systemd/system/samba-ad-dc.service
fi
# end-remove-after

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/samba-ad-dc" ] ; then
	chmod +x "/etc/init.d/samba-ad-dc" >/dev/null || true
fi
# End automatically added section


exit 0
