#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          courier-webadmin
# Required-Start:    courier-authdaemon $remote_fs $syslog
# Required-Stop:     courier-authdaemon $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Courier Web Admin
### END INIT INFO

# Author: Ondřej Surý <ondrej@debian.org>
# Modified by Soren Stoutner <soren@debian.org>

DAEMON="courierlogger -pid=/run/courier/webadmin.pid"
DESC="Courier Web Admin"

DO_START=yes
PIDFILE="/run/courier/webadmin.pid"

. /usr/lib/courier/init-d-script-courier

do_start_cmd_override() {
    $DAEMON -start /usr/lib/courier/courier/webmail/webadmin daemon
}

do_stop_cmd_override() {
    $DAEMON -stop
}
