#!/bin/sh

set -e

if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm ]; then
        . /usr/share/dbconfig-common/dpkg/postrm
        dbc_go pnopaste $@
fi

case "$1" in
        purge)
                rm -f /etc/pnopaste/debiandb.pm
				if [ -x /usr/bin/ucf ]; then
	                ucf --debconf-ok --purge /etc/pnopaste/debiandb.pm
				fi
				if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
					. /usr/share/apache2/apache2-maintscript-helper
					apache2_invoke disconf pnopaste.conf
				fi
        ;;
        remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
        *)
                echo "postrm called with unknown argument \`$1'" >&2
                exit 1
esac

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'pnopaste.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
