#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.16
dpkg-maintscript-helper rm_conffile /etc/default/corosync-qnetd 3.0.0-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.16
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/corosync-qnetd" ] ; then
	chmod +x "/etc/init.d/corosync-qnetd" >/dev/null || true
fi
# End automatically added section
