#!/bin/sh
set -e 

case "$1" in
    remove|deconfigure)
      rm -f /var/lib/munge/munge.seed
      rm -rf /run/munge
    ;;

    upgrade)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'munge.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/munge" ] ; then
	invoke-rc.d --skip-systemd-native munge stop || exit 1
fi
# End automatically added section


exit 0
