#!/bin/sh
set -e

if [ "$1" = "purge" ] ; then
	groupdel timekpr 2>/dev/null || true
fi

# Automatically added by dh_installsystemd/13.19
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.19
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'timekpr.service' >/dev/null || true
	fi
fi
# End automatically added section

