#!/bin/sh

set -e

case "$1" in
	configure)
		passwd_version=$(dpkg-query -W -f'${Version}' passwd)
		if dpkg --compare-versions "$passwd_version" ge "1:4.13+dfsg1"
		then
			# --add-subids-for-system was added in bookworm
			# (this is needed for the setup of unshare)
			# Workers running on older than bookworm need
			# to be set up manually for unshare or not run
			# tasks that need unshare
			add_subids="--add-subids-for-system"
		else
			add_subids=""
		fi
		user="debusine-worker"
		group="$user"
		home="/var/lib/debusine/worker"

		# Create debusine-worker user
		if ! getent passwd "$user" > /dev/null 2>&1
		then
			useradd --system \
				$add_subids \
				--comment "Debusine Worker System user" \
				--home-dir "$home" \
				--create-home \
				"$user"
		fi
    
		# Create directories
		directories="/etc/debusine/worker $home /var/log/debusine/worker"

		# shellcheck disable=SC2086
		mkdir -p $directories

		# Change directory permissions
		# shellcheck disable=SC2086
		chown "$user:$group" $directories
	;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'debusine-worker.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'debusine-worker.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'debusine-worker.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'debusine-worker.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'debusine-worker.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
