#!/bin/sh

set -e

if [ "remove" = "${1}" ]; then
    deluser root pkcs11 || true
    deluser pkcsslotd || true
    delgroup --group --only-if-empty pkcs11 || true
fi

# Automatically added by dh_installinit/13.23
if [ "$1" = "remove" ] && [ -x "/etc/init.d/pkcsslotd" ] ; then
	chmod -x "/etc/init.d/pkcsslotd" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d pkcsslotd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.23
dpkg-maintscript-helper mv_conffile /etc/init.d/opencryptoki /etc/init.d/pkcsslotd -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'pkcsslotd.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
