#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.23
dpkg-maintscript-helper mv_conffile /etc/init.d/opencryptoki /etc/init.d/pkcsslotd -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.23
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/pkcsslotd" ] ; then
	chmod +x "/etc/init.d/pkcsslotd" >/dev/null || true
fi
# End automatically added section
