#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'pkcsslotd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/pkcsslotd" ] ; then
	invoke-rc.d --skip-systemd-native pkcsslotd stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.23
dpkg-maintscript-helper mv_conffile /etc/init.d/opencryptoki /etc/init.d/pkcsslotd -- "$@"
# End automatically added section
