#!/bin/sh

set -e

if [ "$1" = purge ]; then
	rm -rf /etc/slony1/ /var/log/slony1/ /var/run/slony1/
fi

# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/slony1" ] ; then
	chmod -x "/etc/init.d/slony1" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d slony1 remove >/dev/null
fi
# End automatically added section

