#!/bin/sh
set -e
# Automatically added by dh_installinit/13.20
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/rbd-target-api" ] ; then
	chmod +x "/etc/init.d/rbd-target-api" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.20
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/rbd-target-gw" ] ; then
	chmod +x "/etc/init.d/rbd-target-gw" >/dev/null || true
fi
# End automatically added section
