#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-container-auditor" ] ; then
	chmod +x "/etc/init.d/swift-container-auditor" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-container-reconciler" ] ; then
	chmod +x "/etc/init.d/swift-container-reconciler" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-container-replicator" ] ; then
	chmod +x "/etc/init.d/swift-container-replicator" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-container-sharder" ] ; then
	chmod +x "/etc/init.d/swift-container-sharder" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-container-sync" ] ; then
	chmod +x "/etc/init.d/swift-container-sync" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-container-updater" ] ; then
	chmod +x "/etc/init.d/swift-container-updater" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-container" ] ; then
	chmod +x "/etc/init.d/swift-container" >/dev/null || true
fi
# End automatically added section
