#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
   # check hostcert is already generated (update vs install)
   if [ ! -f /etc/grid-security/testCA-hostcert.pem ] ; then
       arcctl test-ca init
       arcctl test-ca hostcert
   fi
fi


# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p nordugrid-arc-arex:amd64 
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p nordugrid-arc-arex:amd64  || true
fi

# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/arc-arex" ]; then
		update-rc.d arc-arex defaults-disabled >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native arc-arex $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/arc-arex-ws" ]; then
		update-rc.d arc-arex-ws defaults-disabled >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native arc-arex-ws $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'arc-arex.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'arc-arex.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'arc-arex.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'arc-arex.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'arc-arex.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'arc-arex.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'arc-arex-ws.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'arc-arex-ws.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'arc-arex-ws.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'arc-arex-ws.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'arc-arex-ws.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'arc-arex-ws.service' >/dev/null || true
	fi
fi
# End automatically added section

