#!/bin/sh

set -e

# Service renamed a-rex → arc-arex in version 6.0.0

if [ -n "$2" ] ; then
	if dpkg --compare-versions "$2" "<<" "6.0.0" ; then
		update-rc.d -f a-rex remove >/dev/null
	fi
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/arc-arex" ] ; then
	chmod +x "/etc/init.d/arc-arex" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/arc-arex-ws" ] ; then
	chmod +x "/etc/init.d/arc-arex-ws" >/dev/null || true
fi
# End automatically added section

