#!/bin/sh

set -e

case "$1" in
    configure)
        # begin-remove-after: released:trixie
        # DEP17 P1 M8: Protective diversion for moved file
        if dpkg --compare-versions "$2" lt 1:2.8.2-2~exp1~; then
            dpkg-divert --remove --no-rename --divert /lib/systemd/system/nfs-blkmap.service.usr-is-merged /lib/systemd/system/nfs-blkmap.service
        fi

        # end-remove-after: released:trixie
        ucf --three-way /usr/share/nfs-common/conffiles/idmapd.conf /etc/idmapd.conf
        ucf --three-way /usr/share/nfs-common/conffiles/nfs-common.default /etc/default/nfs-common
        ucf --three-way /usr/share/nfs-common/conffiles/nfs.conf /etc/nfs.conf

        if ! getent passwd statd >/dev/null; then
            adduser --system --home /var/lib/nfs --no-create-home statd
        fi

        chown statd: /var/lib/nfs/sm \
            /var/lib/nfs/sm.bak

	# Create state file if missing, using backup created during
	# preinst if present
	if [ -f /var/lib/nfs/state.bak ]; then
	    mv -n /var/lib/nfs/state.bak /var/lib/nfs/state || rm -f /var/lib/nfs/state.bak
	else
	    [ -e /var/lib/nfs/state ] || touch /var/lib/nfs/state
	fi
	chown statd /var/lib/nfs/state
    ;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/nfs-common" ]; then
		update-rc.d nfs-common defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native nfs-common $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'nfs-blkmap.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'nfs-blkmap.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'nfs-blkmap.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'nfs-blkmap.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'nfs-client.target' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'nfs-client.target'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'nfs-client.target' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'nfs-client.target' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'auth-rpcgss-module.service' 'nfs-blkmap.service' 'nfs-client.target' 'nfs-idmapd.service' 'nfs-utils.service' 'proc-fs-nfsd.mount' 'rpc-gssd.service' 'rpc-statd-notify.service' 'rpc-statd.service' 'rpc-svcgssd.service' >/dev/null || true
	fi
fi
# End automatically added section

