#!/bin/sh

set -e

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/nfs-common" ] ; then
	chmod -x "/etc/init.d/nfs-common" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d nfs-common remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nfs-blkmap.service' 'nfs-client.target' >/dev/null || true
	fi
fi
# End automatically added section


case "$1" in
    purge)
	for FILE in /etc/default/nfs-common /etc/idmapd.conf /etc/nfs.conf; do
	    # Taken from the ucf example postrm
	    for ext in '~' '%' .bak .dpkg-tmp .dpkg-new .dpkg-old .dpkg-dist;  do
		rm -f $FILE$ext
	    done
	    rm -f $FILE
	    if [ -x /usr/bin/ucf ]; then
		ucf --purge $FILE
	    fi
	done
	rm -f /etc/nfs.conf.d/local.conf

	rm -f /var/lib/nfs/state    \
	      /var/lib/nfs/sm/*     \
	      /var/lib/nfs/sm.bak/*
	    
	dpkg-statoverride --remove /sbin/mount.nfs || true
	;;
    # begin-remove-after: released:trixie
    abort-upgrade)
        # DEP17 P1 M8: Protective diversion for moved file
        if dpkg --compare-versions "$2" lt 1:2.8.2-2~exp1~; then
            dpkg-divert --remove --no-rename --divert /lib/systemd/system/nfs-blkmap.service.usr-is-merged /lib/systemd/system/nfs-blkmap.service
        fi
	;;
    # end-remove-after: released:trixie
esac
