#!/bin/sh
#
# postrm script for ffproxy
#

set -e

if [ "$1" = "purge" ]; then
    if which ucf >/dev/null; then
        ucf --purge /etc/ffproxy/ffproxy.conf
    fi
    if which ucfr >/dev/null; then
        ucfr --purge ffproxy /etc/ffproxy/ffproxy.conf
    fi
    if [ -d /etc/ffproxy ]; then
        rm -rf /etc/ffproxy
    fi
fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ffproxy" ] ; then
	chmod -x "/etc/init.d/ffproxy" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d ffproxy remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ffproxy.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
