#!/bin/sh

set -e

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/syncache" ] ; then
	chmod -x "/etc/init.d/syncache" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d syncache remove >/dev/null
fi
# End automatically added section


case "$1" in
	purge)
	# remove user, group, and home directory
	deluser --remove-home syncache >/dev/null 2>&1 || true
	;;

	remove|upgrade|disappearfailed-install|abort-install|abort-upgrade|failed-upgrade)
	;;

	*)
	echo "postrm called with unknown argument \`$1'" >&2;
	;;
esac

exit 0
