#!/bin/sh

set -e

PIDDIR="/var/run/syncache-drb"

case "$1" in
	configure)

	# Create syncache system user
	getent passwd syncache > /dev/null || \
		adduser --quiet --system --home "$PIDDIR" --no-create-home \
		--gecos 'SynCache DRb Server' --group syncache

	;;

	failed-upgrade|abort-upgrade|abort-remove|abort-deconfigure|in-favour|removing)
	;;

	*)
	echo "postinst called with unknown argument \`$1'" >&2;
	exit 1;
	;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/syncache" ]; then
		update-rc.d syncache defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d syncache $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0
