#!/bin/sh

set -e

# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'webfs.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/webfs" ] ; then
	invoke-rc.d --skip-systemd-native webfs stop || exit 1
fi
# End automatically added section


# Older versions of Webfs had an init script that could leave
# the PID-file behind after stopping the service. Correct this
# behaviour.

rm -f /var/run/webfs/webfsd.pid || true
