#!/bin/sh

set -e

case "$1" in
install|upgrade)
	;;

abort-upgrade)
	;;

*)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
	;;
esac

# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/default/xend 4.11.1-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xen/xend-config.sxp 4.11.1-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xen/xend-pci-permissive.sxp 4.11.1-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xen/xend-pci-quirks.sxp 4.11.1-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/xen" ] ; then
	chmod +x "/etc/init.d/xen" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/xendomains" ] ; then
	chmod +x "/etc/init.d/xendomains" >/dev/null || true
fi
# End automatically added section


exit 0
