#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/default/xend 4.11.1-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xen/xend-config.sxp 4.11.1-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xen/xend-pci-permissive.sxp 4.11.1-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xen/xend-pci-quirks.sxp 4.11.1-2\~ -- "$@"
# End automatically added section
