#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.18
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'tuptime-sync.service' 'tuptime-sync.timer' 'tuptime.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.18
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/tuptime" ] ; then
	invoke-rc.d --skip-systemd-native tuptime stop || exit 1
fi
# End automatically added section
