#! /bin/bash
### BEGIN INIT INFO
# Provides:            vrfydmn
# Required-Start:      $remote_fs $syslog
# Required-Stop:       $remote_fs $syslog
# Should-Start:                $local_fs
# Should-Stop:         $local_fs
# Default-Start:       2 3 4 5
# Default-Stop:                0 1 6
# Short-Description:   Start vrfydmn daemon
# Description:         Start up vrfydmn, an anti-spoofing milter
### END INIT INFO

. /lib/lsb/init-functions

NAME=vrfydmn
RUNDIR=/run/${NAME}
SOCKET=local:${RUNDIR}/${NAME}.sock
USER=vrfydmn
GROUP=vrfydmn
PIDFILE=${RUNDIR}/${NAME}.pid
COMMAND="/usr/sbin/${NAME}"

# Include defaults if available
if [ -f /etc/default/${NAME} ] ; then
        . /etc/default/${NAME}
fi

start_daemon() {
       mkdir -p ${RUNDIR}
       chown $USER:$GROUP ${RUNDIR}

        echo "Starting ${NAME}"
        start-stop-daemon --start --pidfile "${PIDFILE}" \
                --exec ${COMMAND} -- -p "${PIDFILE}" -s $SOCKET \
                -u $USER -g $GROUP $EXTRAAFTER
        return $?
}

case "$1" in
	start)
		start_daemon
		exit $?
		;;
	stop)
		stop_daemon
		exit $?
		;;
	restart)
		$0 stop && $0 start
		;;
	reload)
		kill -SIGHUP $(cat ${PIDFILE})
		;;
	force-reload)
		$0 stop && $0 start
		;;
	status)
		status_of_proc -p ${PIDFILE} ${NAME} ${NAME} && exit 0 || exit $?
		;;
	*)
		echo "Usage: ${NAME} {start|stop|restart|reload|status}" >&2
		;;
esac

exit 0
