#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    if ! getent passwd onionbalance >/dev/null; then
        adduser --quiet --system --group --no-create-home --home /nonexistent onionbalance
        adduser onionbalance debian-tor
    fi
fi

chown onionbalance:adm /var/log/onionbalance
# rwxr-s---
chmod 02750 /var/log/onionbalance


# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p onionbalance 
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p onionbalance  || true
fi

# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/onionbalance" ]; then
		update-rc.d onionbalance defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native onionbalance $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'onionbalance.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'onionbalance.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'onionbalance.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'onionbalance.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'onionbalance.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
