#!/bin/sh
set -e
# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/globus-scheduler-event-generator" ] ; then
	chmod -x "/etc/init.d/globus-scheduler-event-generator" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d globus-scheduler-event-generator remove >/dev/null
fi
# End automatically added section
