#!/bin/sh
set -e
# Automatically added by dh_installinit/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/shishi-kdc" ] ; then
	invoke-rc.d --skip-systemd-native shishi-kdc stop || exit 1
fi
# End automatically added section
