#!/bin/sh

# John G. Hasler <john@dhh.gt.org> 1999-2003
# Any possessor of a copy of this program may treat it as if it
# were in the public domain.  I waive all rights.
set -e
if ( [ "$1" = "upgrade" ] || [ "$1" = "remove" ] ) && [ -L /usr/doc/pppconfig ] ; then
	rm -f /usr/doc/pppconfig
fi

# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'dns-clean.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'dns-clean.service' >/dev/null || true
fi
# End automatically added section

