#!/bin/sh
#
# post-removal script for AIDE
# A whole lot of this is "borrowed" from tripwire's postinst
#

set -e

if [ -n "$AIDEDEBUG" ]; then
  printf "now debugging %s %s\n" "$0" "$@"
  set -x
fi

PKGNAME="aide"

# Make sure we should be running...
[ "$1" = "purge" ] || exit 0

UCF="ucf"
UCFR="ucfr"

if command -v ucfq >/dev/null; then
  for file in $(ucfq --with-colons "$PKGNAME" | cut --delimiter=: --fields=1); do
    for ext in '' '~' '%' .bak .dpkg-tmp .dpkg-new .dpkg-old .dpkg-dist .ucf-new .ucf-old .ucf-dist;  do
      rm -f "${file}${ext}"
    done

    if command -v $UCF >/dev/null; then
      $UCF --purge "${file}"
    fi
    if command -v $UCFR >/dev/null; then
      $UCFR --purge "${PKGNAME}" "${file}"
    fi
  done
else
  printf >&2 "ucf no longer installed, not cleaning up\n"
fi

rm -f /var/lib/aide/aide.db /var/lib/aide/aide.db.new
if [ -d "/run/aide" ]; then
    rmdir --ignore-fail-on-non-empty "/run/aide"
fi

# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper mv_conffile /etc/cron.daily/aide /etc/cron.daily/dailyaidecheck 0.18.6-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'dailyaidecheck.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'dailyaidecheck.timer' >/dev/null || true
	fi
fi
# End automatically added section

