#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.15.3
dpkg-maintscript-helper rm_conffile /etc/init/aptitude-robot.conf 1.5.3-1 -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/aptitude-robot" ]; then
		update-rc.d aptitude-robot defaults >/dev/null || exit 1
	fi
fi
# End automatically added section
