#!/bin/sh
set -e
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/aptitude-robot" ] ; then
	chmod -x "/etc/init.d/aptitude-robot" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d aptitude-robot remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.15.3
dpkg-maintscript-helper rm_conffile /etc/init/aptitude-robot.conf 1.5.3-1 -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
