#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/endlessh" ] ; then
	chmod +x "/etc/init.d/endlessh" >/dev/null || true
fi
# End automatically added section
