#!/bin/sh
# -*- mode: Shell-Script -*-
# complete dpkg-maintscript-helper operations

set -e

if [ "$1" = "configure" ]; then

    if [ -h /etc/init.d/thin.dpkg-backup ]; then
	mv -f "/etc/init.d/thin.dpkg-backup" "/etc/init.d/thin.dpkg-bak"
    fi
    if [ -h /etc/init.d/thin.dpkg-remove ]; then
	rm -f /etc/init.d/thin.dpkg-remove
    fi

    if [ -e /etc/init.d/thin1.8.dpkg-remove ]; then
	rm -f /etc/init.d/thin1.8.dpkg-remove
    fi
    if [ -e /etc/init.d/thin1.8.dpkg-backup ]; then
	mv -f /etc/init.d/thin1.8.dpkg-backup /etc/init.d/thin1.8.dpkg-bak
    fi

fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/thin" ]; then
		update-rc.d thin defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native thin $_dh_action || exit 1
	fi
fi
# End automatically added section

