#!/bin/sh
# -*- mode: Shell-Script -*-
# complete dpkg-maintscript-helper operations

set -e

if [ "$1" = "abort-install" -o "$1" = "abort-upgrade" ]; then
    if [ -h /etc/init.d/thin.dpkg-remove ]; then
	mv /etc/init.d/thin.dpkg-remove /etc/init.d/thin
    fi
    if [ -h /etc/init.d/thin.dpkg-backup ]; then
	mv /etc/init.d/thin.dpkg-backup /etc/init.d/thin
    fi

    if [ -e /etc/init.d/thin1.8.dpkg-remove ]; then
	mv /etc/init.d/thin1.8.dpkg-remove /etc/init.d/thin1.8
    fi
    if [ -e /etc/init.d/thin1.8.dpkg-backup ]; then
	mv /etc/init.d/thin1.8.dpkg-backup /etc/init.d/thin1.8
    fi
fi

if [ "$1" = "purge" ]; then
    rm -f /etc/init.d/thin1.8.dpkg-backup /etc/init.d/thin1.8.dpkg-remove /etc/init.d/thin1.8.dpkg-bak
    rm -f /etc/init.d/thin.dpkg-backup /etc/init.d/thin.dpkg-remove /etc/init.d/thin.dpkg-bak
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/thin" ] ; then
	chmod -x "/etc/init.d/thin" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d thin remove >/dev/null
fi
# End automatically added section

