#!/bin/sh
#
# Post-installation script for Onionprobe
#

# Parameters
# User name should begin with an underscore, see
# https://www.debian.org/doc/debian-policy/ch-opersys.html#introduction
NAME="onionprobe"
USERNAME="_$NAME"

# Ensure that the scripts abort in case of any errors
set -e

# Ensure a dedicated user for running the system-wide service
# Needs --force-badname to allow user names with underscores
adduser --home /var/lib/$NAME --system --group --force-badname $USERNAME

# Include automatic generated code by debhelper(7)

# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p onionprobe 
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p onionprobe  || true
fi

if command -v py3compile >/dev/null 2>&1; then
	py3compile -p onionprobe /usr/share/onionprobe
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p onionprobe /usr/share/onionprobe || true
fi

# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/onionprobe" ]; then
		update-rc.d onionprobe defaults-disabled >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'onionprobe.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'onionprobe.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'onionprobe.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'onionprobe.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'onionprobe.service' >/dev/null || true
fi
# End automatically added section

