#!/bin/sh
# postrm script for dlt

set -e

# Source the debconf shell library.
. /usr/share/debconf/confmodule

[ -z "$DLT_USER" ] && DLT_USER=_dlt
[ -z "$DLT_GROUP" ] && DLT_GROUP=_dlt

case "$1" in
    purge)

    if getent passwd $DLT_USER >/dev/null; then
        if [ -x "`which deluser 2>/dev/null`" ]; then
            deluser --system $DLT_USER
        else
            echo >&2 "Not removing \`_dlt' system account" \
              "because deluser command was not found."
        fi
    fi
    if getent group $DLT_GROUP >/dev/null; then
        if [ -x "`which delgroup 2>/dev/null`" ]; then
            delgroup --system $DLT_GROUP
        else
            echo >&2 "Not removing \`_dlt' system group" \
              "because delgroup command was not found."
        fi
    fi
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac


# Automatically added by dh_installsystemd/13.20
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'dlt.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
