#!/bin/sh
# postinst script for dlt

set -e

# Source the debconf shell library.
. /usr/share/debconf/confmodule

[ -z "$DLT_USER" ] && DLT_USER=_dlt
[ -z "$DLT_GROUP" ] && DLT_GROUP=_dlt

case "$1" in
    configure)

        if ! getent group $DLT_GROUP >/dev/null; then
            addgroup --force-badname --quiet --system $DLT_GROUP
        fi

        if ! getent passwd $DLT_USER; then
            adduser --force-badname \
	            --quiet \
                    --system \
                    --ingroup $DLT_GROUP \
                    --no-create-home \
                    --home /nonexistent \
                    --disabled-password \
                    $DLT_USER
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac


# Automatically added by dh_installsystemd/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'dlt.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'dlt.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'dlt.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'dlt.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'dlt.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
