#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'click-system-hooks.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_click/UNDECLARED
if [ "${1}" = "remove" ] || [ "${1}" = "purge" ] ; then
	if command -v click >/dev/null 2>&1; then
		click hook remove click-desktop
	fi
fi
# End automatically added section
