#!/bin/sh

set -e

# Automatically added by dh_installinit/13.23
if [ "$1" = "remove" ] && [ -x "/etc/init.d/uptimed" ] ; then
	chmod -x "/etc/init.d/uptimed" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d uptimed remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.23
dpkg-maintscript-helper rm_conffile /etc/init.d/uptimed.sh 1:0.3.16-3.1 -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'uptimed.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.23
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


if [ "$1" = "purge" ]; then
	if [ -f /var/spool/uptimed/records ]; then
		echo -n "Deleting uptime record database..."
		rm -f /var/spool/uptimed/records
		echo "done."
	fi
	rm -f /var/spool/uptimed/records.old
	rm -f /var/spool/uptimed/bootid
	if [ -d /var/spool/uptimed ]; then
		rmdir /var/spool/uptimed || true
	fi
fi
