#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'uptimed.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/uptimed" ] ; then
	invoke-rc.d --skip-systemd-native uptimed stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.23
dpkg-maintscript-helper rm_conffile /etc/init.d/uptimed.sh 1:0.3.16-3.1 -- "$@"
# End automatically added section
