#! /bin/sh

set -e

if [ "$1" = "purge" ]; then
	# delete dangling symlinks
	test -d /etc/munin/plugins/ && for plugin in $(find /etc/munin/plugins/ -type l); do
		if [ ! -e "$(readlink "$plugin")" ]; then
			rm "$plugin"
		fi
	done

	rm -f /var/log/munin/munin-node.log*
	rm -f /var/log/munin/munin-node-configure.log*
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/munin-node" ] ; then
	chmod -x "/etc/init.d/munin-node" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d munin-node remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/init/munin-node.conf 2.0.49-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'munin-node.service' >/dev/null || true
	fi
fi
# End automatically added section

