#!/bin/sh

set -e

init_eh () {
	:
}

if [ -x /etc/init.d/dbus ]; then
    invoke-rc.d dbus force-reload || true
fi

# Automatically added by dh_installinit/13.14.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/pommed" ]; then
		update-rc.d pommed defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d pommed $_dh_action || init_eh
	fi
fi
# End automatically added section

