#!/bin/sh
set -e
# Automatically added by dh_installinit/13.14.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/pommed" ] ; then
	chmod +x "/etc/init.d/pommed" >/dev/null || true
fi
# End automatically added section
