#!/bin/sh

set -e

init_eh () {
	:
}

# Automatically added by dh_installinit/13.14.1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/pommed" ] ; then
	invoke-rc.d pommed stop || init_eh
fi
# End automatically added section

