#!/bin/sh

CONFIGFILE=/etc/default/postsrsd
set -e
. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then
	if [ ! -f /etc/postsrsd.secret ]; then
		echo "postsrsd: Generating initial /etc/postsrsd.secret" >&2
		( umask 0077 ; dd if=/dev/urandom bs=24 count=1 2>/dev/null | base64 -w0 > /etc/postsrsd.secret )
	fi

	# We'll only write the configured domain to the config file if it doesn't
	# exist yet, or we're called by dpkg-reconfigure.
	db_get postsrsd/domain; DOMAIN="$RET"

	if [ ! -e $CONFIGFILE ]; then
		cp -a -f /usr/share/postsrsd/postsrsd.template $CONFIGFILE.tmp
		# strip comment from SRS_DOMAIN and write configured domain to config file (but only if the domain is not empty)
		if [ ! -z "$DOMAIN" ]; then
			sed -i "s/^#SRS_DOMAIN=.*/SRS_DOMAIN=$DOMAIN/" $CONFIGFILE.tmp
		fi
		mv -f $CONFIGFILE.tmp $CONFIGFILE
	fi

	if [ "$DEBCONF_RECONFIGURE" = "1" -a ! -z "$DOMAIN" ]; then
		cp -a -f $CONFIGFILE $CONFIGFILE.tmp
		sed -i "s/^\( *\|#\)SRS_DOMAIN=.*/SRS_DOMAIN=$DOMAIN/" $CONFIGFILE.tmp
		mv -f $CONFIGFILE.tmp $CONFIGFILE
	fi

	# Create user
	if ! getent passwd postsrsd > /dev/null; then
		adduser --quiet --system --group --no-create-home --home /var/lib/postsrsd postsrsd
	fi
fi

# Stop communcation with debconf, as the daemon might get confused with the extra file
# descriptor if we use an init system that doesn't close it.
db_stop

# Automatically added by dh_apparmor/3.1.7-1
if [ "$1" = "configure" ]; then
    APP_PROFILE="/etc/apparmor.d/usr.sbin.postsrsd"
    if [ -f "$APP_PROFILE" ]; then
        # Add the local/ include
        LOCAL_APP_PROFILE="/etc/apparmor.d/local/usr.sbin.postsrsd"

        test -e "$LOCAL_APP_PROFILE" || {
            mkdir -p `dirname "$LOCAL_APP_PROFILE"`
            install --mode 644 /dev/null "$LOCAL_APP_PROFILE"
        }

        # Reload the profile, including any abstraction updates
        if aa-enabled --quiet 2>/dev/null; then
            apparmor_parser -r -T -W "$APP_PROFILE" || true
        fi
    fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.19
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/postsrsd" ]; then
		update-rc.d postsrsd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native postsrsd $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.19
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'postsrsd.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'postsrsd.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'postsrsd.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'postsrsd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.19
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'postsrsd.service' >/dev/null || true
	fi
fi
# End automatically added section

