#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
	rm -f /etc/postsrsd.secret
	rm -f /etc/default/postsrsd

	if getent passwd postsrsd >/dev/null; then
		if [ -x "$(command -v deluser)" ]; then
			deluser --system postsrsd || echo "Could not remove postsrsd user."
		fi
	fi

	if getent group postsrsd >/dev/null; then
		if [ -x "$(command -v delgroup)" ]; then
			delgroup --system postsrsd || echo "Could not remove postsrsd group."
		fi
	fi

fi

# Automatically added by dh_installinit/13.19
if [ "$1" = "remove" ] && [ -x "/etc/init.d/postsrsd" ] ; then
	chmod -x "/etc/init.d/postsrsd" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d postsrsd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.19
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.19
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'postsrsd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.19
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_apparmor/3.1.7-1
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.sbin.postsrsd" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.sbin.postsrsd" || true
    rm -f "/etc/apparmor.d/force-complain/usr.sbin.postsrsd" || true
    rm -f "/etc/apparmor.d/local/usr.sbin.postsrsd" || true
    rm -f /var/cache/apparmor/*/"usr.sbin.postsrsd" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section

