#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.19
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'postsrsd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.19
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/postsrsd" ] ; then
	invoke-rc.d --skip-systemd-native postsrsd stop || exit 1
fi
# End automatically added section
