#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'pvpgn.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/pvpgn" ] ; then
	invoke-rc.d --skip-systemd-native pvpgn stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/pvpgn/ad.conf 1.99.7.2.1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pvpgn/bnetd_default_user.cdb 1.99.7.2.1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pvpgn/bnhelp.conf 1.99.7.2.1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pvpgn/bnmotd.txt 1.99.7.2.1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pvpgn/d2server.ini 1.99.7.2.1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pvpgn/news.txt 1.99.7.2.1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pvpgn/sql_DB_layout2.conf 1.99.7.2.1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pvpgn/versioncheck.conf 1.99.7.2.1\~ -- "$@"
# End automatically added section
