#!/bin/sh
set -e

if [ "$1" = purge ]; then
	rm -rf /var/run/uuidd
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/uuidd" ] ; then
	chmod -x "/etc/init.d/uuidd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d uuidd remove >/dev/null
fi
# End automatically added section

