#!/bin/sh
set -e
# Automatically added by dh_installinit/12.1.1
if [ -x "/etc/init.d/nagzillad" ] && [ "$1" = remove ]; then
	invoke-rc.d nagzillad stop || exit 1
fi
# End automatically added section
