#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/speechd-up" ]; then
		update-rc.d speechd-up defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native speechd-up $_dh_action || true
	fi
fi
# End automatically added section
