#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.9
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/speechd-up" ] ; then
	invoke-rc.d --skip-systemd-native speechd-up stop || true
fi
# End automatically added section
