#!/bin/sh
set -e
# Automatically added by dh_installinit/13.16
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/miredo-server" ] ; then
	chmod +x "/etc/init.d/miredo-server" >/dev/null || true
fi
# End automatically added section
