#!/bin/sh
set -e
# Automatically added by dh_installinit/13.16
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/miredo-server" ] ; then
	invoke-rc.d --skip-systemd-native miredo-server stop || exit 1
fi
# End automatically added section
