#!/bin/sh

set -e

if [ "$1" = configure ]; then
  if ! getent passwd radvd >/dev/null; then
    adduser --quiet --system --no-create-home --home /run/radvd radvd
  fi
  for i in /run/radvd; do
    if dpkg-statoverride --list $i >/dev/null; then
      dpkg-statoverride --remove $i
    fi
  done
fi

# Recover from incorrect init.d script headers in version 1:1.3-1 and earlier
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" le "1:1.3-1" \
   && [ -f /etc/rcS.d/S[0-9][0-9]radvd ] ; then
  update-rc.d -f radvd remove
fi

# Automatically added by dh_systemd_enable/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'radvd.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'radvd.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'radvd.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'radvd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/radvd" ]; then
		update-rc.d radvd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d radvd $_dh_action || true
	fi
fi
# End automatically added section

