#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'macsmc-battery-charge-control-end-threshold.path' 'macsmc-battery-charge-control-end-threshold.service' >/dev/null || true
fi
# End automatically added section
