#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/plymouth" ] ; then
	chmod +x "/etc/init.d/plymouth" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/plymouth-log" ] ; then
	chmod +x "/etc/init.d/plymouth-log" >/dev/null || true
fi
# End automatically added section
