#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/courier" ] ; then
	chmod +x "/etc/init.d/courier" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/courierfilter" ] ; then
	chmod +x "/etc/init.d/courierfilter" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/courier-mta" ] ; then
	chmod +x "/etc/init.d/courier-mta" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/courier-mta-ssl" ] ; then
	chmod +x "/etc/init.d/courier-mta-ssl" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/courier-msa" ] ; then
	chmod +x "/etc/init.d/courier-msa" >/dev/null || true
fi
# End automatically added section
