#!/bin/sh
set -e
# Automatically added by dh_installinit/13.20
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/darkstat" ] ; then
	chmod +x "/etc/init.d/darkstat" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'darkstat.service' >/dev/null || true
fi
# End automatically added section
