#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/wide-dhcpv6-server" ] ; then
	invoke-rc.d --skip-systemd-native wide-dhcpv6-server stop || true
fi
# End automatically added section
