#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          kxd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: key exchange daemon
# Description:       kxd is a program that serves keys to authorized clients.
### END INIT INFO

# Author: Maximiliano Curia <maxy@debian.org>

DESC="key exchange daemon"
DAEMON=/usr/bin/kxd
START_ARGS="--background --make-pidfile"
