#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'gnome-remote-desktop-configuration.service' 'gnome-remote-desktop.service' >/dev/null || true
fi
# End automatically added section
