#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    rm -f /etc/ipvsadm.rules
fi

# Automatically added by dh_installinit/13.23
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ipvsadm" ] ; then
	chmod -x "/etc/init.d/ipvsadm" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d ipvsadm remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ipvsadm.service' >/dev/null || true
	fi
fi
# End automatically added section
	
