#!/bin/sh
# postinst script for zeroc-icegrid
set -e

if [ "$1" = "configure" ]; then
    for i in icegrid icegrid/node1 icegrid/registry
    do
        if ! dpkg-statoverride --list /var/lib/ice/$i >/dev/null; then
    	   dpkg-statoverride --update --add ice adm 0770 /var/lib/ice/$i >/dev/null 2>/dev/null || true
        fi
    done
fi

# Automatically added by dh_systemd_start/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'icegridnode.service' 'icegridregistry.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'icegridregistry.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'icegridregistry.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'icegridregistry.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'icegridregistry.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'icegridregistry.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'icegridnode.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'icegridnode.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'icegridnode.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'icegridnode.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'icegridnode.service' >/dev/null || true
fi
# End automatically added section


exit 0
