#!/bin/sh
# postrm script for zeroc-icegrid
set -e

if [ "$1" = "purge" ]; then
    # We remove /var/lib/ice/icegrid
    rm -rf /var/lib/ice/icegrid

    # Remove /var/lib/ice/icegrid
    for i in icegrid icegrid/node1 icegrid/registry
    do
        dpkg-statoverride --remove /var/lib/ice/$i >/dev/null 2>/dev/null || true
    done
fi

# Automatically added by dh_systemd_start/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'icegridnode.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'icegridregistry.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
