#!/bin/sh
set -e
# Automatically added by dh_systemd_start/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'icegridnode.service' 'icegridregistry.service' >/dev/null || true
fi
# End automatically added section
