#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.13
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.13
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ipa-healthcheck.service' 'ipa-healthcheck.timer' >/dev/null || true
	fi
fi
# End automatically added section
