#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    rmdir --ignore-fail-on-non-empty /etc/rplay
fi

# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/rplay" ] ; then
	chmod -x "/etc/init.d/rplay" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d rplay remove >/dev/null
fi
# End automatically added section

