#!/bin/sh

set -e

pkg=rplayd

if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/$pkg ]; then
  rm -f /usr/doc/$pkg
fi

# Automatically added by dh_installinit/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/rplay" ] ; then
	invoke-rc.d --skip-systemd-native rplay stop || exit 1
fi
# End automatically added section

