#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/default/ircd-hybrid 1:8.2.30\+dfsg.1-1\~ ircd-hybrid -- "$@"
# End automatically added section
