#!/bin/sh
set -e

# We may have been unable to stop tgtd during prerm, so at least create the
# pidfile for the initscript to continue working.
if [ ! -f /run/tgtd.pid ] && pidof /usr/sbin/tgtd >/dev/null; then
	pidof -s /usr/sbin/tgtd >/run/tgt.pid
fi

# Automatically added by dh_installinit/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/tgt" ]; then
		update-rc.d tgt defaults >/dev/null
		invoke-rc.d --skip-systemd-native tgt start || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'tgt.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'tgt.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'tgt.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'tgt.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		deb-systemd-invoke start 'tgt.service' >/dev/null || true
	fi
fi
# End automatically added section

