#!/bin/sh
set -e

# Stop tgtd if no initiators are currently connected (package removal is
# handled by dh below). This is a bit racey but simpler and more robust than
# setting tgtd into and out of offline mode.
if [ -x /etc/init.d/tgt ]; then
	if ! tgtadm --mode target --op show | grep -q Connection; then
		invoke-rc.d tgt stop
	fi
fi

# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'tgt.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/tgt" ] ; then
	invoke-rc.d --skip-systemd-native tgt stop || exit 1
fi
# End automatically added section

