#!/bin/sh
set -e

# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/tlp -- "$@"
dpkg-maintscript-helper rm_conffile /etc/acpi/events/thinkpad-radiosw -- "$@"
dpkg-maintscript-helper rm_conffile /etc/acpi/thinkpad-radiosw.sh -- "$@"
dpkg-maintscript-helper mv_conffile /etc/default/tlp /etc/tlp.conf -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/tlp" ]; then
		update-rc.d tlp defaults 98 01 >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'tlp.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'tlp.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'tlp.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'tlp.service' >/dev/null || true
	fi
fi
# End automatically added section


SERVICES2MASK="systemd-rfkill.service systemd-rfkill.socket"

case "$1" in
    configure)
        # Mask conflicting systemd services
        for svc in $SERVICES2MASK; do
            deb-systemd-helper mask $svc 2> /dev/null || true
        done
        ;;
esac
