#!/bin/sh
set -e

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/tlp" ] ; then
	chmod -x "/etc/init.d/tlp" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d tlp remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/tlp -- "$@"
dpkg-maintscript-helper rm_conffile /etc/acpi/events/thinkpad-radiosw -- "$@"
dpkg-maintscript-helper rm_conffile /etc/acpi/thinkpad-radiosw.sh -- "$@"
dpkg-maintscript-helper mv_conffile /etc/default/tlp /etc/tlp.conf -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'tlp.service' >/dev/null || true
	fi
fi
# End automatically added section


SERVICES2MASK="systemd-rfkill.service systemd-rfkill.socket"

case "$1" in
    remove|purge)
        # Unmask conflicting systemd services
        for svc in $SERVICES2MASK; do
            deb-systemd-helper unmask $svc 2> /dev/null || true
        done
        ;;
esac
