#! /bin/sh

set -e

if [ "$1" = "purge" ]; then
    rm -f  "/etc/zm/core.php" || true
    echo "
Reminder: to completely remove \"zoneminder\" it may be necessary
 * to delete database using the following sample command:
        sudo mysqladmin --defaults-file=/etc/mysql/debian.cnf -f drop zm
 * to delete remaining data files in "/var/cache/zoneminder".
"
fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/zoneminder" ] ; then
	chmod -x "/etc/init.d/zoneminder" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d zoneminder remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/zm/apache.conf 1.28.1-5\~ -- "$@"
dpkg-maintscript-helper dir_to_symlink /usr/share/zoneminder/www/api/lib/Cake /usr/share/php/Cake 1.30.4\+dfsg1-4\~ -- "$@"
dpkg-maintscript-helper symlink_to_dir /usr/share/zoneminder/www/api/lib/Cake /usr/share/php/Cake 1.36.5\+dfsg1-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'zoneminder.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_apache2/UNDECLARED
if [ "$1" = "purge" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in zoneminder  ; do
				apache2_invoke disconf $conf  || exit 1
			done
		fi
	fi
fi
# End automatically added section

