#!/bin/sh
set -e
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/lcd4linux" ] ; then
	chmod -x "/etc/init.d/lcd4linux" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d lcd4linux remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.15.3
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'lcd4linux.service' >/dev/null || true
	fi
fi
# End automatically added section
