#! /bin/sh
# preinst script for quota
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>

case "$1" in
    upgrade)
	echo "$2" > /var/run/quota.upgrade
    ;;

    install)
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

# Automatically added by dh_installinit/13.23
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/quota" ] ; then
	chmod +x "/etc/init.d/quota" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.23
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/quotarpc" ] ; then
	chmod +x "/etc/init.d/quotarpc" >/dev/null || true
fi
# End automatically added section


exit 0


