#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.23
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.sssd.infopipe.conf 2.8.2-3\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'sssd-ifp.service' >/dev/null || true
	fi
fi
# End automatically added section
