#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'sssd-ifp.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.23
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.sssd.infopipe.conf 2.8.2-3\~ -- "$@"
# End automatically added section
