#!/bin/sh
set -e
# Automatically added by dh_installinit/13.1
if [ "$1" = "purge" ] ; then
	update-rc.d cgroupfs-mount remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.1
dpkg-maintscript-helper rm_conffile /etc/init/cgroupfs-mount.conf 1.4\~ -- "$@"
# End automatically added section
