#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.1
dpkg-maintscript-helper rm_conffile /etc/init/cgroupfs-mount.conf 1.4\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/cgroupfs-mount" ]; then
		update-rc.d cgroupfs-mount defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native cgroupfs-mount $_dh_action || exit 1
	fi
fi
# End automatically added section
