#!/bin/sh
set -e
# Automatically added by dh_installinit/13.1
if [ -x "/etc/init.d/cgroupfs-mount" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native cgroupfs-mount stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.1
dpkg-maintscript-helper rm_conffile /etc/init/cgroupfs-mount.conf 1.4\~ -- "$@"
# End automatically added section
