#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.15.3
dpkg-maintscript-helper rm_conffile /etc/init.d/ltsp-client-setup 5.5.4-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/ltsp-client-setup 5.5.4-3\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/ltsp-client-core" ] ; then
	chmod +x "/etc/init.d/ltsp-client-core" >/dev/null || true
fi
# End automatically added section
