#!/bin/sh
#
# $Id: whereami.postinst,v 1.6 2004/02/10 20:52:04 andrew Exp $
#

set -e

if [ "$1" = "configure" ]; then
    # CFG=/etc/whereami/whereami.conf

    if [ ! -d /var/lib/whereami ] ; then
      # Create new state files location then move and link files
      mkdir /var/lib/whereami
      cd /etc/whereami
      mv iam iwas* whereiam.sh /var/lib/whereami
      ln -s /var/lib/whereami/iam
      ln -s /var/lib/whereami/iwas
      ln -s /var/lib/whereami/whereiam.sh
    fi
fi

# Automatically added by dh_installinit/13.22
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/whereami" ]; then
		update-rc.d whereami defaults 35 65 >/dev/null
		invoke-rc.d --skip-systemd-native whereami start || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.22
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'whereami.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'whereami.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'whereami.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'whereami.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.22
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'whereami.service' >/dev/null || true
	fi
fi
# End automatically added section

