#!/bin/sh
#  Pre-removal script for whereami.
# $Id: whereami.prerm,v 1.4 2005/05/15 09:18:01 andrew Exp $

set -e

case "$1" in
    remove|deconfigure)
	set +e
	[ -L /usr/sbin/whereami ] && rm -f /usr/sbin/whereami
  (
    for DDD in /etc/whereami /var/lib/whereami ; do
      cd "$DDD" || continue
      for F in whereiam.sh iam iwas* whereami.started dhclient3.* iwlist.*; do
        [ -f "$F" ] && rm -f "$F"
      done
    done
  )
	;;
esac

# Automatically added by dh_installsystemd/13.22
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'whereami.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.22
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/whereami" ] ; then
	invoke-rc.d --skip-systemd-native whereami stop || exit 1
fi
# End automatically added section

