#!/bin/sh
set -e
# Automatically added by dh_installinit/13.2
if [ -x "/etc/init.d/spamass-milter" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native spamass-milter stop || exit 1
fi
# End automatically added section
