#!/bin/sh

set -e

# Remove exabgp.env when run in purge mode
case "$1" in
    purge)
        for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist;  do
            rm -f /etc/exabgp/exabgp.env$ext
        done

        # remove the configuration file itself
        rm -f /etc/exabgp/exabgp.env

        # and finally clear it out from the ucf database
        if which ucf >/dev/null; then
            ucf --purge /etc/exabgp/exabgp.env
        fi
        if which ucfr >/dev/null; then
            ucfr --purge exabgp /etc/exabgp/exabgp.env
        fi
        ;;
esac

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/exabgp" ] ; then
	chmod -x "/etc/init.d/exabgp" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d exabgp remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'exabgp.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
