#!/bin/sh
# prerm script for icecc

set -e

# Automatically added by dh_installinit/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/iceccd" ] ; then
	invoke-rc.d --skip-systemd-native iceccd stop || exit 1
fi
# End automatically added section


if [ -x "/etc/init.d/icecc-scheduler" ]; then
        invoke-rc.d icecc-scheduler stop || exit $?
fi

exit 0
