#!/bin/sh

set -e

if [ "$1" = purge ]; then
    rm -rf /var/log/conmux
fi

# Automatically added by dh_installdeb/13.11.8
dpkg-maintscript-helper rm_conffile /etc/init/conmux.conf 0.12.0-3 -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.11.8
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.8
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'conmux.service' >/dev/null || true
	fi
fi
# End automatically added section

