#!/bin/sh

set -e

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ipband" ] ; then
	chmod -x "/etc/init.d/ipband" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d ipband remove >/dev/null
fi
# End automatically added section


if [ "$1" = "purge" ]; then
    [ -d /var/run/ipband ] && rm -rf /var/run/ipband || true
fi
