#! /bin/sh
# postrm script for ejabberd
#
# see: dh_installdeb(1)

set -e

EJABBERD_YML_TARGET=/etc/ejabberd/ejabberd.yml
EJABBERDCTL_CFG_TARGET=/etc/default/ejabberd

if [ -f /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
fi

case "$1" in
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade)
		;;

	purge|disappear)
		if command -v ucf > /dev/null ; then
			ucf --purge "$EJABBERD_YML_TARGET"
			ucf --purge "$EJABBERDCTL_CFG_TARGET"
		fi
		if command -v ucfr > /dev/null ; then
			ucfr --purge ejabberd "$EJABBERD_YML_TARGET"
			ucfr --purge ejabberd "$EJABBERDCTL_CFG_TARGET"
		fi
		rm -f "$EJABBERD_YML_TARGET"
		rm -f "$EJABBERDCTL_CFG_TARGET"
		rm -f /etc/ejabberd/ejabberd.pem
		rm -f /etc/ejabberd/ejabberd.yml.ucf-old
		rm -f /etc/ejabberd/ejabberd.yml.ucf-dist
		rm -f /etc/default/ejabberd.ucf-old
		rm -f /etc/default/ejabberd.ucf-dist
		rm -rf /var/log/ejabberd /var/lib/ejabberd
		rm -rf /var/run/ejabberd || true
		rm -f /root/.rnd || true
		if command -v deluser > /dev/null ; then
			deluser ejabberd || true
			delgroup ejabberd || true
		fi
		;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ejabberd" ] ; then
	chmod -x "/etc/init.d/ejabberd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d ejabberd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/apparmor.d/usr.sbin.ejabberdctl -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ejabberd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

