#!/bin/sh

# Exit immediately if a command produces an error.
set -e

del_override() {
    if dpkg-statoverride --list $1 >/dev/null; then
	dpkg-statoverride --remove $1
    fi
}

if [ "$1" = "purge" ]; then
    # Remove generated TLS certificate
    rm -f /etc/courier/pop3d.pem

    del_override /etc/courier/pop3d.cnf
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/courier-pop-ssl" ] ; then
	chmod -x "/etc/init.d/courier-pop-ssl" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d courier-pop-ssl remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/courier-pop" ] ; then
	chmod -x "/etc/init.d/courier-pop" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d courier-pop remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'courier-pop-ssl.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'courier-pop.service' >/dev/null || true
	fi
fi
# End automatically added section

