#!/bin/sh

set -e

case "$1" in
    remove)
        [ -d /run/nut ] && rmdir --ignore-fail-on-non-empty /run/nut >/dev/null 2>&1
    ;;
    purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/nut-server" ] ; then
	chmod -x "/etc/init.d/nut-server" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d nut-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nut-driver-enumerator.path' 'nut-driver-enumerator.service' 'nut-driver.target' 'nut-server.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
