#!/bin/sh
set -e
# Automatically added by dh_runit/2.10.3
# Unlike postrm, I can be sure, that runit-helper is present on
# postinst.
NAME='mini-httpd' ENABLE='yes' ONUPGRADE='restart' /lib/runit-helper/runit-helper prerm "$@"
# End automatically added section
