#!/bin/sh
set -e
# Automatically added by dh_icons/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if command -v update-icon-caches >/dev/null; then
		update-icon-caches /usr/share/icons/onedriver-128.png /usr/share/icons/onedriver.png /usr/share/icons/onedriver.svg
	fi
fi
# End automatically added section
