#!/bin/sh
set -e
# Automatically added by dh_icons/13.20
if command -v update-icon-caches >/dev/null; then
	update-icon-caches /usr/share/icons/onedriver-128.png /usr/share/icons/onedriver.png /usr/share/icons/onedriver.svg
fi
# End automatically added section
