#!/bin/sh
set -e;

PACKAGE=sendmail-bin;

if [ "$1" = "remove" ]; then

	if dpkg-statoverride --list /usr/libexec/sendmail/sendmail >/dev/null ; then
		dpkg-statoverride --remove /usr/libexec/sendmail/sendmail
	fi
	if dpkg-statoverride --list /usr/libexec/sendmail/mailstats >/dev/null ; then
		dpkg-statoverride --remove /usr/libexec/sendmail/mailstats
	fi

fi

if [ "$1" = "purge" ]; then

		# If postrm is called *AND* there are no files, exit quickly
		# (This is a *GROSS* hack... beter use the test below)
		#if [ ! -s `echo "$0" | sed -e 's/postrm$/list/'` ]; then
		#		echo "Purging replaced package $PACKAGE, nothing to do...";
		#		exit 0;
		#		fi;

		# We're *really* purging; neither sendmail nor sendmail-tls
		# is currently installed
		if [ -f /usr/libexec/sendmail/sendmail ]; then
			echo "Purging replaced package $PACKAGE, nothing to do...";
			exit 0;
			fi;

		# Currently, dh_installdebconf doesn't do db_stop... ensure it is done!
		if [ -e /usr/share/debconf/confmodule ]; then
			# Source debconf library.
			. /usr/share/debconf/confmodule;
			# Make sure we're done
			#db_stop;
			# Remove my changes to the db.
			db_purge;
			fi;

		rm -f /etc/mail/sendmail.cf.old
		rm -f /etc/mail/submit.cf.old

fi

# Automatically added by dh_installinit/13.23
if [ "$1" = "remove" ] && [ -x "/etc/init.d/sendmail" ] ; then
	chmod -x "/etc/init.d/sendmail" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d sendmail remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'sendmail.service' >/dev/null || true
	fi
fi
# End automatically added section

