#!/bin/sh

### BEGIN INIT INFO
# Provides:          debug-me
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: debug-me server
# Description: Starts debug-me in server mode
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=debug-me
DESC="debug-me server"
DAEMON="/usr/bin/debug-me"
PIDFILE=/var/run/"$NAME".pid

test -x /usr/bin/debug-me || exit 0

. /lib/lsb/init-functions

# Parameters to pass to debug-me.
# This can be overridden in /etc/default/debug-me
DAEMON_PARAMS="--server /var/log/debug-me/ --delete-old-logs"
if [ -e /etc/default/debug-me ]; then
	. /etc/default/debug-me
fi

case "$1" in
	start)
		log_daemon_msg "Starting $DESC" "$NAME"
		start-stop-daemon --start --quiet --oknodo \
			--background --no-close \
			--pidfile "$PIDFILE" --make-pidfile \
			--chuid _debug-me:_debug-me \
			--exec "$DAEMON" -- $DAEMON_PARAMS \
			> /var/log/debug-me.log
		log_end_msg $?
	;;
	stop)
		log_daemon_msg "Stopping $DESC" "$NAME"
		killproc -p "$PIDFILE" "$DAEMON"
		RETVAL=$?
		[ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
		log_end_msg $RETVAL
		;;
	restart|reload|force-reload)
		log_daemon_msg "Restarting $DESC" "$NAME"
		$0 stop
		$0 start
		;;
	status)
		status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
		;;
	*)
		log_action_msg "Usage: /etc/init.d/debug-me {start|stop|status|restart|reload|force-reload}"
		exit 2
		;;
esac
exit 0
