#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/init.d/haveged 1.9.19-6\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/haveged" ] ; then
	chmod +x "/etc/init.d/haveged" >/dev/null || true
fi
# End automatically added section
