#!/bin/sh

set -e

# only stop firewall when uif is going to be removed
if [ "$1" = "remove" -o "$1" = "deconfigure" ]; then
	invoke-rc.d uif stop
else
	echo "Please restart uif manually using: invoke-rc.d uif restart"
fi

# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/uif" ] ; then
	invoke-rc.d --skip-systemd-native uif stop || exit 1
fi
# End automatically added section


exit 0
