#!/bin/sh

set -e

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/acpi-support" ] ; then
	chmod -x "/etc/init.d/acpi-support" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d acpi-support remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'acpi-support.service' >/dev/null || true
	fi
fi
# End automatically added section


if [ "$1" = "purge" ] ; then
	rm -f /etc/acpi/resume.d/13-855-resolution-set.sh.obsolete
	rm -f /etc/acpi/resume.d/49-855-resolution-set.sh.obsolete
	rm -f /etc/modprobe.d/ibm_acpi.modprobe
fi

