#!/bin/sh
set -e

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/jetty9" ] ; then
	chmod -x "/etc/init.d/jetty9" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d jetty9 remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'jetty9.service' 'jetty9.timer' >/dev/null || true
	fi
fi
# End automatically added section


# Remove cached files
rm -rf /var/cache/jetty9/*

case "$1" in
    remove)
        rmdir --ignore-fail-on-non-empty \
            /var/lib/jetty9/webapps/root \
            /var/lib/jetty9/webapps \
            /var/lib/jetty9 || true

        if [ -d "/var/cache/jetty9" ] ; then
            rm -rf /var/cache/jetty9
        fi
    ;;

    purge)
        # Remove log files (don't remove everything under /var/lib/jetty
        # because there might be user-installed webapps)
        rm -rf /var/log/jetty9
        if [ -d "/var/lib/jetty9" ] ; then
            rmdir --ignore-fail-on-non-empty /var/lib/jetty9 || true
        fi
        rmdir --ignore-fail-on-non-empty /etc/jetty9/start.d /etc/jetty9 || true

        # clean up /etc/authbind after conffiles have been removed
        rmdir --ignore-fail-on-non-empty /etc/authbind/byuid /etc/authbind || true
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
