#!/bin/sh
set -e

case "$1" in
    remove)
        # Remove auth for jetty to open privileged ports via authbind.
        JETTY_USER="jetty"
        JETTY_UID="`id -u $JETTY_USER`"
        if [ -f "/etc/authbind/byuid/$JETTY_UID" ]; then
                rm -f /etc/authbind/byuid/$JETTY_UID
        fi

        # Remove the default page
        if cmp --silent /var/lib/jetty9/webapps/root/index.html /usr/share/jetty9/default-root/index.html
        then
                rm /var/lib/jetty9/webapps/root/index.html
        fi
        if cmp --silent /var/lib/jetty9/webapps/root/jetty_banner.gif /usr/share/jetty9/default-root/jetty_banner.gif
        then
                rm /var/lib/jetty9/webapps/root/jetty_banner.gif
        fi
    ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'jetty9.service' 'jetty9.timer' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/jetty9" ] ; then
	invoke-rc.d --skip-systemd-native jetty9 stop || exit 1
fi
# End automatically added section

