#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-account-auditor" ] ; then
	chmod +x "/etc/init.d/swift-account-auditor" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-account-reaper" ] ; then
	chmod +x "/etc/init.d/swift-account-reaper" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-account-replicator" ] ; then
	chmod +x "/etc/init.d/swift-account-replicator" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-account" ] ; then
	chmod +x "/etc/init.d/swift-account" >/dev/null || true
fi
# End automatically added section
