#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/mistral-engine" ] ; then
	chmod -x "/etc/init.d/mistral-engine" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d mistral-engine remove >/dev/null
fi
# End automatically added section
