#!/bin/sh

set -e
if [ "$1" = purge ]; then
	rm -rf /var/lib/samba/winbindd_privileged/
	rm -f \
		/var/cache/samba/netsamlogon_cache.tdb \
		/var/lib/samba/winbindd_cache.tdb \
		/var/log/samba/log.winbind* \
		/var/log/samba/log.wb* \
		/run/samba/winbindd.pid
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/winbind" ] ; then
	chmod -x "/etc/init.d/winbind" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d winbind remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/logrotate.d/winbind 2:4.19.4\+dfsg-3\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'winbind.service' >/dev/null || true
	fi
fi
# End automatically added section

