#!/bin/sh

set -e 

# Remove generated default file.
if [ "$1" = "purge" ]; then
	rm -f /etc/default/watchdog
fi

# Not automatically added by dh_installinit (--noscripts)
if [ "$1" = "purge" ] ; then
	update-rc.d watchdog remove >/dev/null
	update-rc.d wd_keepalive remove >/dev/null
fi
# End manually added section

# Automatically added by dh_installsystemd/13.20
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'watchdog.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.20
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


