#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'jabberd-c2s.service' 'jabberd-router.service' 'jabberd-s2s.service' 'jabberd-sm.service' 'jabberd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/jabberd2" ] ; then
	invoke-rc.d --skip-systemd-native jabberd2 stop || exit 1
fi
# End automatically added section
