#!/bin/sh

set -e

if test "$1" = "configure" -o "$1" = "reconfigure" ; then

    test -r /etc/default/voms && . /etc/default/voms

    if test -z "$VOMS_USER" -o "$VOMS_USER" = "voms" ; then

	getent group voms > /dev/null || \
	    addgroup --quiet --system voms

	getent passwd voms > /dev/null || \
	    adduser --quiet --system --home /etc/voms --shell /bin/false \
	    --ingroup voms --disabled-password --disabled-login \
	    --gecos "VOMS Server Account" voms

	chown voms:voms /var/log/voms

    fi

fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/voms" ]; then
		update-rc.d voms defaults-disabled >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native voms $_dh_action || exit 1
	fi
fi
# End automatically added section

