#!/bin/sh

set -e

case "$1" in
purge)
  rm -rf /etc/iptables/ipsets
  ;;
esac

# To register the drop-in's removal
if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload >/dev/null || true
fi

if [ -L /etc/systemd/system/ipset.service ]; then
  rm /etc/systemd/system/ipset.service
fi

# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/systemd/system/netfilter-persistent.service.d/ipset.conf -- "$@"
# End automatically added section
# Automatically added by dh_installdebconf/13.24.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

