#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.9
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/welcome2l" ] ; then
	invoke-rc.d --skip-systemd-native welcome2l stop || exit 1
fi
# End automatically added section
