#!/bin/sh

set -e

if [ "$1" = "purge" ]; then

	# Handle the /run/fwknop directory that contains pid and digest files
	if [ -d /run/fwknop ]; then
	    find /run/fwknop/ -type f -delete
	    rmdir /run/fwknop
	fi

fi

# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/fwknop-server" ] ; then
	chmod -x "/etc/init.d/fwknop-server" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d fwknop-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.20
dpkg-maintscript-helper rm_conffile /etc/init/fwknop-server.conf 2.6.9-2\~ fwknop-server -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'fwknop-server.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0;
