#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'fwknop-server.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/fwknop-server" ] ; then
	invoke-rc.d --skip-systemd-native fwknop-server stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.20
dpkg-maintscript-helper rm_conffile /etc/init/fwknop-server.conf 2.6.9-2\~ fwknop-server -- "$@"
# End automatically added section
