#!/bin/sh
set -e

# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'pqconnect-server.service' >/dev/null || true
	fi
fi
# End automatically added section


if [ x"$1" = "xpurge" ]; then
  echo 'purging /etc/pqconnect directory, including configuration and keys'
  rm -rf /etc/pqconnect
fi
