#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/uml-utilities" ] ; then
	invoke-rc.d --skip-systemd-native uml-utilities stop || exit 1
fi
# End automatically added section
