#!/bin/sh

set -e

case "$1" in
remove|upgrade|failed-upgrade|abort-install|abort-upgrade)
    ;;
purge|disappear)
    rm -rf /var/log/inspircd.log* || true
    ;;
*)
    echo "postrm called with unknown argument '$1'" >&2
    exit 1
    ;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/inspircd" ] ; then
	chmod -x "/etc/init.d/inspircd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d inspircd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'inspircd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/4.1.0~beta5-5
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.sbin.inspircd" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.sbin.inspircd" || true
    rm -f "/etc/apparmor.d/force-complain/usr.sbin.inspircd" || true
    rm -f "/etc/apparmor.d/local/usr.sbin.inspircd" || true
    rm -f /var/cache/apparmor/*/"usr.sbin.inspircd" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section

exit 0
