#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/inspircd" ] ; then
	chmod +x "/etc/init.d/inspircd" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -x "/etc/init.d/inspircd" ] ; then
	invoke-rc.d --skip-systemd-native inspircd stop || exit 1
fi
# End automatically added section
