#!/bin/sh
set -e
# Automatically added by dh_installinit/13.3.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/dphys-config" ]; then
		update-rc.d dphys-config defaults >/dev/null || exit 1
	fi
fi
# End automatically added section
