#!/bin/sh

# exit if any errors occur
set -e

# Automatically added by dh_installinit/13.11.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/distributed-net" ] ; then
	chmod -x "/etc/init.d/distributed-net" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d distributed-net remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.11.3
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


# Remove the configuration, logs and buffers
if [ "$1" = "purge" ] ; then
	rm -f /var/log/distributed-net*.log*
	rm -rf /var/lib/distributed-net
	rm -f /etc/distributed-net.conf
fi
