#!/bin/sh

# Make sure that we exit on error
set -e

# Automatically added by dh_installinit/13.11.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/distributed-net" ] ; then
	invoke-rc.d --skip-systemd-native distributed-net stop || exit 1
fi
# End automatically added section

