#!/bin/sh
set -e
# Automatically added by dh_installinit/13.15.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/redsocks" ] ; then
	chmod +x "/etc/init.d/redsocks" >/dev/null || true
fi
# End automatically added section
