#!/bin/sh
set -e
# Automatically added by dh_installinit/13.15.2
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/redsocks" ] ; then
	invoke-rc.d redsocks stop || exit 1
fi
# End automatically added section
