#!/bin/sh

set -e

if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ] ; then
	# create rabbitmq group
	if ! getent group rabbitmq >/dev/null; then
		addgroup --system rabbitmq
	fi

	# create rabbitmq user
	if ! getent passwd rabbitmq >/dev/null; then
		adduser --system \
		--ingroup rabbitmq \
		--home /var/lib/rabbitmq \
                --no-create-home \
		--gecos "RabbitMQ messaging server" \
                --disabled-login rabbitmq
	fi

	mkdir -p /etc/rabbitmq
	chown rabbitmq:rabbitmq /etc/rabbitmq
	if [ -r /usr/share/rabbitmq/rabbitmq-env.conf ] && ! [ -e /etc/rabbitmq/rabbitmq-env.conf ] ; then
		install -m 0644 -o rabbitmq -g rabbitmq /usr/share/rabbitmq/rabbitmq-env.conf /etc/rabbitmq/rabbitmq-env.conf
	fi
	if [ -f /etc/rabbitmq/enabled_plugins ] ; then
		chown rabbitmq:rabbitmq /etc/rabbitmq/enabled_plugins
	fi

	mkdir -p /var/lib/rabbitmq/mnesia
	chmod 750 /var/lib/rabbitmq/mnesia
	chmod -R o-rwx,g-w /var/lib/rabbitmq/mnesia

	# We generate the erlang cookie by ourselves, just to make sure we don't
	# leave the job to erlang that doesn't do it with enough entropy.
	if ! [ -e /var/lib/rabbitmq/.erlang.cookie ] ; then
		OLD_UMASK=$(umask)
		umask 077; openssl rand -base64 -out /var/lib/rabbitmq/.erlang.cookie 42
		umask ${OLD_UMASK}
	else
		# This matches an Erlang generated cookie file: 20 upper case chars
		if grep -q -E '^[A-Z]{20}$' /var/lib/rabbitmq/.erlang.cookie ; then
			OLD_UMASK=$(umask)
			umask 077; openssl rand -base64 -out /var/lib/rabbitmq/.erlang.cookie 42
			umask ${OLD_UMASK}
			if [ ""$(ps --no-headers -o comm 1) = "systemd" ] ; then
				if systemctl is-active --quiet rabbitmq-server.service ; then
					systemctl restart rabbitmq-server.service
				fi
			fi
		fi
	fi
	chmod 0400 /var/lib/rabbitmq/.erlang.cookie

	chown -R rabbitmq:rabbitmq /var/lib/rabbitmq
	chown -R rabbitmq:adm /var/log/rabbitmq
fi

# Automatically added by dh_systemd_enable/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'rabbitmq-server.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'rabbitmq-server.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'rabbitmq-server.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'rabbitmq-server.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/rabbitmq-server" ]; then
		update-rc.d rabbitmq-server defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d rabbitmq-server $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0
