#!/bin/bash

set -e

# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper mv_conffile /etc/spampd.conf /etc/spampd.sa.cf 2.62-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/spampd 2.62-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/spampd" ] ; then
	chmod +x "/etc/init.d/spampd" >/dev/null || true
fi
# End automatically added section


