#!/bin/bash

set -e

handle_init_errs ()
{
	RET=$?
	if [ "$RET" = "6" ]; then
		return 0
	else
		exit $RET
	fi
	set -e
}

# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'spampd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/spampd" ] ; then
	invoke-rc.d --skip-systemd-native spampd stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper mv_conffile /etc/spampd.conf /etc/spampd.sa.cf 2.62-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/spampd 2.62-2\~ -- "$@"
# End automatically added section


case "$1" in
	purge)
		deluser spampd > /dev/null 2>&1 || true
		delgroup spampd > /dev/null 2>&1 || true
		;;
	*)
		;;
esac
