#!/bin/sh
set -e
# Automatically added by dh_installinit/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/edac" ] ; then
	invoke-rc.d edac stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.23
dpkg-maintscript-helper rm_conffile /etc/udev/rules.d/z60_edac-utils.rules 0.16-1\~ edac-utils -- "$@"
# End automatically added section
