#!/bin/sh
# preinst script for dicod
#
# see: dh_installdeb(1)

set -e

case "$1" in
  install|upgrade)
    adduser --quiet --system --home /var/lib/dicod --no-create-home \
            --group dicod || true
  ;;

  abort-upgrade)
  ;;

  *)
      echo "preinst called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/dicod" ] ; then
	chmod +x "/etc/init.d/dicod" >/dev/null || true
fi
# End automatically added section


exit 0
