#!/bin/sh
set -e

# remove pid and pipe file only when being removed
case "$1" in
  "remove"| "purge"| "abort-install")
    # make sure pipe and pid file are removed
    rm -f /var/run/snmptrapfmt.p /var/run/snmptrapfmt.pid
    ;;
  *)
    ;;
esac

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/snmptrapfmt" ] ; then
	chmod -x "/etc/init.d/snmptrapfmt" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d snmptrapfmt remove >/dev/null
fi
# End automatically added section

