#!/bin/sh
#
# postinst script for incron
#

set -e

case "$1" in
    configure|reconfigure)
        # add group for incrontabs
        getent group incron > /dev/null 2>&1 || addgroup --system incron

        if ! dpkg-statoverride --list /usr/bin/incrontab > /dev/null ; then
            dpkg-statoverride --update --add root incron 2755 /usr/bin/incrontab
        fi

        if ! dpkg-statoverride --list /var/spool/incron > /dev/null ; then
            dpkg-statoverride --update --add root incron 1731 /var/spool/incron
        fi

        for f in /etc/incron.allow /etc/incron.deny ; do
            if ! dpkg-statoverride --list $f > /dev/null ; then
                dpkg-statoverride --update --add root incron 640 $f
            fi
        done
        ;;
esac

# Automatically added by dh_installinit/13.11.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/incron" ]; then
		update-rc.d incron defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native incron $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'incron.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'incron.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'incron.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'incron.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'incron.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
