#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    rm -rf /var/games/armagetronad
    rmdir --ignore-fail-on-non-empty /var/games
fi

# Automatically added by dh_installinit/13.14.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/armagetronad-dedicated" ] ; then
	chmod -x "/etc/init.d/armagetronad-dedicated" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d armagetronad-dedicated remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'armagetronad-dedicated.service' >/dev/null || true
	fi
fi
# End automatically added section

