#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.14.1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'armagetronad-dedicated.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.14.1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/armagetronad-dedicated" ] ; then
	invoke-rc.d --skip-systemd-native armagetronad-dedicated stop || exit 1
fi
# End automatically added section
