#!/bin/sh
set -e

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'jetty12.service' 'jetty12.timer' >/dev/null || true
	fi
fi
# End automatically added section


# Remove cached files
rm -rf /var/cache/jetty12/*

case "$1" in
    remove)
        rmdir --ignore-fail-on-non-empty \
            /var/lib/jetty12/webapps/root \
            /var/lib/jetty12/webapps \
            /var/lib/jetty12 || true

        if [ -d "/var/cache/jetty12" ] ; then
            rm -rf /var/cache/jetty12
        fi
    ;;

    purge)
        # Remove log files (don't remove everything under /var/lib/jetty
        # because there might be user-installed webapps)
        rm -rf /var/log/jetty12
        if [ -d "/var/lib/jetty12" ] ; then
            rmdir --ignore-fail-on-non-empty /var/lib/jetty12 || true
        fi
        rmdir --ignore-fail-on-non-empty /etc/jetty12/start.d /etc/jetty12 || true
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
