#!/bin/sh
set -e

JETTY_USER=jetty
JETTY_GROUP=jetty

case "$1" in
    configure)
	# Install the default page if no root context exist
	if [ ! -f /var/lib/jetty12/webapps/root.war ]; then
		mkdir -p /var/lib/jetty12/webapps/root
		if [ -z "$(ls -A /var/lib/jetty12/webapps/root)" ]; then
			cp /usr/share/jetty12/default-root/* /var/lib/jetty12/webapps/root
		fi
	fi

	if ! id jetty > /dev/null 2>&1 ; then
	    adduser --system --home /usr/share/jetty12 --no-create-home \
		--group --disabled-password --shell /bin/false \
		$JETTY_USER
	fi
	chown -Rh jetty:adm /var/cache/jetty12 /var/log/jetty12 /var/lib/jetty12
	chmod 750 /var/log/jetty12
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
	echo "$0 called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'jetty12.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'jetty12.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'jetty12.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'jetty12.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'jetty12.timer' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'jetty12.timer'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'jetty12.timer' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'jetty12.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'jetty12.service' 'jetty12.timer' >/dev/null || true
	fi
fi
# End automatically added section

