#!/bin/sh
set -e

case "$1" in
    remove)
        # Remove the default page
        if cmp --silent /var/lib/jetty12/webapps/root/index.html /usr/share/jetty12/default-root/index.html
        then
                rm /var/lib/jetty12/webapps/root/index.html
        fi
        if cmp --silent /var/lib/jetty12/webapps/root/jetty_banner.gif /usr/share/jetty12/default-root/jetty_banner.gif
        then
                rm /var/lib/jetty12/webapps/root/jetty_banner.gif
        fi
    ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'jetty12.service' 'jetty12.timer' >/dev/null || true
fi
# End automatically added section

