#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'aminer.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.15.3
dpkg-maintscript-helper rm_conffile /etc/aminer/config.py.template 2.0.1-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init/aminer.conf 2.0.1-1\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/aminer/conf-available/generic/EximParsingModel.py /etc/aminer/conf-available/generic/EximGenericParsingModel.py 2.2.0-1\~ -- "$@"
# End automatically added section

# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1; then
	py3clean -p logdata-anomaly-miner 
else
	dpkg -L logdata-anomaly-miner | sed -En -e '/^(.*)\/(.+)\.py$/s,,rm "\1/__pycache__/\2".*,e'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section
