#!/bin/sh
set -e

case "$1" in
configure)
	# Create ulog group if there isn't one already.
	if ! getent group ulog >/dev/null; then
		addgroup --system ulog >/dev/null
	fi

	# Create ulog user if there isn't one already.
	if ! getent passwd ulog >/dev/null; then
		adduser --system --ingroup ulog --shell /bin/false \
			--home /var/log/ulog --no-create-home ulog >/dev/null
	fi

	# Create /var/log/ulog if there isn't one already, and set ownership and
	# permissions on it.
	if [ ! -d /var/log/ulog ]; then
		install -d -o ulog -g adm -m u=rwx,g=rx,o= /var/log/ulog
	fi
	;;
esac

# Automatically added by dh_installtmpfiles/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "$(command -v systemd-tmpfiles)" ]; then
		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create ulogd2.conf || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/ulogd2" ]; then
		update-rc.d ulogd2 defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native ulogd2 $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'ulogd2.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'ulogd2.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'ulogd2.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'ulogd2.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'ulogd2.service' >/dev/null || true
	fi
fi
# End automatically added section

