#!/bin/sh
set -e

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ulogd2" ] ; then
	chmod -x "/etc/init.d/ulogd2" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d ulogd2 remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ulogd2.service' >/dev/null || true
	fi
fi
# End automatically added section


# Clean up the log directory
if [ "$1" = "purge" ]; then
	if [ -d /var/log/ulog ]; then
		rm -rf /var/log/ulog
	fi
fi
