#!/bin/sh

set -e

if [ "${1}" = purge ] ; then
	rm -f /var/log/ceilometer/ceilometer-agent-central.log*
	[ -d /var/log/ceilometer ] && rmdir --ignore-fail-on-non-empty /var/log/ceilometer
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ceilometer-agent-central" ] ; then
	chmod -x "/etc/init.d/ceilometer-agent-central" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d ceilometer-agent-central remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ceilometer-agent-central.service' >/dev/null || true
	fi
fi
# End automatically added section

