#!/bin/sh
set -e

case "$1" in
  purge)
  rm -f /etc/udev/rules.d/70-persistent-*.rules
  rmdir --ignore-fail-on-non-empty /etc/udev/rules.d/ 2> /dev/null || true
  rm -f /lib/udev/hwdb.bin
  rm -f /var/log/udev
  ;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/eudev" ] ; then
	chmod -x "/etc/init.d/eudev" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d eudev remove >/dev/null
fi
# End automatically added section

