#!/bin/sh
set -e
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/switchconf" ] ; then
	chmod -x "/etc/init.d/switchconf" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d switchconf remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.15.3
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'switchconf.service' >/dev/null || true
	fi
fi
# End automatically added section
