#!/bin/sh

#
# preinst script for sympa
#

set -e

case "$1" in
  install|upgrade)
    if dpkg --compare-versions "$2" "lt" "6.1.22~dfsg-1"; then
        # delete sympa facility before managing it as a conffile (#774877)
        rm -f /etc/sympa/facility
    fi
  ;;
esac

# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/sympa/sympa/sympa.conf 6.2.16\~dfsg-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/sympa/sympa.conf-smime.in 6.2.16\~dfsg-4\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/sympa" ] ; then
	chmod +x "/etc/init.d/sympa" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'sympa-bounced.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'sympa-archived.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'sympa-bulk.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'sympa-task_manager.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'wwsympa.service' 'wwsympa.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'sympasoap.service' 'sympasoap.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'sympasoap.socket' >/dev/null || true
fi
# End automatically added section


exit 0
