#!/bin/sh

#
# prerm script for sympa
#

set -e

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi

if [ -f /usr/share/dbconfig-common/dpkg/prerm ]; then
    . /usr/share/dbconfig-common/dpkg/prerm
    dbc_go sympa $@
fi

# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'wwsympa.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'sympa.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/sympa" ] ; then
	invoke-rc.d --skip-systemd-native sympa stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/sympa/sympa/sympa.conf 6.2.16\~dfsg-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/sympa/sympa.conf-smime.in 6.2.16\~dfsg-4\~ -- "$@"
# End automatically added section


exit 0
