#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.22
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.GeoClue2.Agent.conf 2.7.0-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.GeoClue2.conf 2.7.0-3\~ -- "$@"
# End automatically added section
