#!/bin/sh

set -e

if [ "${1}" = "configure" ] ; then
	[ -f "/etc/default/ceph" ] && . /etc/default/ceph
	[ -z "$SERVER_USER" ] && SERVER_USER=ceph
	[ -z "$SERVER_GROUP" ] && SERVER_GROUP=ceph
	if ! dpkg-statoverride --list /var/lib/ceph/radosgw >/dev/null; then
		chown $SERVER_USER:$SERVER_GROUP /var/lib/ceph/radosgw
	fi
fi
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/radosgw" ]; then
		update-rc.d radosgw defaults >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'ceph-radosgw.target' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'ceph-radosgw.target'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'ceph-radosgw.target' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'ceph-radosgw.target' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		deb-systemd-invoke start 'ceph-radosgw.target' >/dev/null || true
	fi
fi
# End automatically added section


exit 0


