#!/bin/sh
# vim: set noet ts=8:

set -e

case "$1" in
    remove)
	invoke-rc.d radosgw stop || {
	    RESULT=$?
	    if [ $RESULT != 100 ]; then
		exit $RESULT
	    fi
	}
	;;

    *)
	;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'ceph-radosgw.target' >/dev/null || true
fi
# End automatically added section


exit 0
