#! /bin/sh
set -e

# Automatically added by dh_installdeb/13.15.3
dpkg-maintscript-helper rm_conffile /etc/default/fusioninventory-agent 1:2.4-1 fusioninventory-agent -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.daily/fusioninventory-agent 1:2.4-1 fusioninventory-agent -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/fusioninventory-agent 1:2.4-1 fusioninventory-agent -- "$@"
dpkg-maintscript-helper rm_conffile /etc/logrotate.d/fusioninventory-agent 1:2.4-1 fusioninventory-agent -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.weekly/fusioninventory-agent 1:2.5.1-1 fusioninventory-agent -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'fusioninventory-agent.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'fusioninventory-agent.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'fusioninventory-agent.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'fusioninventory-agent.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'fusioninventory-agent.service' >/dev/null || true
	fi
fi
# End automatically added section


case "$1" in
  configure)
    [ -d "/etc/fusioninventory" ] || mkdir "/etc/fusioninventory"
    [ -d "/etc/fusioninventory/conf.d" ] || mkdir "/etc/fusioninventory/conf.d"
    for conf in agent inventory-server-plugin ssl-server-plugin server-test-plugin \
        proxy-server-plugin proxy2-server-plugin
    do
        ucf /usr/share/fusioninventory/etc/$conf.cfg /etc/fusioninventory/$conf.cfg
        ucfr fusioninventory-agent /etc/fusioninventory/$conf.cfg
    done
    ;;
esac

exit 0
