#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.15.3
dpkg-maintscript-helper rm_conffile /etc/default/fusioninventory-agent 1:2.4-1 fusioninventory-agent -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.daily/fusioninventory-agent 1:2.4-1 fusioninventory-agent -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/fusioninventory-agent 1:2.4-1 fusioninventory-agent -- "$@"
dpkg-maintscript-helper rm_conffile /etc/logrotate.d/fusioninventory-agent 1:2.4-1 fusioninventory-agent -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.weekly/fusioninventory-agent 1:2.5.1-1 fusioninventory-agent -- "$@"
# End automatically added section
