#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/init/php8.4-fpm.conf 7.4.3-4\~ php8.4-fpm -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/php8.4-fpm" ] ; then
	chmod +x "/etc/init.d/php8.4-fpm" >/dev/null || true
fi
# End automatically added section
