#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
  CONFFILES="dovecot.conf \
    conf.d/10-auth.conf \
    conf.d/10-logging.conf \
    conf.d/10-mail.conf \
    conf.d/10-master.conf \
    conf.d/10-metrics.conf \
    conf.d/10-ssl.conf \
    conf.d/15-lda.conf \
    conf.d/15-mailboxes.conf \
    conf.d/30-dict-server.conf \
    conf.d/90-acl.conf \
    conf.d/90-fts.conf \
    conf.d/90-quota.conf \
    conf.d/auth-deny.conf.ext \
    conf.d/auth-master.conf.ext \
    conf.d/auth-oauth2.conf.ext \
    conf.d/auth-passwdfile.conf.ext \
    conf.d/auth-sql.conf.ext \
    conf.d/auth-static.conf.ext \
    conf.d/auth-system.conf.ext"

  OLD_CONFFILES="conf.d/auth-vpopmail.conf.ext \
    dovecot-dict-auth.conf.ext \
    dovecot-dict-sql.conf.ext \
    dovecot-sql.conf.ext \
    conf.d/10-director.conf \
    conf.d/10-tcpwrapper.conf \
    conf.d/90-plugin.conf"

  ## Users
  #

  adduser --system --group --home /usr/lib/dovecot --gecos "Dovecot mail server" \
          --no-create-home --disabled-password --quiet dovecot || true

  adduser --system --group --home /nonexistent --no-create-home --gecos "Dovecot login user" \
          --disabled-password --quiet dovenull || true

  for conffile in $CONFFILES ; do
    # Tell ucf that the file in /usr/share/dovecot is the latest
    # maintainer version, and let it handle how to manage the real
    # configuration file in /etc/dovecot.
    ucf --three-way "/usr/share/dovecot/$conffile" "/etc/dovecot/$conffile"
    ucfr dovecot-core "/etc/dovecot/$conffile"
    if [ "$conffile" != "dovecot.conf" ] && [ -f "/etc/dovecot/$conffile" ] &&
		[ "$(echo "$conffile" | cut -b -7)" != "conf.d/" ]; then
      chmod 0640 "/etc/dovecot/$conffile"
      chgrp dovecot "/etc/dovecot/$conffile"
    fi
  done

  for oldconffile in $OLD_CONFFILES ; do
    if [ -e "/etc/dovecot/$oldconffile" ]; then
      modified=$(ucfq -w /etc/dovecot/$oldconffile | cut -d: -f4)
      if [ "$modified" = "No" ]; then
	echo "Removing unmodified obsolete configuration file '/etc/dovecot/$oldconffile'"
	rm -f "/etc/dovecot/$oldconffile"
      else
	echo "Locally modified configuration file '/etc/dovecot/$oldconffile' is obsolete. Please remove."
      fi
      ucf --purge "/etc/dovecot/$oldconffile"
      ucfr --purge dovecot-core "/etc/dovecot/$oldconffile"
    fi
  done


  if ! dpkg-statoverride --list /etc/dovecot/private >/dev/null; then
    dpkg-statoverride --quiet --update --add root root 0700 /etc/dovecot/private
  fi

  # SSL configuration
  # Use the ssl-cert-snakeoil certificate in the following cases:
  # - On new installations
  if [ -z "$2" ]; then
    if [ ! -e /etc/dovecot/private/dovecot.key ] && \
       [ ! -e /etc/dovecot/private/dovecot.pem ] && \
       [ -e /etc/ssl/certs/ssl-cert-snakeoil.pem ] && \
       [ -e /etc/ssl/private/ssl-cert-snakeoil.key ]; then
      ln -s /etc/ssl/certs/ssl-cert-snakeoil.pem /etc/dovecot/private/dovecot.pem
      ln -s /etc/ssl/private/ssl-cert-snakeoil.key /etc/dovecot/private/dovecot.key
    fi
  fi
fi

if [ "$1" = "triggered" ]; then
    if [ -x "/etc/init.d/dovecot" ]; then
        invoke-rc.d dovecot restart
    fi
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/dovecot" ]; then
		update-rc.d dovecot defaults 20 >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native dovecot $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'dovecot.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'dovecot.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'dovecot.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'dovecot.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'dovecot.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'dovecot.socket'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'dovecot.socket' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'dovecot.socket'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'dovecot.socket' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'dovecot.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'dovecot.socket' >/dev/null || true
	fi
fi
# End automatically added section

