#!/bin/sh
set -e
# Automatically added by dh_installinit/13.14.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/secnet" ] ; then
	chmod -x "/etc/init.d/secnet" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d secnet remove >/dev/null
fi
# End automatically added section
