#!/bin/sh
set -e
# Automatically added by dh_installinit/13.14.1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/secnet" ] ; then
	invoke-rc.d --skip-systemd-native secnet stop || exit 1
fi
# End automatically added section
