#!/bin/sh

set -e

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'fsidd.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'fsidd.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'fsidd.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'fsidd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'nfs-server.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'nfs-server.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'nfs-server.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'nfs-server.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'fsidd.service' 'nfs-mountd.service' 'nfs-server.service' 'nfsdcld.service' >/dev/null || true
	fi
fi
# End automatically added section


case "$1" in
    configure)
	ucf --three-way /usr/share/nfs-kernel-server/conffiles/etc.exports /etc/exports
	ucf --three-way /usr/share/nfs-kernel-server/conffiles/nfs-kernel-server.default /etc/default/nfs-kernel-server

	# Create state files if missing, using backups created during
	# preinst if present
	for f in /var/lib/nfs/etab  \
		 /var/lib/nfs/rmtab; do
	    if [ -f "$f.bak" ]; then
		mv -n "$f.bak" "$f" || rm -f "$f.bak"
	    else
		[ -e "$f" ] || touch "$f"
	    fi
	done

	update-rc.d nfs-kernel-server defaults 20 80 >/dev/null

	# Remove leftover /fsid.sock file on upgrade (Cf. #1041147)
	if dpkg --compare-versions "$2" lt 1:2.6.3-2~; then
		if [ -S /fsid.sock ]; then
			rm -f /fsid.sock
		fi
	fi
    ;;
esac

act="restart"
[ "$1:$2" = "configure:" ] && act="start"
invoke-rc.d nfs-kernel-server $act || echo "Failed to ${act} nfs-kernel-server, ignoring."
