#! /bin/sh
# preinst script for tenshi

set -e

case "$1" in
    install)
    ;;

    upgrade)
        if [ -x "/etc/init.d/tenshi" ]; then
            if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                    invoke-rc.d tenshi stop || exit $?
            else
                    /etc/init.d/tenshi stop || exit $?
            fi
         fi
    ;;

    abort-upgrade)
    ;;   

*)
    echo "preinst called with unknown argument '$1'" >&2
    exit 1
    ;;
esac

# Automatically added by dh_installinit/13.16
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/tenshi" ] ; then
	chmod +x "/etc/init.d/tenshi" >/dev/null || true
fi
# End automatically added section


exit 0
