#!/bin/sh
set -e
# Automatically added by dh_installinit/13.14.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/opa-fm" ] ; then
	chmod -x "/etc/init.d/opa-fm" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d opa-fm remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'opa-fm.service' >/dev/null || true
	fi
fi
# End automatically added section
