#!/bin/sh

set -e

if [ "$1" = "configure" ]; then

	# Create the "puppet" user
	if ! getent passwd puppet > /dev/null; then
		adduser --quiet --system --group --home /var/lib/puppet  \
			--no-create-home \
			--gecos "Puppet configuration management daemon" \
			puppet
	fi

	# Create the "puppet" group, if it is missing, and set the
	# primary group of the "puppet" user to this group.
	if ! getent group puppet > /dev/null; then
		addgroup --quiet --system puppet
		usermod -g puppet puppet
	fi

	# Set correct permissions and ownership for puppet directories

	# home directory
	if ! dpkg-statoverride --list /var/lib/puppet >/dev/null 2>&1; then
		dpkg-statoverride --update --add puppet puppet 0750 /var/lib/puppet
	fi

	# logdir
	if ! dpkg-statoverride --list /var/log/puppet >/dev/null 2>&1; then
		dpkg-statoverride --update --add puppet puppet 0750 /var/log/puppet
	fi

	# vardir
	if ! dpkg-statoverride --list /var/cache/puppet >/dev/null 2>&1; then
		dpkg-statoverride --update --add puppet puppet 0751 /var/cache/puppet
	fi

	# devicedir
	if ! dpkg-statoverride --list /var/cache/puppet/devices >/dev/null 2>&1; then
		dpkg-statoverride --update --add puppet puppet 0750 /var/cache/puppet/devices
	fi

	# publicdir
	if ! dpkg-statoverride --list /var/cache/puppet/public >/dev/null 2>&1; then
		dpkg-statoverride --update --add puppet puppet 0755 /var/cache/puppet/public
	fi

	# statedir
	if ! dpkg-statoverride --list /var/cache/puppet/state >/dev/null 2>&1; then
		dpkg-statoverride --update --add puppet puppet 0750 /var/cache/puppet/state
	fi

	# ssldir
	if ! dpkg-statoverride --list /var/lib/puppet/ssl >/dev/null 2>&1; then
		dpkg-statoverride --update --add puppet puppet 0750 /var/lib/puppet/ssl
	fi

	# move puppet-agent dropin directory after service unit rename
	if dpkg --compare-versions "$2" lt-nl 7.21.0-3~; then
		if [ -d /etc/system/systemd/puppet-agent.service.d ] && \
		   [ ! -d /etc/system/systemd/puppet.service.d ]; then
			mv /etc/system/systemd/puppet-agent.service.d /etc/system/systemd/puppet.service.d
			if [ -d /run/systemd/system ]; then
				systemctl --system daemon-reload > /dev/null || true
			fi
		fi
	fi

fi

# Automatically added by dh_installtmpfiles/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "$(command -v systemd-tmpfiles)" ]; then
		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create puppet-agent.conf || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper mv_conffile /etc/default/puppet-agent /etc/default/puppet 7.23.0-1\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/init.d/puppet-agent /etc/init.d/puppet 7.23.0-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/puppet" ]; then
		update-rc.d puppet defaults-disabled >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native puppet $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'puppet.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'puppet.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'puppet.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'puppet.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'puppet.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'puppet.service' >/dev/null || true
	fi
fi
# End automatically added section

