#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'puppet.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/puppet" ] ; then
	invoke-rc.d --skip-systemd-native puppet stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper mv_conffile /etc/default/puppet-agent /etc/default/puppet 7.23.0-1\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/init.d/puppet-agent /etc/init.d/puppet 7.23.0-1\~ -- "$@"
# End automatically added section
