#!/bin/sh
set -e

if [ "$1" = "upgrade" ]; then

    . /usr/share/debconf/confmodule

    if dpkg --compare-versions "$2" lt 0.5.0; then
        db_version 2.0
        db_reset yggdrasil/upgrade
        db_input critical yggdrasil/upgrade || true
        db_go || true
        db_get yggdrasil/upgrade
        answer="$RET"

        if [ "x$answer" != "xtrue" ]; then
            exit 1
        fi
    fi

fi


