#! /bin/sh

set -e

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/snmptrapd" ] ; then
	chmod -x "/etc/init.d/snmptrapd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d snmptrapd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'snmptrapd.socket' >/dev/null || true
	fi
fi
# End automatically added section


if [ $1 = purge ]; then
    rm -f /var/lib/snmp/snmptrapd.conf*
    rm -f /var/run/snmptrapd.pid
fi

exit 0
