#!/bin/sh

set -e

# Version 11 starts using defaults-disabled
# Remove rc.d links if upgrading from an older version and the service is
# disabled in /etc/default

if [ -n "$2" ] ; then
	if dpkg --compare-versions "$2" "<<" "11" ; then
		[ -r /etc/default/globus-gatekeeper ] && . /etc/default/globus-gatekeeper
		if [ -n "${RUN}" ] && [ "${RUN}" != "yes" ] ; then
			update-rc.d -f globus-gatekeeper remove >/dev/null
		fi
	fi
fi

# Automatically added by dh_installinit/13.14.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/globus-gatekeeper" ] ; then
	chmod +x "/etc/init.d/globus-gatekeeper" >/dev/null || true
fi
# End automatically added section

