#!/bin/sh

set -e

case $1 in
	purge)
		rm -rf /var/spool/snmptt
		;;
esac

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/snmptt" ] ; then
	chmod -x "/etc/init.d/snmptt" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d snmptt remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'snmptt.service' >/dev/null || true
	fi
fi
# End automatically added section

