#!/bin/sh
set -e

CONFFILE=/etc/dibbler/client.conf
TMP=${CONFFILE}-dpkg-new

if [ "$1" = "purge" ] ; then
    if [ -e ${CONFFILE} ]; then
	rm -f ${CONFFILE}
    fi
    if [ -e ${TMP} ]; then
	rm -f ${TMP}
    fi
    test -f /usr/bin/ucf && ucf --debconf-ok --purge ${CONFFILE}
fi

# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/dibbler-client" ] ; then
	chmod -x "/etc/init.d/dibbler-client" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d dibbler-client remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.20
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

