#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
  if [ -d "/var/log/ircd" ]; then
    rm -rf /var/log/ircd/*
    rmdir --ignore-fail-on-non-empty /var/log/ircd
  fi
  if [ -d "/var/run/ircd" ]; then
    rm -rf /var/run/ircd/*
    rmdir --ignore-fail-on-non-empty /var/run/ircd
  fi
fi

# Automatically added by dh_installinit/13.23
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ircd-irc2" ] ; then
	chmod -x "/etc/init.d/ircd-irc2" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d ircd-irc2 remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.23
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ircd-irc2.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
