#!/bin/sh
# postrm script for quassel-core

set -e

# configure some variables
QUASSEL_GROUP=quassel
QUASSEL_USER=quasselcore

case "$1" in
	purge)
		echo "Deleting $QUASSEL_USER user ..."
		if which deluser > /dev/null; then
			deluser --quiet --system $QUASSEL_USER
		fi

		echo "Deleting $QUASSEL_GROUP group ..."
		if which delgroup > /dev/null; then
			delgroup --quiet --system $QUASSEL_GROUP
		fi

		echo "Deleting /var/cache/quassel ..."
		rm -rf /var/lib/quassel
		echo "Deleting /var/log/quassel ..."
                rm -rf /var/log/quassel
		;;
	remove)
		;;
	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/quasselcore" ] ; then
	chmod -x "/etc/init.d/quasselcore" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d quasselcore remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'quasselcore.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/4.1.0~beta5-2
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.bin.quasselcore" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.bin.quasselcore" || true
    rm -f "/etc/apparmor.d/force-complain/usr.bin.quasselcore" || true
    rm -f "/etc/apparmor.d/local/usr.bin.quasselcore" || true
    rm -f /var/cache/apparmor/*/"usr.bin.quasselcore" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section

