#!/bin/sh
set -e
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/binfmt-support" ] ; then
	chmod +x "/etc/init.d/binfmt-support" >/dev/null || true
fi
# End automatically added section
