#!/bin/sh
set -e

case "$1" in
configure)
    # creating gerbera group if it isn't already there
    if ! getent group gerbera >/dev/null; then
        # Adding system group: gerbera.
        addgroup --system gerbera >/dev/null
    fi

    # creating gerbera user if it isn't already there
    if ! getent passwd gerbera >/dev/null; then
        # Adding system user: gerbera.
        adduser \
         --system \
         --ingroup gerbera \
         --home /var/lib/gerbera \
         --no-create-home \
         --gecos "Gerbera Media Server" \
         --shell /usr/sbin/nologin \
         --disabled-login \
         --disabled-password \
         gerbera  >/dev/null
    fi

    if ! dpkg-statoverride --list /etc/gerbera/config.xml >/dev/null 2>&1
    then
        dpkg-statoverride --update --add gerbera gerbera 644 /etc/gerbera/config.xml
    fi
    if ! dpkg-statoverride --list /var/lib/gerbera >/dev/null 2>&1
    then
        dpkg-statoverride --update --add gerbera gerbera 755 /var/lib/gerbera
    fi
esac

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/gerbera" ]; then
		update-rc.d gerbera defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native gerbera $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'gerbera.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'gerbera.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'gerbera.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'gerbera.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'gerbera.service' >/dev/null || true
	fi
fi
# End automatically added section

