#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.8
if [ "$1" = "remove" ] && [ -x "/etc/init.d/cachefilesd" ] ; then
	chmod -x "/etc/init.d/cachefilesd" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d cachefilesd remove >/dev/null
fi
# End automatically added section
