#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.8
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/cachefilesd" ] ; then
	invoke-rc.d cachefilesd stop || exit 1
fi
# End automatically added section
