#!/bin/sh
#
# Post removal script for Tomcat
#

set -e

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'tomcat11.service' >/dev/null || true
	fi
fi
# End automatically added section


CONFFILES="tomcat-users.xml web.xml server.xml logging.properties context.xml catalina.properties jaspic-providers.xml"

case "$1" in
    remove)
        # Remove the ROOT webapp if not modified
        RWLOC="/var/lib/tomcat11/webapps/ROOT"
        RWFILES="$RWLOC/index.html $RWLOC/META-INF/context.xml"
        if [ "`(cat $RWFILES | md5sum -) 2>/dev/null | cut -d ' ' -f 1`" \
                            = "0bd580369a24425f994f9d524d85d9a3" ] ; then
            rm $RWFILES
            rmdir --ignore-fail-on-non-empty \
                /var/lib/tomcat11/webapps/ROOT/META-INF \
                /var/lib/tomcat11/webapps/ROOT \
                /var/lib/tomcat11/webapps \
                /var/lib/tomcat11 || true
        fi

        # Remove CATALINA_BASE/lib if not empty
        if [ -d /var/lib/tomcat11/lib ] && [ -z "`(find var/lib/tomcat11/lib/classes -type f)`" ] ; then
            rmdir --ignore-fail-on-non-empty \
                /var/lib/tomcat11/lib/classes \
                /var/lib/tomcat11/lib || true
        fi

        # Remove the cache files (compiled JSP files)
        if [ -d "/var/cache/tomcat11" ] ; then
            rm -rf /var/cache/tomcat11
        fi
    ;;

    purge)
        # Ignore errors during purge
        set +e

        # Remove the configuration files
        rm -rf /etc/logrotate.d/tomcat11
        rm -rf /etc/default/tomcat11
        for conffile in $CONFFILES;
        do
            rm -f /etc/tomcat11/$conffile
        done

        # Unregister the configuration files from ucf
        if which ucf >/dev/null; then
            ucf --purge /etc/logrotate.d/tomcat11
            ucf --purge /etc/default/tomcat11
            for conffile in $CONFFILES;
            do
                ucf --purge /etc/tomcat11/$conffile
            done
        fi

        # Remove the log files
        rm -rf /var/log/tomcat11

        # Remove the temp directory
        rm -rf /var/lib/tomcat11/temp

        # Remove the CATALINA_BASE directory if empty
        if [ -d "/var/lib/tomcat11" ] ; then
            rmdir --ignore-fail-on-non-empty /var/lib/tomcat11
        fi

        # Remove the configuration directories
        rmdir --ignore-fail-on-non-empty /etc/tomcat11/Catalina/* /etc/tomcat11/Catalina /etc/tomcat11

        set -e
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
