#!/bin/sh
#
# Post installation script for Tomcat
#

set -e

TOMCAT_USER="tomcat"
TOMCAT_GROUP="tomcat"

CONFFILES="tomcat-users.xml web.xml server.xml logging.properties context.xml catalina.properties jaspic-providers.xml"

case "$1" in
    configure)
	# Create the tomcat user as defined in /usr/lib/sysusers.d/tomcat11.conf
	systemd-sysusers

	# Install the configuration files
	for conffile in $CONFFILES;
	do
		ucf --debconf-ok --three-way /usr/share/tomcat11/etc/$conffile /etc/tomcat11/$conffile

		# Configuration files should not be modifiable by the tomcat user, as this can be
		# a security issue (an attacker may insert code in a webapp and rewrite the tomcat
		# configuration) but those files should be readable by tomcat, so we set the group
		# to tomcat.
		if [ -f "/etc/tomcat11/$conffile" ]; then
			chown root:$TOMCAT_GROUP /etc/tomcat11/$conffile
			chmod 640 /etc/tomcat11/$conffile
		fi
	done

	# Install /etc/logrotate.d/tomcat11
	ucf --debconf-ok --three-way /usr/share/tomcat11/logrotate.template /etc/logrotate.d/tomcat11

	# Install /etc/default/tomcat11
	ucf --debconf-ok --three-way /usr/share/tomcat11/default.template /etc/default/tomcat11

	# Grant the tomcat group read/write access to /var/lib/tomcat11/lib. This allows
	# a non-root administrator in the tomcat group to add jar files to the classpath
	# (for example database drivers).
	chown -Rh $TOMCAT_USER:$TOMCAT_GROUP /var/lib/tomcat11/lib

	# Grant the tomcat group read/write access to the /etc/tomcat11/Catalina directory
	# to write the hosts/contexts configuration files.
	chown -Rh root:$TOMCAT_GROUP /etc/tomcat11/Catalina
	chmod 775 /etc/tomcat11/Catalina

	# Grant read/write access to tomcat to the webapps directory (needed for extracting
	# war files and for deploying webapps by non-root administrators in the tomcat group).
	chown -Rh $TOMCAT_USER:$TOMCAT_GROUP /var/lib/tomcat11/webapps
	chmod 775 /var/lib/tomcat11/webapps

	# Grant read/write access to tomcat to the log and cache directories
	chown -Rh $TOMCAT_USER:adm /var/log/tomcat11/
	chmod 2770 /var/log/tomcat11/
	chown -Rh $TOMCAT_USER:$TOMCAT_GROUP /var/cache/tomcat11/
	chmod 750 /var/cache/tomcat11/
    ;;
esac

# Install the default root webapp if there isn't one already
if [ ! -d /var/lib/tomcat11/webapps/ROOT ]; then
    cp -r /usr/share/tomcat11-root/default_root /var/lib/tomcat11/webapps/ROOT
fi

# Automatically added by dh_installtmpfiles/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "$(command -v systemd-tmpfiles)" ]; then
		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create tomcat11.conf || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'tomcat11.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'tomcat11.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'tomcat11.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'tomcat11.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'tomcat11.service' >/dev/null || true
	fi
fi
# End automatically added section

