#!/bin/sh

set -e

case "$1" in
	configure)
		getent group _znc >/dev/null 2>&1 || addgroup --force-badname --system _znc
		adduser --force-badname --system --home /var/lib/znc --quiet _znc --ingroup _znc || true
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'znc.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'znc.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'znc.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'znc.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'znc.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			deb-systemd-invoke try-restart 'znc.service' >/dev/null || true
		fi
	fi
fi
# End automatically added section


exit 0
