#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.9
if [ "$1" = "remove" ] && [ -x "/etc/init.d/diod" ] ; then
	chmod -x "/etc/init.d/diod" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d diod remove >/dev/null
fi
# End automatically added section
