#! /bin/sh

set -e

if [ "$1" = "purge" ]; then
    if dpkg-statoverride --list /usr/lib/cgi-bin/pks/\* >/dev/null; then
        for i in $(dpkg-statoverride --list /usr/lib/cgi-bin/pks/\* | cut -d " " -f 4); do
            dpkg-statoverride --remove $i
	done
    fi

    rm -f /var/log/onak.log /var/log/onak.log.1 /var/log/onak.log.*.gz
fi

# Automatically added by dh_installinit/13.14.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/onak" ] ; then
	chmod -x "/etc/init.d/onak" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d onak remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.14.1
dpkg-maintscript-helper rm_conffile /etc/onak.conf 0.4.6-1 onak -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'onak.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'onak.service' >/dev/null || true
	fi
fi
# End automatically added section

