#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.14.1
dpkg-maintscript-helper rm_conffile /etc/onak.conf 0.4.6-1 onak -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.14.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/onak" ] ; then
	chmod +x "/etc/init.d/onak" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'onak.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'onak.socket' >/dev/null || true
fi
# End automatically added section
