#!/bin/sh

set -e

case "$1" in
    purge)
        if [ -x "$(command -v deluser)" ]; then
            rm -rf /var/log/nutcracker/
            deluser --quiet --system nutcracker > /dev/null || true
            deluser --group --system --quiet --only-if-empty nutcracker || true
        else
            echo >&2 "not removing nutcracker system account, group and logfiles because deluser command was not found"
        fi
	;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;
    *)
	echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac

# Automatically added by dh_installinit/13.11.9
if [ "$1" = "remove" ] && [ -x "/etc/init.d/nutcracker" ] ; then
	chmod -x "/etc/init.d/nutcracker" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d nutcracker remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.9
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.9
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nutcracker.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
