#!/bin/sh

set -e

DEFAULT_DISPLAY_MANAGER_FILE=/etc/X11/default-display-manager

if [ "$1" = "abort-install" ] || [ "$1" = "abort-upgrade" ]; then
  if [ -e "$DEFAULT_DISPLAY_MANAGER_FILE.dpkg-tmp" ]; then
    mv "$DEFAULT_DISPLAY_MANAGER_FILE.dpkg-tmp" "$DEFAULT_DISPLAY_MANAGER_FILE"
  fi
fi

if [ "$1" = "purge" ] ; then
        update-rc.d lightdm remove >/dev/null
        if [ -d /var/lib/lightdm ]; then
                rm -r /var/lib/lightdm
        fi
        if [ -d /var/log/lightdm ]; then
                rm -r /var/log/lightdm
        fi
        error() { echo >&2 "Could not remove lightdm $1.
Please make sure lightdm is not running before attempting to purge lightdm"; }
        if getent passwd lightdm >/dev/null; then
                if which deluser >/dev/null; then
                        deluser --system lightdm || error user
                fi
        fi
        if getent group lightdm >/dev/null; then
                if which delgroup >/dev/null; then
                        delgroup --system lightdm || error group
                fi
        fi
fi
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.DisplayManager.conf 1.32.0-4\~ lightdm -- "$@"
# End automatically added section
# Automatically added by dh_installdebconf/13.24.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

exit 0
