#!/bin/sh

set -e

. /usr/share/debconf/confmodule

THIS_PACKAGE=lightdm
DEFAULT_DISPLAY_MANAGER_FILE=/etc/X11/default-display-manager

# creating lightdm group if he isn't already there
if ! getent group lightdm >/dev/null; then
        addgroup --system lightdm
fi

# creating lightdm user if he isn't already there
if ! getent passwd lightdm >/dev/null; then
        adduser --system --ingroup lightdm --home /var/lib/lightdm lightdm
        usermod -c "Light Display Manager" lightdm
        usermod -d "/var/lib/lightdm"      lightdm
        usermod -g "lightdm"               lightdm
        usermod -s "/bin/false"            lightdm
fi

# fix https://bugs.devuan.org/494
usermod -G audio -a lightdm 1>/dev/null 2>&1 || true

mkdir -p /var/lib/lightdm
chown lightdm:lightdm /var/lib/lightdm
chmod 0750 /var/lib/lightdm

# debconf is not a registry, so we only fiddle with the default file if it
# does not exist
if [ ! -e "$DEFAULT_DISPLAY_MANAGER_FILE" ]; then
  if db_get shared/default-x-display-manager; then
    # workaround debconf passthru bug (#379198)
    if [ -z "$RET" ]; then
      $RET="$THIS_PACKAGE"
    fi
    if [ "$THIS_PACKAGE" != "$RET" ]; then
      echo "Please be sure to run \"dpkg --configure $RET\"."
    fi
    if db_get "$RET"/daemon_name; then
      echo "$RET" > $DEFAULT_DISPLAY_MANAGER_FILE
    fi
  fi
fi

# remove the displaced old default display manager file if it exists
if [ -e "$DEFAULT_DISPLAY_MANAGER_FILE.dpkg-tmp" ]; then
  rm "$DEFAULT_DISPLAY_MANAGER_FILE.dpkg-tmp"
fi

# debconf hangs if lightdm gets started below without this
db_stop || true

# update-rc.d levels
S=30
K=01

if [ -x /etc/init.d/lightdm ]; then
  update-rc.d lightdm defaults $S $K >/dev/null 2>&1
fi

if [ "$1" = "configure" ];
then
  invoke-rc.d dbus reload || true
fi

# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.DisplayManager.conf 1.32.0-4\~ lightdm -- "$@"
# End automatically added section


exit 0
