#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.DisplayManager.conf 1.32.0-4\~ lightdm -- "$@"
# End automatically added section
