#!/bin/sh

set -e

# orginal by installinit
if [ "$1" = "purge" ] ; then
	userdel scanlogd || true
	rm -rf /var/run/scanlogd
fi

# Automatically added by dh_installinit/13.3.4
if [ "$1" = "purge" ] ; then
	update-rc.d scanlogd remove >/dev/null
fi
# End automatically added section

