#!/bin/sh

set -e

if [ -d /home/scanlogd ] ; then # Clean up after #668722
	# If for some reason the directory isn't empty
	# then the directory shouldn't be unconditionally
	# removed
	rmdir --ignore-fail-on-non-empty /home/scanlogd
fi

# scanlogd needs a user
adduser --system --home /var/lib/scanlogd --no-create-home --quiet scanlogd || true

if which invoke-rc.d >/dev/null 2>&1; then
    invoke-rc.d scanlogd start
else
    /etc/init.d/scanlogd start
fi

# Automatically added by dh_installinit/13.3.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/scanlogd" ]; then
		update-rc.d scanlogd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native scanlogd $_dh_action || exit 1
	fi
fi
# End automatically added section

