#!/bin/sh

set -e

# orginal by dh_installinit
if which invoke-rc.d >/dev/null 2>&1; then
    invoke-rc.d scanlogd stop
else
    /etc/init.d/scanlogd stop
fi

# Automatically added by dh_installinit/13.3.4
if [ -x "/etc/init.d/scanlogd" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native scanlogd stop || exit 1
fi
# End automatically added section

