#!/bin/sh

set -e

case "$1" in
    purge)
        rm -fr /etc/zabbix/zabbix_agentd.conf.d
        rm -fr /var/log/zabbix-agent
        rm -fr /run/zabbix

        # Can be removed after Wheezy:
        ucf --purge /etc/zabbix/zabbix_agent.conf || true
    ;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/zabbix-agent" ] ; then
	chmod -x "/etc/init.d/zabbix-agent" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d zabbix-agent remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_ucf/13.24.2
if [ "$1" = "purge" ]; then
	for ext in .ucf-new .ucf-old .ucf-dist ""; do
		rm -f "/etc/zabbix/zabbix_agentd.conf$ext"
	done
	
	if [ -x "`command -v ucf`" ]; then
		ucf --purge "/etc/zabbix/zabbix_agentd.conf"
	fi
	if [ -x "`command -v ucfr`" ]; then
		ucfr --purge zabbix-agent "/etc/zabbix/zabbix_agentd.conf"
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'zabbix-agent.service' >/dev/null || true
	fi
fi
# End automatically added section

