#!/bin/sh

set -e

case "$1" in
install|upgrade)
    update-rc.d opensm-boot remove || true
esac

# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/init.d/opensm-boot 3.3.22-1\~ opensm -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/opensm" ] ; then
	chmod +x "/etc/init.d/opensm" >/dev/null || true
fi
# End automatically added section

