#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'opensm.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/opensm" ] ; then
	invoke-rc.d --skip-systemd-native opensm stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/init.d/opensm-boot 3.3.22-1\~ opensm -- "$@"
# End automatically added section
