#!/bin/sh
set -e

zedd="/usr/lib/zfs-linux/zed.d"
etcd="/etc/zfs/zed.d"

if [ "$1" = "purge" ] && [ -d "$etcd" ] ; then
    # remove the overrides created in prerm
    find "${etcd}" -maxdepth 1 -lname '/dev/null' -delete
    # remove any dangling symlinks to old zedlets
    find "${etcd}" -maxdepth 1 -lname "${zedd}/*" -xtype l  -delete
    # clean up any empty directories
    ( rmdir "$etcd" && rmdir "/etc/zfs" ) || true
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/zfs-zed" ] ; then
	chmod -x "/etc/init.d/zfs-zed" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d zfs-zed remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'zfs-zed.service' >/dev/null || true
	fi
fi
# End automatically added section


