#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'mythtv-status.service' 'mythtv-status_health-check.service' 'mythtv-status_health-check.timer' 'mythtv-status_update-motd.service' 'mythtv-status_update-motd.timer' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/mythtv-status" ] ; then
	invoke-rc.d --skip-systemd-native mythtv-status stop || exit 1
fi
# End automatically added section
