#!/bin/sh

set -e

# Load debconf if available (might have been removed before purging
# slapd)

if [ -e "/usr/share/debconf/confmodule" ]; then
  . /usr/share/debconf/confmodule
fi

# Check if the user wants the database removed on purging slapd
remove_database_on_purge() {
  db_get slapd/purge_database || RET=false
  if [ "$RET" = "true" ]; then
    return 0
  else
    return 1
  fi
}

if [ "$1" = "purge" ]; then
  echo -n "Removing slapd configuration... "
  rm -f /etc/ldap/slapd.conf 2>/dev/null || true
  rm -rf /etc/ldap/slapd.d 2>/dev/null || true
  echo "done."

  if remove_database_on_purge; then
    echo -n "Purging OpenLDAP database... "
    rm -rf /var/lib/ldap || true
    echo done
  fi
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/slapd" ] ; then
	chmod -x "/etc/init.d/slapd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d slapd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/ldap/schema/ppolicy.schema 2.5.4\+dfsg-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/ldap/schema/ppolicy.ldif 2.5.4\+dfsg-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'slapd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0

