#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/certmonger/nssdb/cert9.db 0.79.17-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/certmonger/nssdb/key4.db 0.79.17-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/certmonger/nssdb/pkcs11.txt 0.79.17-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/certmonger/nssdb/ 0.79.17-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/certmonger" ] ; then
	chmod +x "/etc/init.d/certmonger" >/dev/null || true
fi
# End automatically added section
