#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/live-config" ]; then
		update-rc.d live-config start 00 S . >/dev/null || exit 1
	fi
fi
# End automatically added section
