#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/live-config" ] ; then
	chmod +x "/etc/init.d/live-config" >/dev/null || true
fi
# End automatically added section
