#!/bin/sh

set -e

if [ "remove" = "$1" ]; then
    if command -v update-inetd > /dev/null; then
        update-inetd --remove '.*gopher.*gophernicus'
    fi
fi

# Automatically added by dh_installsystemd/13.16
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'gophernicus.socket' >/dev/null || true
fi
# End automatically added section


exit 0
