#!/bin/sh
set -e

. /usr/share/debconf/confmodule

if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*" 1>&2 }

FILE_INI="/etc/virtuoso-opensource-7/virtuoso.ini"
FILE_ODBC_DSN="/usr/share/virtuoso-opensource-7/odbc.ini"

invoke-rc.d virtuoso-opensource-7 stop || true

if [ "$1" = "purge" ]; then
	# log files can go without warning...
	rm -rf /var/log/virtuoso-opensource-7

	# ...but get explicit confirmation before removing databases
	db_input high virtuoso-opensource-7/check-remove-databases || true
	db_go || true
	db_get virtuoso-opensource-7/check-remove-databases || true
	if [ "$RET" = "true" ]; then
		rm -rf /var/lib/virtuoso-opensource-7
	fi

	rm -f $FILE_INI
	rm -f $FILE_ODBC_DSN

	update-rc.d virtuoso-opensource-7 remove >/dev/null || exit $?
fi

# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/virtuoso-opensource-7/virtuoso.ini 7.2.5.1\+dfsg-1\~ virtuoso-opensource-7 -- "$@"
# End automatically added section
# Automatically added by dh_installdebconf/13.24.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

