#!/bin/sh
set -e

# add ocserv user/group if needed.
if ! getent group ocserv >/dev/null; then
    addgroup --system ocserv
fi
if ! getent passwd ocserv >/dev/null; then
    adduser --system --ingroup ocserv \
            --home /run/ocserv --no-create-home \
            ocserv
fi

# create chroot/socket directory if needed.
mkdir -p /var/lib/ocserv/run

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/ocserv" ]; then
		update-rc.d ocserv defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native ocserv $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'ocserv.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'ocserv.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'ocserv.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'ocserv.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'ocserv.service' >/dev/null || true
fi
# End automatically added section


