#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    rm -rf /var/log/iaxmodem
fi

# Automatically added by dh_installinit/13.3.4
if [ "$1" = "purge" ] ; then
	update-rc.d iaxmodem remove >/dev/null
fi
# End automatically added section

