#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/openipmi" ] ; then
	chmod -x "/etc/init.d/openipmi" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d openipmi remove >/dev/null
fi
# End automatically added section
