#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/default/argus-server 2:3.0.8.1-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/argus-server 2:3.0.8.1-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/ppp/ip-down.d/argus-server 2:3.0.8.1-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/ppp/ip-up.d/argus-server 2:3.0.8.1-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'argus.service' >/dev/null || true
fi
# End automatically added section
