#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'openqa-slirpvde.service' 'openqa-vde_switch.service' 'openqa-worker-cacheservice-minion.service' 'openqa-worker-cacheservice.service' 'openqa-worker.target' >/dev/null || true
	fi
fi
# End automatically added section
