#!/bin/sh
set -e

if test "$1" = "configure"; then
    if ! getent passwd gdnsd > /dev/null; then
        adduser --quiet --system --group \
		--home /run/gdnsd \
		--no-create-home \
		gdnsd
    fi
fi

# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/init.d/gdnsd 2.4.2-1 -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'gdnsd.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'gdnsd.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'gdnsd.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'gdnsd.service' >/dev/null || true
	fi
fi
# End automatically added section


# Override dh_installsystemd's default here, to be able to perfom zero downtime
# upgrades (i.e. without restarting the daemon) on >= 3.x. We'd ideally want to
# use something like a --reload-after-upgrade option, but this is not supported
# yet. See debhelper MR #14 and Debian #892958 for an eventual implementation.
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			if systemctl --quiet is-active gdnsd && echo "$2" | grep -vq '^[1-2]\.'; then
				_dh_action=reload-or-restart
			else
				_dh_action=restart
			fi
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'gdnsd.service' >/dev/null || true
	fi
fi

exit 0
