#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/prerm.pgsql ]; then
	. /usr/share/dbconfig-common/dpkg/prerm.pgsql
	dbc_go sreview-master "$@"
fi

# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'sreview-dispatch.service' >/dev/null || true
fi
# End automatically added section

