#!/bin/sh -e

case "$1" in
	remove|purge)

		if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
		# Source debconf library.
			. /usr/share/debconf/confmodule
			# Remove my changes to the db.
			db_purge
		fi
		;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;
esac

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/nas" ] ; then
	chmod -x "/etc/init.d/nas" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d nas remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.15.3
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

