#!/bin/sh -e

CONF=/etc/nas/nasd.conf
CONFEG=/usr/share/nas/nasd.conf.eg

# Source debconf library.
. /usr/share/debconf/confmodule
db_version 2.0

set_var ()
{
	if [ ! -f $CONF ] ; then
		cp $CONFEG $CONF
	fi

	NAME=$1
	VALUE=$2

#	echo "Setting $NAME to $VALUE" >/dev/stderr

	sed "s/^[[:space:]\#]*$NAME.*/$NAME \"$VALUE\"/g" $CONF >$CONF.tmp
	mv $CONF.tmp $CONF
}

case "$1" in
	configure)

		# Grab config stuff from debconf
		db_get nas/relinquish
		if [ "$RET" = "true" ] ; then
			set_var ReleaseDevice yes
		else
			set_var ReleaseDevice no
		fi

		db_get nas/mixer
		if [ "$RET" = "true" ] ; then
			set_var MixerInit yes
		else
			set_var MixerInit no
		fi

		# Start up NAS

		db_stop
	;;
	
	abort-upgrade|abort-remove|abort-deconfigure)

		# Restart NAS
	;;

esac

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/nas" ]; then
		update-rc.d nas defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native nas $_dh_action || exit 1
	fi
fi
# End automatically added section

