#!/bin/sh
set -e
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/nas" ] ; then
	chmod +x "/etc/init.d/nas" >/dev/null || true
fi
# End automatically added section
