#!/bin/sh
set -e
# Automatically added by dh_installinit/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/rsplib-registrar" ] ; then
	invoke-rc.d --skip-systemd-native rsplib-registrar stop || exit 1
fi
# End automatically added section
