#!/bin/bash

set -e

# Automatically added by dh_systemd_start/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'iipsrv.service' >/dev/null || true
fi
# End automatically added section


if [ "$1" != "remove" -a "$1" != "purge" ]; then
	exit 0
fi

if [ -e /etc/apache2/apache2.conf ]; then
	a2dismod iipsrv || true
	rm /var/log/iipsrv.log
fi

if [ -e /etc/lighttpd/lighttpd.conf ]; then
	lighty-disable-mod iipsrv || true
	rm /var/log/iipsrv.log
fi

exit 0
