#!/bin/sh
set -e
# Automatically added by dh_installinit/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/pcapdump" ]; then
		update-rc.d pcapdump start 90 2 3 4 5 . stop 05 0 1 6 . >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native pcapdump $_dh_action || exit 1
	fi
fi
# End automatically added section
