#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.9
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/numad" ] ; then
	chmod +x "/etc/init.d/numad" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.9
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'numad.service' >/dev/null || true
fi
# End automatically added section
