#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
	rm -f /etc/default/i2pd
	rm -rf /etc/i2pd
	rm -rf /var/lib/i2pd
	rm -rf /var/log/i2pd
	rm -rf /run/i2pd
fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/i2pd" ] ; then
	chmod -x "/etc/init.d/i2pd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d i2pd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'i2pd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/4.1.0~beta5-3
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.bin.i2pd" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.bin.i2pd" || true
    rm -f "/etc/apparmor.d/force-complain/usr.bin.i2pd" || true
    rm -f "/etc/apparmor.d/local/usr.bin.i2pd" || true
    rm -f /var/cache/apparmor/*/"usr.bin.i2pd" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section


exit 0
