#!/bin/sh
set -e

if [ x"$1" = xconfigure ]; then
  if [ -f /etc/inittab ]; then
    if ! grep '^SV:' /etc/inittab >/dev/null; then
      echo 'Adding SV inittab entry...'
      (
        cat /etc/inittab
        echo '#-- daemontools-run begin'
        echo 'SV:123456:respawn:/usr/bin/svscanboot'
        echo '#-- daemontools-run end'
      ) > /etc/inittab'{new}'
      mv -f /etc/inittab'{new}' /etc/inittab
      init q || :
    fi
  fi
fi

# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'daemontools-run.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'daemontools-run.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'daemontools-run.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'daemontools-run.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'daemontools-run.service' >/dev/null || true
	fi
fi
# End automatically added section

