#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/ceilometer-agent-notification" ] ; then
	invoke-rc.d ceilometer-agent-notification stop || true
fi
# End automatically added section
