#!/bin/sh
set -e
# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/pagekite" ] ; then
	chmod -x "/etc/init.d/pagekite" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d pagekite remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.20
dpkg-maintscript-helper rm_conffile /etc/pagekite.rc 0.3.9-1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pagekite/pagekite.rc -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pagekite/local.rc -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'pagekite.service' >/dev/null || true
	fi
fi
# End automatically added section
