#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.20
dpkg-maintscript-helper rm_conffile /etc/pagekite.rc 0.3.9-1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pagekite/pagekite.rc -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pagekite/local.rc -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.20
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/pagekite" ] ; then
	chmod +x "/etc/init.d/pagekite" >/dev/null || true
fi
# End automatically added section
