#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'pagekite.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/pagekite" ] ; then
	invoke-rc.d --skip-systemd-native pagekite stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.20
dpkg-maintscript-helper rm_conffile /etc/pagekite.rc 0.3.9-1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pagekite/pagekite.rc -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pagekite/local.rc -- "$@"
# End automatically added section

# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1; then
	py3clean -p pagekite 
else
	dpkg -L pagekite | sed -En -e '/^(.*)\/(.+)\.py$/s,,rm "\1/__pycache__/\2".*,e'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section
