#!/bin/sh

set -e

case "$1" in
    purge)
        for d in /etc/pinto \
            /var/log/pinto \
            /var/lib/pinto \
            /var/run/pinto ; do
            rm -rf $d 2> /dev/null || true;
        done;
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/pinto" ] ; then
	chmod -x "/etc/init.d/pinto" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d pinto remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
