#!/bin/sh

set -e

### Start of included pkgos_postrm library
#!/bin/sh
# -*- mode: shell-script -*-

# Perform cleanups when removing a package
# Prototype: pkgos_postrm <template-prefix-name> <package-name> $@
# Example:   pkgos_postrm neutron                neutron-common $@
pkgos_dbc_postrm () {
	local PKPRM_TEMPLATE_PREFIX PKPRM_PACKAGE_NAME

	PKPRM_TEMPLATE_PREFIX=${1}
	PKPRM_PACKAGE_NAME=${2}
	shift
	shift

	if [ -f /usr/share/debconf/confmodule ] ; then
		. /usr/share/debconf/confmodule
		# If the package has the template, then it means we're having a db,
		# and therefore we can call the dbconfig-common clean function.
		db_get ${PKPRM_TEMPLATE_PREFIX}/configure_db
		if [ "$RET" = "true" ] ; then
			if [ -f /usr/share/dbconfig-common/dpkg/postrm ] ; then
				. /usr/share/dbconfig-common/dpkg/postrm
				dbc_go ${PKPRM_PACKAGE_NAME} $@
			else
				rm -f /etc/dbconfig-common/${PKPRM_PACKAGE_NAME}.conf
				if which ucf >/dev/null 2>&1; then
					ucf --purge /etc/dbconfig-common/${PKPRM_PACKAGE_NAME}.conf
					ucfr --purge ${PKPRM_PACKAGE_NAME} /etc/dbconfig-common/${PKPRM_PACKAGE_NAME}.conf
                                fi
                        fi
                fi
	fi

	rm -rf /var/lib/${PKPRM_TEMPLATE_PREFIX} /var/log/${PKPRM_TEMPLATE_PREFIX} /var/lock/${PKPRM_TEMPLATE_PREFIX}
}
### End of included pkgos_postrm library

if [ "${1}" = "purge" ] ; then
        pkgos_dbc_postrm ironic-inspector ironic-inspector $@

	rm -f /etc/ironic-inspector/inspector.conf /etc/ironic-inspector/policy.json
	rmdir --ignore-fail-on-non-empty /etc/ironic-inspector || true
	rm -rf /var/lib/ironic-inspector
	rm -rf /var/log/ironic-inspector
fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ironic-inspector-conductor" ] ; then
	chmod -x "/etc/init.d/ironic-inspector-conductor" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d ironic-inspector-conductor remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ironic-inspector-api" ] ; then
	chmod -x "/etc/init.d/ironic-inspector-api" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d ironic-inspector-api remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ironic-inspector" ] ; then
	chmod -x "/etc/init.d/ironic-inspector" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d ironic-inspector remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ironic-inspector-conductor.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ironic-inspector-api.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
