#!/bin/sh

set -e

if [ "${1}" = "remove" ] && [ -r /usr/share/debconf/confmodule ] && [ -r /usr/share/dbconfig-common/dpkg/prerm ] ; then
	. /usr/share/debconf/confmodule
	db_get ironic-inspector/configure_db || true
	if [ "$RET" = "true" ] ; then
		. /usr/share/dbconfig-common/dpkg/prerm
		dbc_go ironic-inspector $@
	fi
fi

# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/ironic-inspector-conductor" ] ; then
	invoke-rc.d ironic-inspector-conductor stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/ironic-inspector-api" ] ; then
	invoke-rc.d ironic-inspector-api stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'ironic-inspector-conductor.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'ironic-inspector-api.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/ironic-inspector" ] ; then
	invoke-rc.d ironic-inspector stop || true
fi
# End automatically added section


exit 0
