#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/shairport-sync-dbus-policy.conf 4.3.7-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/shairport-sync-mpris-policy.conf 4.3.7-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/shairport-sync" ] ; then
	chmod +x "/etc/init.d/shairport-sync" >/dev/null || true
fi
# End automatically added section
