#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'shairport-sync.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/shairport-sync" ] ; then
	invoke-rc.d --skip-systemd-native shairport-sync stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/shairport-sync-dbus-policy.conf 4.3.7-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/shairport-sync-mpris-policy.conf 4.3.7-1\~ -- "$@"
# End automatically added section
