#! /bin/sh

### BEGIN INIT INFO
# Provides:		olpc-kbdshim
# Required-Start:	$syslog $remote_fs
# Required-Stop:	$syslog $remote_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	OLPC XO keyboard support daemon
### END INIT INFO

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/olpc-kbdshim-udev
NAME=olpc-kbdshim
PIDFILE=/var/run/$NAME.pid
DESC="OLPC XO keyboard support daemon"

test -x $DAEMON || exit 0

# make sure we're running on an XO
[ -f /proc/device-tree/model ] || exit 0

. /lib/lsb/init-functions

modprobe uinput || true
modprobe olpc-dcon || true

# allow the admin to set DAEMON_OPTS
if [ -f /etc/default/olpc-kbdshim ]; then
	. /etc/default/olpc-kbdshim
fi

do_start()
{
	start-stop-daemon --start --quiet --oknodo --background \
			--make-pidfile --pidfile $PIDFILE \
			--exec $DAEMON -- $DAEMON_OPTS
}

do_stop()
{
	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE \
			--name $NAME
}

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	log_end_msg $?
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	log_end_msg $?
	;;

  restart|force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	sleep 1
	do_start
	log_end_msg $?
	;;

  *)
	log_success_msg "Usage: $0 {start|stop|restart|force-reload}"
	exit 1
	;;
esac

exit 0
