#!/bin/sh -e

generate_config () {
	db_get uftp/generate_config || RET=
	[ "$RET" = true ] || return

	db_get uftp/dest_dir
	local dest_dir="$RET"
	db_get uftp/arguments
	local args="$RET"

	cat >/etc/default/uftp <<CONF
#
# This is a POSIX shell fragment sourced by /etc/init.d/uftp
# It is managed by debconf - use 'dpkg-reconfigure uftp'.
#
DAEMON_ARGS="-L /var/log/uftp.log -D ${dest_dir} ${args}"
CONF

	db_set uftp/generate_config false
}

case "$1" in
configure)
	. /usr/share/debconf/confmodule
	db_version 2.0

	generate_config
	;;
esac

# Automatically added by dh_systemd_enable/13.14.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'uftp.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'uftp.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'uftp.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'uftp.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.14.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/uftp" ]; then
		update-rc.d uftp defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d uftp $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0
