#! /bin/sh
# preinst script for xymon

set -e

# Workaround for http://bugs.debian.org/560317 in case debconf is too old like on Squeeze
export DPKG_MAINTSCRIPT_PACKAGE=${DPKG_MAINTSCRIPT_PACKAGE:-xymon}
export DPKG_MAINTSCRIPT_NAME=${DPKG_MAINTSCRIPT_NAME:-preinst}

case "$1" in
    install|upgrade)
	# stop the client when the server is installed
	invoke-rc.d xymon-client stop || true
	;;
esac

# Automatically added by dh_installinit/13.20
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/xymon" ] ; then
	chmod +x "/etc/init.d/xymon" >/dev/null || true
fi
# End automatically added section


exit 0
