#!/bin/sh
# postinst script for firebird3.0-superclassic

set -e
. /usr/share/debconf/confmodule
set -u

if [ -n "${DEBIAN_FIREBIRD_DEBUG:-}" ]; then
    set -x
fi
# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#
# quoting from the policy:
#     Any necessary prompting should almost always be confined to the
#     post-installation script, and should be protected with a conditional
#     so that unnecessary prompting doesn't happen if a package's
#     installation fails and the `postinst' is called with `abort-upgrade',
#     `abort-remove' or `abort-deconfigure'.

FB_VER=3.0
. /usr/share/firebird${FB_VER}-common/functions.sh

checkFirebirdAccount() {
    getent passwd firebird > /dev/null || \
    adduser --system --quiet --home /var/lib/firebird \
        --group --gecos "Firebird Database Administator" firebird
}

debhelper_hook()
{
    # This is here in order to make debhelper_hook() a valid
    # shell procedure in the case when debhelper has nothing
    # for us
    DuMmYnOtUsEd="dummy"

# Automatically added by dh_installtmpfiles/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "$(command -v systemd-tmpfiles)" ]; then
		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create firebird3.0.conf || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/default/firebird3.0 3.0.0\~svn\+61473.ds4-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/firebird3.0" ]; then
		update-rc.d firebird3.0 defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native firebird3.0 $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'firebird3.0.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'firebird3.0.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'firebird3.0.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'firebird3.0.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'firebird3.0.service' >/dev/null || true
	fi
fi
# End automatically added section

}


case "$1" in
    configure)
        checkFirebirdAccount

        firebird_config_postinst "$@"

        # move the log files from /var/log to /var/log/firebird
        if [ -n "${2:-}" ] \
            && dpkg --compare-versions "$2" lt "3.0.0~svn+61473.ds4-1~"
        then
            find /var/log -maxdepth 1 -name 'firebird3.0.log*' \
                -exec mv --backup=numbered '{}' /var/log/firebird/ \;
        fi
    ;;

    *)
        debhelper_hook "$@"
    ;;
esac

exit 0

# vi: set sw=4 ts=8 filetype=sh sts=4 :
