#!/bin/sh
set -e

# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p pyroman 
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p pyroman  || true
fi

# End automatically added section
# Automatically added by dh_installdeb/13.15.3
dpkg-maintscript-helper rm_conffile /etc/default/pyroman 0.6.0-1\~ pyroman -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/pyroman" ]; then
		update-rc.d pyroman defaults-disabled >/dev/null || exit 1
	fi
fi
# End automatically added section
