#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.15.3
dpkg-maintscript-helper rm_conffile /etc/default/pyroman 0.6.0-1\~ pyroman -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/pyroman" ] ; then
	chmod +x "/etc/init.d/pyroman" >/dev/null || true
fi
# End automatically added section
