#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.15.3
dpkg-maintscript-helper rm_conffile /etc/default/pyroman 0.6.0-1\~ pyroman -- "$@"
# End automatically added section

# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1; then
	py3clean -p pyroman 
else
	dpkg -L pyroman | sed -En -e '/^(.*)\/(.+)\.py$/s,,rm "\1/__pycache__/\2".*,e'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section
