#!/bin/sh 

set -e


ipmievd_initd_failed() {
    :
}

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ipmievd" ] ; then
	chmod -x "/etc/init.d/ipmievd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d ipmievd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/default/ipmitool 1.8.18-11\~ ipmitool -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ipmievd.service' >/dev/null || true
	fi
fi
# End automatically added section

