#!/bin/sh

set -e

BIN=/usr/bin/wget
SOURCE=https://www.iana.org/assignments/enterprise-numbers.txt
DEST=/usr/share/misc/enterprise-numbers.txt


ipmievd_initd_failed() {
    echo "Unable to start ipmievd during installation.  Trying to disable."
    if [ -f /etc/default/ipmievd ] && \
           grep -q ^ENABLED=\"false\" /etc/default/ipmievd ; then
        :
    else
        touch /etc/default/ipmievd
        echo "ENABLED=\"false\"" >> /etc/default/ipmievd
    fi
}

[ -x $BIN ] || exit 0

#echo "Download enterprise-numbers.txt"

#$BIN -O $DEST $SOURCE  >/dev/null 2>&1


# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/default/ipmitool 1.8.18-11\~ ipmitool -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/ipmievd" ]; then
		update-rc.d ipmievd defaults-disabled >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native ipmievd $_dh_action || ipmievd_initd_failed
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'ipmievd.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'ipmievd.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'ipmievd.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'ipmievd.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'ipmievd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'ipmievd.service' >/dev/null || true
	fi
fi
# End automatically added section

