#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/default/ipmitool 1.8.18-11\~ ipmitool -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/ipmievd" ] ; then
	chmod +x "/etc/init.d/ipmievd" >/dev/null || true
fi
# End automatically added section
