#!/bin/sh

set -e

ipmievd_initd_failed() {
    :
}

# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'ipmievd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/ipmievd" ] ; then
	invoke-rc.d --skip-systemd-native ipmievd stop || ipmievd_initd_failed
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.1
dpkg-maintscript-helper rm_conffile /etc/default/ipmitool 1.8.18-11\~ ipmitool -- "$@"
# End automatically added section

