#!/bin/sh

set -e

# Automatically added by dh_installinit/13.14.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/rtcw-server" ] ; then
	chmod -x "/etc/init.d/rtcw-server" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d rtcw-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'rtcw-server.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/3.0.12-1
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.lib.rtcw.iowolfded" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.lib.rtcw.iowolfded" || true
    rm -f "/etc/apparmor.d/force-complain/usr.lib.rtcw.iowolfded" || true
    rm -f "/etc/apparmor.d/local/usr.lib.rtcw.iowolfded" || true
    rm -f /var/cache/apparmor/*/"usr.lib.rtcw.iowolfded" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section


if [ "$1" = "purge" ] ; then
    # Lock account on purge
    if [ -f /etc/shadow ]; then
        usermod -L -e 1 rtcw-server
    else
        usermod -L rtcw-server
    fi
    rm -r /var/games/rtcw-server
    rmdir --ignore-fail-on-non-empty /var/games
fi
