#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'ostree-boot-complete.service' 'ostree-finalize-staged-hold.service' 'ostree-finalize-staged.service' 'ostree-prepare-root.service' 'ostree-remount.service' >/dev/null || true
fi
# End automatically added section
