#!/bin/sh
set -e

#if [ remove = "$1" ]; then
#    dpkg-divert --package ld10k1 --remove --rename \
#        --divert /usr/share/alsa/cards/EMU10K1.conf.real \
#        /usr/share/alsa/cards/EMU10K1.conf
#fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ld10k1" ] ; then
	chmod -x "/etc/init.d/ld10k1" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d ld10k1 remove >/dev/null
fi
# End automatically added section

