#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    BASEDIR="/var/lib/tftpd"
    if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
        db_get atftpd/basedir
        if [ "$RET" ]; then
            BASEDIR="$RET"
        fi
    fi

    if [ -d $BASEDIR ]; then
	rmdir --ignore-fail-on-non-empty $BASEDIR
    fi

    # logrotate 
    rm -f /etc/logorotate.d/atftpd

    # init.d config file
    if [ -r /etc/default/atftpd ]; then
	rm -f /etc/default/atftpd
    fi
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/atftpd" ] ; then
	chmod -x "/etc/init.d/atftpd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d atftpd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'atftpd.service' 'atftpd.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

