#!/bin/sh

set -e

if [ "$1" = "failed-upgrade" ] && dpkg --compare-versions "$2" lt-nl "0.7.git20210915-2" && [ -f /etc/default/atftpd ]; then
    sed -i -e 's/^OPTIONS=\\"/OPTIONS="/' -e 's/\\"$/"/' /etc/default/atftpd
    echo "Fix broken syntax in /etc/default/atftpd"
fi

# Stops daemon if it is running under our control
if [ -x /etc/init.d/atftpd ]; then 
    if which invoke-rc.d > /dev/null ; then
	invoke-rc.d --quiet atftpd stop
    else
	/etc/init.d/atftpd stop
    fi
fi	

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'atftpd.service' 'atftpd.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/atftpd" ] ; then
	invoke-rc.d --skip-systemd-native atftpd stop || exit 1
fi
# End automatically added section


exit 0
