#!/bin/sh
# prerm script for dbeacon

set -e

if [ $1 = 'remove' ]; then
	deluser Debian-dbeacon
fi

# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'dbeacon.service' >/dev/null || true
fi
# End automatically added section


exit 0
