#!/bin/sh

set -e

case "$1" in
    configure)
    # Source debconf library.
    . /usr/share/debconf/confmodule
    db_version 2.0

    adduser --quiet --system --group --no-create-home  --home /var/lib/canna --gecos "Canna server" --disabled-password --disabled-login canna
    chown canna:canna /var/lib/canna /var/lib/canna/dic /var/lib/canna/dic/canna /var/lib/canna/dic/canna/*.ctd
    mkdir -p /var/log/canna
    chown canna:canna /var/log/canna
    update-canna-dics_dir

    # debconf processing for running cannaserver

    db_get canna/run_cannaserver
    if [ "$RET" = "true" ] ; then
	CANNA_SERVER_RUN=yes

	db_get canna/run_with_inet
	if [ "$RET" = "true" ] ; then
	    CANNA_ENABLE_INET=yes

	    db_get canna/manage_allow_hosts_with_debconf
	    if [ "$RET" = "true" ] ; then
		CANNA_MANAGE_CANNAHOST=yes		
		db_get canna/allow_hosts
		CANNA_ALLOW_HOSTS="$RET"
	    else
		CANNA_MANAGE_CANNAHOST=no
		CANNA_ALLOW_HOSTS="unix"
	    fi
	else
	    CANNA_ENABLE_INET=no
	    CANNA_MANAGE_CANNAHOST=yes
	    CANNA_ALLOW_HOSTS="unix"
	fi
    else
	CANNA_SERVER_RUN=no
	CANNA_ENABLE_INET=no
	CANNA_MANAGE_CANNAHOST=yes
	CANNA_ALLOW_HOSTS="unix"
    fi
    db_stop

    if [ -e /etc/default/canna ] ; then
	cp /etc/default/canna /etc/default/canna.dpkg-old
	rm -f /etc/default/canna
    fi

    cat > /etc/default/canna <<EOF
# Enable cannaserver
CANNA_SERVER_RUN=${CANNA_SERVER_RUN}

# Enable inet socket connection
CANNA_ENABLE_INET=${CANNA_ENABLE_INET}
EOF

    if [ "${CANNA_MANAGE_CANNAHOST}" = "yes" ] ; then
	    TMPFILE=`mktemp`
	    for HOST in ${CANNA_ALLOW_HOSTS}
	      do
	      echo $HOST >> ${TMPFILE}
	    done
	    if [ -e /etc/hosts.canna ] ; then
		cmp -s ${TMPFILE} /etc/hosts.canna || \
		    (cp /etc/hosts.canna /etc/hosts.canna.dpkg-old && cp ${TMPFILE} /etc/hosts.canna)
	    else
		cp ${TMPFILE} /etc/hosts.canna
	    fi
	    chmod 644 /etc/hosts.canna
	    rm -f ${TMPFILE}
    else
	[ ! -e /etc/hosts.canna ] && echo unix > /etc/hosts.canna
	chmod 644 /etc/hosts.canna
    fi

    # Install files from template dir to /var
    if [ -f /var/lib/canna/dic/canna/iroha.cbd ] && [ -f /var/lib/canna/dic/canna/iroha.cld ] && [ -f /var/lib/canna/dic/canna/bushu.cld ]; then
	: # the files already exist, ignore
	echo "iroha dics are already installed... ignoring" >&2
    else
	for FILE in iroha.cbd iroha.cld bushu.cld; do
	    cp -p /usr/lib/canna/debian-template/$FILE /var/lib/canna/dic/canna/
	    chown canna:canna /var/lib/canna/dic/canna/$FILE
	done
	echo "Installed new iroha dic" >&2
    fi

    if [ -f /var/lib/canna/dic/canna/fuzokugo.cbd ] && [ -f /var/lib/canna/dic/canna/fuzokugo.cld ]; then
	: # the files already exist, ignore
	echo "fuzokugo dics are already installed... ignoring" >&2
    else
	cp -p /usr/lib/canna/debian-template/fuzokugo.cbd /var/lib/canna/dic/canna/
	chown canna:canna /var/lib/canna/dic/canna/fuzokugo.cbd
	rm -f /var/lib/canna/dic/canna/fuzokugo.cld
	echo "Installed new fuzokugo dics" >&2
    fi

    
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    
    *)
    ;;
esac

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/canna" ]; then
		update-rc.d canna defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native canna $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'canna.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'canna.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'canna.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'canna.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'canna.service' >/dev/null || true
	fi
fi
# End automatically added section

