#!/bin/sh

set -e

case "$1" in
    purge)
        userdel didiwiki || true
	rm -f /var/run/didiwiki.pid

	if [ "`readlink /var/lib/didiwiki/styles.css`" = "/etc/didiwiki/styles.css" ]
	then
	    rm /var/lib/didiwiki/styles.css
	fi

    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/didiwiki" ] ; then
	chmod -x "/etc/init.d/didiwiki" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d didiwiki remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'didiwiki.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
