#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/sm.puri.Calls-daemon.desktop 41\~alpha-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/sm.puri.Calls.desktop 0.2.0-1\~ -- "$@"
# End automatically added section
