#!/bin/bash

set -e

case "$1" in
    upgrade)
        [ -d  /run/systemd/system/ ] && deb-systemd-invoke stop log2ram.service log2ram-daily.timer
        exit 0
        ;;
    *)
        [ -d  /run/systemd/system/ ] && deb-systemd-invoke stop log2ram.service log2ram-daily.timer
        [ -d  /run/systemd/system/ ] && deb-systemd-invoke disable log2ram.service log2ram-daily.timer
        exit 0
        ;;
esac


