#!/bin/sh
set -e
# Automatically added by dh_installinit/13.16
if [ "$1" = "remove" ] && [ -x "/etc/init.d/netscript" ] ; then
	chmod -x "/etc/init.d/netscript" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d netscript remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.16
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'netscript.service' >/dev/null || true
	fi
fi
# End automatically added section
