#!/bin/sh
set -e

if test -f /usr/local/lib/libeibclient.so.0 ; then
    echo "*** You have old eibd libraries lying around in /usr/local/lib." >&2
    echo "*** Remove them before installing knxd." >&2
    exit 1
fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/knxd" ] ; then
	chmod +x "/etc/init.d/knxd" >/dev/null || true
fi
# End automatically added section

