#!/bin/sh
set -e
# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/smcroute" ] ; then
	chmod -x "/etc/init.d/smcroute" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d smcroute remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.15.3
dpkg-maintscript-helper mv_conffile /etc/startup.sh /etc/smcroute/startup.sh 2.0.0-4 -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'smcroute-helper.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'smcroute.service' >/dev/null || true
	fi
fi
# End automatically added section
