#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'smcroute-helper.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'smcroute.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/smcroute" ] ; then
	invoke-rc.d --skip-systemd-native smcroute stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.15.3
dpkg-maintscript-helper mv_conffile /etc/startup.sh /etc/smcroute/startup.sh 2.0.0-4 -- "$@"
# End automatically added section
