#!/bin/sh -e
# postrm

USERNAME="Debian-console-log"

# Automatically added by dh_installinit/13.3.1
if [ "$1" = "purge" ] ; then
	update-rc.d console-log remove >/dev/null
fi
# End automatically added section


[ -n "$CONLOGDEBUG" ] && set -x

if [ "$1" = "purge" ]; then
    if command -v deluser >/dev/null; then
        echo >&2 'Removing system user'
        deluser --remove-home --system $USERNAME || deluser --system $USERNAME
    else
        echo >&2 'Not removing system user, deluser not found'
    fi
fi

# end of file
