#!/bin/sh
set -e
# Automatically added by dh_installinit/13.3.1
if [ -x "/etc/init.d/console-log" ] && [ "$1" = remove ]; then
	invoke-rc.d console-log stop || exit 1
fi
# End automatically added section
