#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'openqa-enqueue-asset-cleanup.timer' 'openqa-enqueue-audit-event-cleanup.timer' 'openqa-enqueue-bug-cleanup.timer' 'openqa-enqueue-git-auto-update.timer' 'openqa-enqueue-result-cleanup.timer' 'openqa-gru.service' 'openqa-livehandler.service' 'openqa-minion-restart.path' 'openqa-scheduler.service' 'openqa-setup-db.service' 'openqa-websockets.service' 'openqa-webui.service' >/dev/null || true
	fi
fi
# End automatically added section
