#!/bin/sh
set -e

if [ -x "/etc/init.d/stun" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d stun stop || exit $? 
	else
		/etc/init.d/stun stop || exit $?
	fi
fi

# Automatically added by dh_installinit/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/stun" ] ; then
	invoke-rc.d --skip-systemd-native stun stop || exit 1
fi
# End automatically added section

