#!/bin/bash
set -euo pipefail

if [[ ${1:-} == configure ]]; then
	pkill -HUP -x syncthing || true
fi

# Automatically added by dh_installsystemduser/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ]; then
		if deb-systemd-helper --user debian-installed 'syncthing.service' ; then
			# The following line should be removed in trixie or trixie+1
			deb-systemd-helper --user unmask 'syncthing.service' >/dev/null || true

			if deb-systemd-helper --quiet --user was-enabled 'syncthing.service' ; then
				# Create new symlinks, if any.
				deb-systemd-helper --user enable 'syncthing.service' >/dev/null || true
			fi
		fi

		# Update the statefile to add new symlinks (if any), which need to be cleaned
		# up on purge. Also remove old symlinks.
		deb-systemd-helper --user update-state 'syncthing.service' >/dev/null || true
	fi
fi
# End automatically added section

