#!/bin/sh
set -e
# Automatically added by dh_installinit/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/timidity" ] ; then
	invoke-rc.d timidity stop || exit 1
fi
# End automatically added section
