#!/bin/sh
set -e
# Automatically added by dh_installinit/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/mpt-statusd" ] ; then
	invoke-rc.d --skip-systemd-native mpt-statusd stop || exit 1
fi
# End automatically added section
