#!/bin/sh
set -e

if [ "$1" = purge ]; then
  rm -f /var/log/binkd/binkd*
  rmdir --ignore-fail-on-non-empty /var/log/binkd/ 2>/dev/null || true
fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/binkd" ] ; then
	chmod -x "/etc/init.d/binkd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d binkd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'binkd.service' >/dev/null || true
	fi
fi
# End automatically added section


