#!/bin/sh -e

# Automatically added by dh_installsystemd/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'binkd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/binkd" ] ; then
	invoke-rc.d --skip-systemd-native binkd stop || exit 1
fi
# End automatically added section


# must be executed after /etc/init.d/binkd stop
if command -v update-inetd > /dev/null; then
  update-inetd --remove '^binkp[ \t]'
fi

