#!/bin/sh

set -e

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
    dpkg-maintscript-helper rm_conffile /usr/lib/systemd/ntp-units.d/openntpd.list 1:5.7p4-1 -- "$@"
    dpkg-maintscript-helper rm_conffile /etc/apparmor.d/usr.sbin.ntpd 1:5.7p4-1 -- "$@"
fi

# Automatically added by dh_installinit/13.11.9
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/openntpd" ] ; then
	chmod +x "/etc/init.d/openntpd" >/dev/null || true
fi
# End automatically added section


exit 0
