#!/bin/sh
set -e
# Automatically added by dh_installinit/13.23
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/w1retap" ] ; then
	chmod +x "/etc/init.d/w1retap" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'w1retap.service' >/dev/null || true
fi
# End automatically added section
