#!/bin/sh
set -e
# Automatically added by dh_installinit/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/w1retap" ] ; then
	invoke-rc.d --skip-systemd-native w1retap stop || exit 1
fi
# End automatically added section
