#!/bin/sh
set -eu

if test "$1" = purge; then
    if test -d /etc/ionit; then
        rmdir --ignore-fail-on-non-empty /etc/ionit
    fi
fi

# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ionit.service' >/dev/null || true
	fi
fi
# End automatically added section

