#!/bin/sh
set -e
# Automatically added by dh_installinit/13.7.1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/gearman-server" ] ; then
	invoke-rc.d --skip-systemd-native gearman-server stop || exit 1
fi
# End automatically added section
