#! /bin/sh -e

invoke_failure() {
    # invoke-rc.d failed
    return
}

# Automatically added by dh_installsystemd/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'sssd-autofs.service' 'sssd-autofs.socket' 'sssd-nss.service' 'sssd-nss.socket' 'sssd-pam.service' 'sssd-pam.socket' 'sssd-ssh.service' 'sssd-ssh.socket' 'sssd-sudo.service' 'sssd-sudo.socket' 'sssd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/sssd" ] ; then
	invoke-rc.d --skip-systemd-native sssd stop || invoke_failure
fi
# End automatically added section


