#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper mv_conffile /etc/mumble-server.ini /etc/mumble/mumble-server.ini 1.5.517-1\~ -- "$@"
# End automatically added section
