#!/bin/sh
set -e

# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p loggerhead 
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p loggerhead  || true
fi

# End automatically added section
# Automatically added by dh_installinit/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/loggerhead" ]; then
		update-rc.d loggerhead defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native loggerhead $_dh_action || exit 1
	fi
fi
# End automatically added section


adduser --system --group --home / loggerhead > /dev/null 2>&1
chown loggerhead /var/log/loggerhead
