#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/gridengine-exec" ] ; then
	invoke-rc.d gridengine-exec stop || exit 1
fi
# End automatically added section
