#!/bin/sh
set -e

# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p pagure-ev-server /usr/share/pagure-ev-server
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p pagure-ev-server /usr/share/pagure-ev-server || true
fi

# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'pagure-ev-server.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'pagure-ev-server.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'pagure-ev-server.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'pagure-ev-server.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'pagure-ev-server.service' >/dev/null || true
fi
# End automatically added section
