#!/bin/sh
set -e
# Automatically added by dh_installinit/13.2
if [ -x "/etc/init.d/dns2tcp" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native dns2tcp stop || exit 1
fi
# End automatically added section
