#!/bin/sh

set -e

case "$1" in
    purge)
        rm -rf /var/log/filetea
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "remove" ] && [ -x "/etc/init.d/filetea" ] ; then
	chmod -x "/etc/init.d/filetea" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d filetea remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'filetea.service' >/dev/null || true
	fi
fi
# End automatically added section


if dpkg-maintscript-helper supports rm_conffile; then
   dpkg-maintscript-helper rm_conffile /etc/default/filetea 0.1.16-2~ -- "$@"
fi

exit 0
