#!/bin/sh

set -e

# Automatically added by dh_installinit/13.15.3
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/filetea" ] ; then
	chmod +x "/etc/init.d/filetea" >/dev/null || true
fi
# End automatically added section


if dpkg-maintscript-helper supports rm_conffile; then
   dpkg-maintscript-helper rm_conffile /etc/default/filetea 0.1.16-2~ -- "$@"
fi

exit 0
