#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'filetea.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.15.3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/filetea" ] ; then
	invoke-rc.d --skip-systemd-native filetea stop || exit 1
fi
# End automatically added section
