#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/unscd" ] ; then
	chmod -x "/etc/init.d/unscd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d unscd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'unscd.service' >/dev/null || true
	fi
fi
# End automatically added section
