#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.6
if [ "$1" = "remove" ] && [ -x "/etc/init.d/rotter" ] ; then
	chmod -x "/etc/init.d/rotter" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d rotter remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installmenu/13.11.6
if [ -x "`command -v update-menus`" ] && [ -x "$DPKG_ROOT`command -v update-menus`" ]; then update-menus ; fi
# End automatically added section
