#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.6
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/rotter" ] ; then
	invoke-rc.d rotter stop || exit 1
fi
# End automatically added section
