#!/bin/sh
# post-removal script for Solid POP3

set -e

# Automatically added by dh_installinit/13.3.1
if [ "$1" = "purge" ] ; then
	update-rc.d solid-pop3d remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.3.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


if [ "X$1" = "Xpurge" ]; then
	if test -x /usr/sbin/update-inetd >/dev/null 2>&1; then
		update-inetd --pattern "spop3d" --remove pop3 || true
	fi
	deluser --system --quiet spop3d > /dev/null || true
	
	rm -f /etc/default/solid-pop3d
fi
