#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
	rm -f /etc/default/bitlbee
	deluser --system bitlbee > /dev/null || true
	rm -rf /var/lib/bitlbee ## deluser doesn't seem to do this for homedirs in /var
fi

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/bitlbee" ] ; then
	chmod -x "/etc/init.d/bitlbee" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d bitlbee remove >/dev/null
fi
# End automatically added section

