#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.20
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'guerillabackup-generator.service' 'guerillabackup-transfer.service' >/dev/null || true
fi
# End automatically added section
