#!/bin/sh
# based on arpwatch.postinst: v11 2004/09/15 KELEMEN Peter <fuji@debian.org>
# postinst: v1 2006/01/12 Jan Wagner <waja@cyconet.org>

set -e

NUSER="polw"
NGROUP="polw"
NHOME="/var/lib/$NUSER"
NGECOS="policy-weight user"

case "$1" in
	configure)
		# Take care of group.
		if NGROUP_ENTRY=`getent group $NGROUP`; then
			# group exists
			:
		else
			# group does not exist yet
			addgroup --quiet --system $NGROUP
		fi

		# Take care of user.
		if NUSER_ENTRY=`getent passwd $NUSER`; then
			# user exists
			adduser --quiet $NUSER $NGROUP
		else
			# user does not exist yet
			adduser --quiet --system	\
				--ingroup $NGROUP	\
				--gecos "$NGECOS"	\
				--home $NHOME		\
				--no-create-home	\
				--shell /bin/sh		\
				--disabled-login	\
				--disabled-password	\
				--shell /bin/false	\
				$NUSER
		fi

		# Set up home directory.
		if [ -d $NHOME ]; then
			chown -R ${NUSER}:${NGROUP} $NHOME
			chmod -R o-rwX $NHOME
		fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installinit/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/policyd-weight" ]; then
		update-rc.d policyd-weight defaults 19 21 >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native policyd-weight $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'policyd-weight.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'policyd-weight.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'policyd-weight.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'policyd-weight.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'policyd-weight.service' >/dev/null || true
	fi
fi
# End automatically added section

