#!/bin/sh
# based on arpwatch.postrm: v2 2004/09/15 KELEMEN Peter <fuji@debian.org>
# postrm: v1 2006/10/12 Jan Wagner <waja@cyconet.org>

NUSER="polw"
NGROUP="polw"

set -e

pathfind() {
    OLDIFS="$IFS"
    IFS=:
    for p in $PATH; do
        if [ -x "$p/$*" ]; then
            IFS="$OLDIFS"
            return 0
        fi
    done
    IFS="$OLDIFS"
    return 1
}

case "$1" in
	purge)
		# find first and last SYSTEM_UID numbers
		for LINE in `grep SYSTEM_UID /etc/adduser.conf | grep -v "^#"`; do
			case $LINE in
				FIRST_SYSTEM_UID*)
					FIST_SYSTEM_UID=`echo $LINE | cut -f2 -d '='`
					;;
				LAST_SYSTEM_UID*)
					LAST_SYSTEM_UID=`echo $LINE | cut -f2 -d '='`
					;;
				*)
					;;
			esac
		done
		# remove system account if necessary
		if [ -n "$FIST_SYSTEM_UID" ] && [ -n "$LAST_SYSTEM_UID" ]; then
			if USERID=`getent passwd $NUSER | cut -f 3 -d ':'`; then
				if [ -n "$USERID" ]; then
					if [ "$FIST_SYSTEM_UID" -le "$USERID" ] && \
						[ "$USERID" -le "$LAST_SYSTEM_UID" ] && \
							pathfind deluser; then 
								deluser --quiet $NUSER || true
								# And then remove the group
								GROUPID=`getent group $NGROUP | cut -f 3 -d ':'`
								if [ -n "$GROUPID" ] && pathfind delgroup;  then
									delgroup --quiet $NGROUP || true
								fi
					fi
				fi
			fi
		fi
		;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/policyd-weight" ] ; then
	chmod -x "/etc/init.d/policyd-weight" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d policyd-weight remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'policyd-weight.service' >/dev/null || true
	fi
fi
# End automatically added section

