#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/nova-novncproxy" ] ; then
	chmod +x "/etc/init.d/nova-novncproxy" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/nova-spicehtml5proxy" ] ; then
	chmod +x "/etc/init.d/nova-spicehtml5proxy" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/nova-serialproxy" ] ; then
	chmod +x "/etc/init.d/nova-serialproxy" >/dev/null || true
fi
# End automatically added section
