#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
    if getent passwd goiardi >/dev/null; then
        if which deluser >/dev/null 2>&1; then
            deluser --quiet --system goiardi || echo "Could not remove goiardi user."
        fi
    fi

    # Get rid of cruft
    rm -rf /var/lib/goiardi
    rm -rf /var/log/goiardi
    rm -f /etc/goiardi/admin.pem \
          /etc/goiardi/chef-validator.pem \
          /etc/goiardi/chef-webui.pem
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/goiardi" ] ; then
	chmod -x "/etc/init.d/goiardi" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d goiardi remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'goiardi.service' >/dev/null || true
	fi
fi
# End automatically added section

