#!/bin/sh

set -e

if ! /usr/bin/getent passwd gkrellmd >/dev/null; then
  useradd --system --no-user-group gkrellmd
fi

# Automatically added by dh_installinit/13.14.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/gkrellmd" ]; then
		update-rc.d gkrellmd defaults 21 >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native gkrellmd $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0
