#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/pcsd-ruby" ] ; then
	chmod +x "/etc/init.d/pcsd-ruby" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/pcsd" ] ; then
	chmod +x "/etc/init.d/pcsd" >/dev/null || true
fi
# End automatically added section
