#!/bin/sh
# postinst script for dmarcts-report-parser
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "${1}" in
        'configure')
                # setup dmarcts-report-parser system user account
                if ! getent 'passwd' '_dmarcts' >'/dev/null'; then
                        echo 'Creating _dmarcts system user.' >&2
                        # if adduser >= 3.122; then use --allow-bad-names
                        # if not; then use --force-badname
                        badname_option="--allow-bad-names"
                        version=`dpkg-query --show --showformat='${Version}' adduser`
                        if dpkg --compare-versions "$version" "lt" "3.122"; then
                            badname_option="--force-badname"
                        fi

                        adduser --system \
                                --disabled-password --disabled-login \
                                --shell /bin/false --group \
                                --home /var/lib/dmarcts \
                                "$badname_option" \
                                _dmarcts
                fi
                ;;
        'abort-upgrade'|'abort-remove'|'abort-deconfigure')
                ;;
        *)
                echo "postinst called with unknown argument '${1}'" >&2
                exit 1
                ;;
esac

# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'dmarcts-report-parser.timer' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'dmarcts-report-parser.timer'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'dmarcts-report-parser.timer' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'dmarcts-report-parser.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'dmarcts-report-parser.service' 'dmarcts-report-parser.timer' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
