#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/cron.daily/samba 2:4.19.3\+dfsg-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/logrotate.d/samba 2:4.19.4\+dfsg-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/samba-ad-dc 2:4.21.1\+dfsg-1 -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/smbd" ] ; then
	chmod +x "/etc/init.d/smbd" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/nmbd" ] ; then
	chmod +x "/etc/init.d/nmbd" >/dev/null || true
fi
# End automatically added section
