#!/bin/sh
# postrm script for mopidy

set -e

if [ "$1" = "purge" ]; then
    rm -f /var/log/mopidy/mopidy.log*
    rm -f /var/log/mopidy/mopidy-debug.log*

    deluser --quiet --system mopidy > /dev/null || true

    rm -rf /var/lib/mopidy
fi

# Automatically added by dh_installinit/13.16
if [ "$1" = "remove" ] && [ -x "/etc/init.d/mopidy" ] ; then
	chmod -x "/etc/init.d/mopidy" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d mopidy remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.16
dpkg-maintscript-helper rm_conffile /etc/mopidy/logging.conf 2.3.1-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'mopidy.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.16
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

