#! /bin/sh

set -e

# Automatically added by dh_installinit/13.20
if [ "$1" = "remove" ] && [ -x "/etc/init.d/c-icap" ] ; then
	chmod -x "/etc/init.d/c-icap" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d c-icap remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'c-icap.service' >/dev/null || true
	fi
fi
# End automatically added section


if [ $1 = purge ]; then
    rm -rf /var/run/c-icap
    if [ -x "$(command -v deluser)" ]; then
      deluser --quiet --system c-icap > /dev/null || true
    else
      echo >&2 "not removing c-icap system account because deluser command was not found"
    fi
    if [ -x "$(command -v delgroup)" ]; then
      delgroup --quiet --system c-icap > /dev/null || true
    else
      echo >&2 "not removing c-icap group because delgroup command was not found"
    fi
fi

exit 0
