#!/bin/sh

set -e

if [ "x$1" = xconfigure ]; then
        adduser --quiet --system --no-create-home --home /var/run/c-icap c-icap
        addgroup --quiet --system c-icap
        chown c-icap /var/log/c-icap
fi

# Automatically added by dh_installinit/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/c-icap" ]; then
		update-rc.d c-icap defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native c-icap $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'c-icap.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'c-icap.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'c-icap.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'c-icap.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'c-icap.service' >/dev/null || true
fi
# End automatically added section


exit 0
