#!/bin/sh

set -e

del_override() {
    if dpkg-statoverride --list $1 >/dev/null 2>&1; then
	dpkg-statoverride --remove $1
    fi
}

if [ "$1" = "purge" ]; then
    del_override /etc/courier/authdaemonrc
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/courier-authdaemon" ] ; then
	chmod -x "/etc/init.d/courier-authdaemon" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d courier-authdaemon remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'courier-authdaemon.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
