#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/patroni" ] ; then
	chmod -x "/etc/init.d/patroni" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d patroni remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'patroni.service' >/dev/null || true
	fi
fi
# End automatically added section
