#!/bin/sh
### BEGIN INIT INFO
# Provides:          opensm
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start opensm subnet manager.
# Description:       Enable opensm subnet manager.
### END INIT INFO

. /lib/lsb/init-functions

PORTS=""
[ -f /etc/default/opensm ] &&  . /etc/default/opensm

[ -x /usr/sbin/opensm ] || exit 0

if [ ! -f /sys/class/infiniband_mad/abi_version ] ; then
echo "No infiniband adapters found."
exit 0
fi


start () {

if [ "$PORTS" = "ALL" ]; then
PORTS=`/usr/sbin/ibstat -p`
fi

if [ "$PORTS" = "NONE" ]; then
echo "opensm disabled."
exit 0
fi

for PORT in $PORTS ; do
    echo -n "Starting opensm on $PORT: "
    start-stop-daemon --start --quiet --make-pidfile  --pidfile /var/run/opensm-$PORT --background --exec /usr/sbin/opensm -- -g $PORT -f /var/log/opensm.$PORT.log
    RETVAL=$?
    echo
done
}

stop () {

if [ "$PORTS" = "ALL" ]; then
PORTS=`/usr/sbin/ibstat -p`
fi

if [ "$PORTS" = "NONE" ]; then
    echo "opensm disabled."
    exit 0
fi
for PORT in $PORTS ; do
    echo -n "Shutting down opensm on $PORT: "
    start-stop-daemon --stop --pidfile /var/run/opensm-$PORT 
    RETVAL=$?
    echo
done
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart | force-reload )
        stop
	start
        ;;
    reload)
    echo "Reloading opensm configuration..."
        killall -HUP opensm
	RETVAL=$?
	echo "done"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|force-reload}"
        RETVAL=1
        ;;
esac

exit $RETVAL;
