#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/rbldns" ] ; then
	chmod -x "/etc/init.d/rbldns" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d rbldns remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_runit/2.16.4
# Unfortunately, we can not assume, that bin:runit-helper package
# is installed at postrm stage.
#
# The only other option is embed whole runit-helper script here,
# into postrm script of -run package, but it would be like static
# linking, requiring rebuild of all reverse dependencies on every
# change of dh-runit.
if [ -z "${DPKG_ROOT:-}" ] && [ -x /usr/lib/runit-helper/runit-helper ] ; then
   NAME='rbldns' ENABLE='no' ONUPGRADE='restart' /usr/lib/runit-helper/runit-helper postrm "$@"
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'rbldns.service' >/dev/null || true
	fi
fi
# End automatically added section
