#!/bin/sh
set -e
# Automatically added by dh_installinit/13.23
if [ "$1" = "remove" ] && [ -x "/etc/init.d/p910nd" ] ; then
	chmod -x "/etc/init.d/p910nd" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d p910nd remove >/dev/null
fi
# End automatically added section
