#!/bin/sh
set -e
# Automatically added by dh_installinit/13.23
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/p910nd" ]; then
		update-rc.d p910nd start 20 2 3 4 5 . stop 20 0 1 6 . >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d p910nd $_dh_action || exit 1
	fi
fi
# End automatically added section
