#!/bin/sh
set -e
# Automatically added by dh_installinit/13.23
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/p910nd" ] ; then
	invoke-rc.d p910nd stop || exit 1
fi
# End automatically added section
