#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'painintheapt-daily.service' 'painintheapt-daily.timer' 'painintheapt-weekly.service' 'painintheapt-weekly.timer' >/dev/null || true
fi
# End automatically added section
