#!/bin/sh
# vim:ts=2:sts=2:et

set -e

divert()
{
  if ! dpkg-divert --list "$1$2" | grep -q diversion; then
    dpkg-divert --package rlinetd --quiet --rename --add \
      --divert "$1.real$2" "$1$2"
  fi
}

divert /usr/sbin/update-inetd
divert /usr/share/man/man8/update-inetd .8.gz


# Automatically added by dh_installinit/13.20
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/rlinetd" ] ; then
	chmod +x "/etc/init.d/rlinetd" >/dev/null || true
fi
# End automatically added section

