#!/bin/sh
set -e

remove_inetd() {
    if [ -x "$(command -v update-inetd)" ]; then
        update-inetd --remove "^.*approx"
    fi
}

remove_cache() {
    rm -rf /var/cache/approx
}

case "$1" in
    remove)
        remove_inetd
        ;;
    purge)
        remove_inetd
        remove_cache
        ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'approx.socket' >/dev/null || true
	fi
fi
# End automatically added section

