#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/bibledit-cloud" ] ; then
	invoke-rc.d bibledit-cloud stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.24.1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'bibledit-cloud.service' >/dev/null || true
fi
# End automatically added section
