#!/bin/sh

set -e

case "$1" in
    remove|purge)
        getent group qat >/dev/null && groupdel qat
        ;;

    *)
        ;;
esac

# Automatically added by dh_installsystemd/13.20
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.20
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'qat.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
