#!/bin/sh

set -e

case "$1" in
    install|upgrade)
        getent group qat >/dev/null || groupadd -r qat
        ;;

    abort-upgrade)
        ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac



exit 0
