#!/bin/sh
set -e
# Automatically added by dh_installinit/13.15.2
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/soundmodem" ] ; then
	invoke-rc.d soundmodem stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.15.2
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'soundmodem.service' >/dev/null || true
fi
# End automatically added section
