#!/bin/sh -e

action=$1
version=$2

case $action in
  upgrade|install )
    if [ -n "$version" ] && dpkg --compare-versions "$version" lt 1.1.28-1
    then
      # Log files should go in /var/log/mgetty
      if [ -f /var/log/acct.log ]; then
	  echo "Moving /var/log/acct.log to /var/log/mgetty..."
	  mv /var/log/acct.log /var/log/mgetty/
      fi
      if [ -f /var/log/faxrunqd.log ]; then
	  echo "Moving /var/log/faxrunqd.log to /var/log/mgetty..."
	  mv /var/log/faxrunqd.log /var/log/mgetty/
      fi
    fi
  ;;
esac

# Automatically added by dh_installinit/13.22
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/mgetty-fax" ] ; then
	chmod +x "/etc/init.d/mgetty-fax" >/dev/null || true
fi
# End automatically added section


