#!/bin/sh
set -e

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'etckeeper.service' 'etckeeper.timer' >/dev/null || true
fi
# End automatically added section


if [ "$1" = remove ]; then
	# In case etckeeper is being purged, stash away a copy of
	# the files purging will need.
	mkdir -p /var/cache/etckeeper/stash
	if [ -e /etc/etckeeper/etckeeper.conf ]; then
		cp -a /etc/etckeeper/etckeeper.conf /var/cache/etckeeper/stash
	fi
	if [ -d /etc/etckeeper/uninit.d ]; then
		cp -a /etc/etckeeper/uninit.d /var/cache/etckeeper/stash
	fi
	if [ -x /usr/bin/etckeeper ]; then
		cp -a /usr/bin/etckeeper /var/cache/etckeeper/stash
	fi
fi
