#!/bin/sh

set -e

if [ "$1" = "remove" ] || [ "$1" = "disappear" ]; then
	update-alternatives --remove targetctl /usr/bin/targetctl-python3
fi
if [ "$1" = "purge" ] ; then
	rm -rf /etc/rtslib-fb-target
fi

# Automatically added by dh_installinit/13.22
if [ "$1" = "remove" ] && [ -x "/etc/init.d/rtslib-fb-targetctl" ] ; then
	chmod -x "/etc/init.d/rtslib-fb-targetctl" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d rtslib-fb-targetctl remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.22
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'rtslib-fb-targetctl.service' >/dev/null || true
	fi
fi
# End automatically added section

