#!/bin/sh
set -e
# Automatically added by dh_installinit/13.22
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/rtslib-fb-targetctl" ] ; then
	chmod +x "/etc/init.d/rtslib-fb-targetctl" >/dev/null || true
fi
# End automatically added section
