#!/bin/sh

set -e

if [ "$1" = "remove" ] || [ "$1" = "disappear" ]; then
	update-alternatives --remove targetctl /usr/bin/targetctl-python3
fi

# Automatically added by dh_installinit/13.22
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/rtslib-fb-targetctl" ] ; then
	invoke-rc.d rtslib-fb-targetctl stop || exit 1
fi
# End automatically added section

# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1; then
	py3clean -p python3-rtslib-fb 
else
	dpkg -L python3-rtslib-fb | sed -En -e '/^(.*)\/(.+)\.py$/s,,rm "\1/__pycache__/\2".*,e'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section

