#!/bin/sh
# vim:ts=2:sw=2:et

set -e

case "$1" in
  remove)
    ;;
  purge)
    update-rc.d -f freeradius remove >/dev/null

    rm -f /var/log/freeradius/radius.log* /var/log/freeradius/radwtmp*
    ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'freeradius.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
