#!/bin/sh
# vim:ts=2:sw=2:et

set -e

case "$1" in
  remove)
    invoke-rc.d freeradius stop
    ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'freeradius.service' >/dev/null || true
fi
# End automatically added section


exit 0
