#!/bin/sh

set -e

rm -f /usr/lib/distcc/* 2>/dev/null || true

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'distcc.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/distcc" ] ; then
	invoke-rc.d --skip-systemd-native distcc stop || exit 1
fi
# End automatically added section

