#!/bin/sh

set -e

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi

if [ -f /usr/share/dbconfig-common/dpkg/prerm.pgsql ]; then
    . /usr/share/dbconfig-common/dpkg/prerm.pgsql
    dbc_sql_substitutions=1
    dbc_go puppetdb "$@"
fi

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'puppetdb.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/puppetdb" ] ; then
	invoke-rc.d --skip-systemd-native puppetdb stop || exit 1
fi
# End automatically added section


exit 0
