#!/bin/sh

set -e

case "$1" in
	purge)
		delgroup fastnetmon || true
		userdel fastnetmon || true
	;;
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
esac

# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'fastnetmon.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
