#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-object-auditor" ] ; then
	chmod +x "/etc/init.d/swift-object-auditor" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-object-reconstructor" ] ; then
	chmod +x "/etc/init.d/swift-object-reconstructor" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-object-replicator" ] ; then
	chmod +x "/etc/init.d/swift-object-replicator" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-object-updater" ] ; then
	chmod +x "/etc/init.d/swift-object-updater" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/swift-object" ] ; then
	chmod +x "/etc/init.d/swift-object" >/dev/null || true
fi
# End automatically added section
