#!/bin/sh

set -e

case "$1" in
    configure)
        # load the module configured in /etc/modules-load.d/pptpd.conf
        if [ -d /run/systemd/system ]; then
            deb-systemd-invoke restart systemd-modules-load.service
        else
            modprobe nf_nat_pptp 2>/dev/null || true
        fi
        ;;
    abort-upgrade | abort-remove | abort-deconfigure) ;;
    *)
        echo "postinst called with unknown argument '$1'"
        exit 1
        ;;
esac

# Automatically added by dh_installinit/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/pptpd" ]; then
		update-rc.d pptpd start 20 2 3 4 5 . stop 20 1 . >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native pptpd $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'pptpd.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'pptpd.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'pptpd.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'pptpd.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'pptpd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'pptpd.service' >/dev/null || true
	fi
fi
# End automatically added section

exit 0
