#!/bin/sh

set -e

case "$1" in
    purge)
        rm -rf /etc/schleuder /var/backup/schleuder /var/lib/schleuder /var/log/schleuder
        rmdir /usr/local/lib/schleuder/filters 2>/dev/null || true
        rmdir /usr/local/lib/schleuder/keyword_handlers 2>/dev/null || true
        rmdir /usr/local/lib/schleuder 2>/dev/null || true
    ;;

    upgrade|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/schleuder-api-daemon" ] ; then
	chmod -x "/etc/init.d/schleuder-api-daemon" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d schleuder-api-daemon remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'schleuder-api-daemon.service' >/dev/null || true
	fi
fi
# End automatically added section

