#!/bin/sh

set -e

SCHLEUDER_DATA_DIR=/var/lib/schleuder
SCHLEUDER_BACKUP_DIR=/var/backup/schleuder

case "$1" in
    upgrade)
        #  Handle existing data if upgrading from schleuder < 3.0
        if dpkg --compare-versions "$2" lt 3.0; then
            # Check for existing data first
            if [ "$(ls $SCHLEUDER_DATA_DIR)" ]; then
                mkdir -p $SCHLEUDER_BACKUP_DIR
                mv $SCHLEUDER_DATA_DIR/* $SCHLEUDER_BACKUP_DIR/
                # Ensure sane permissions of the backup dir.
                chmod 0750 $SCHLEUDER_BACKUP_DIR
                chown schleuder:schleuder $SCHLEUDER_BACKUP_DIR
            fi
        fi
    ;;

    install|abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/schleuder-api-daemon" ] ; then
	chmod +x "/etc/init.d/schleuder-api-daemon" >/dev/null || true
fi
# End automatically added section

