#!/bin/sh
set -e

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/lxd-containers" ] ; then
	chmod -x "/etc/init.d/lxd-containers" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d lxd-containers remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/lxd" ] ; then
	chmod -x "/etc/init.d/lxd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d lxd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'lxd-containers.service' 'lxd.service' 'lxd.socket' >/dev/null || true
	fi
fi
# End automatically added section


# Package removal
if [ "$1" = "remove" ]; then
    # dnsmasq config handling
    if [ -L /etc/dnsmasq.d/lxd ]; then
        echo "Removing lxd dnsmasq configuration"
        rm -f /etc/dnsmasq.d/lxd 2>/dev/null || true

        # Try to restart a potential system wide dnsmasq
        invoke-rc.d dnsmasq restart 2>/dev/null || true
    fi
fi

# Purge
if [ "$1" = "purge" ]; then
    # clean all the things
    rm --one-file-system -Rf /var/lib/lxd /var/log/lxd || true
fi

exit 0
