#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/lxd-containers" ] ; then
	invoke-rc.d --skip-systemd-native lxd-containers stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/lxd" ] ; then
	invoke-rc.d --skip-systemd-native lxd stop || exit 1
fi
# End automatically added section
